// Generated by scripts/mind_idl.py from tests/idl/sample.wit; do not edit.
//! Test interface for the MIND IDL generator (tests/idl_host.rs): v0.2 types and the extensions (enums, bytes,
//! capability results).
#![allow(clippy::all, unused_imports, unused_mut, unused_variables)]
use crate::abi::*;
use crate::ipc::{Endpoint, Received};
use crate::mem::Pages;
use crate::sys::{Error as SysError, Result};
use super::codec::{self, List, Reader, Text, Wire, Writer};
use super::wire::{self, Call, Reject};

pub const PACKAGE: &str = "mind:sample";
pub const VERSION: (u8, u8, u8) = (2, 1, 0);
const MAJOR: usize = 2;

/// Why a call failed.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[repr(u8)]
pub enum Error { #[default] NotFound = 0, Exists = 1, TooBig = 2 }
impl Error {
    /// The case with wire code `code`; None for a code the interface does not define.
    pub fn from_code(code: usize) -> Option<Self> { match code { 0 => Some(Self::NotFound), 1 => Some(Self::Exists), 2 => Some(Self::TooBig), _ => None } }
}
impl Wire for Error {
    const MAX: usize = 1;
    fn encode(&self, w: &mut Writer) -> Option<()> { (*self as u8).encode(w) }
    fn decode(r: &mut Reader) -> Option<Self> { Self::from_code(u8::decode(r)? as usize) }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[repr(u8)]
pub enum Kind { #[default] File = 0, Directory = 1, Device = 2 }
impl Kind {
    /// The case with wire code `code`; None for a code the interface does not define.
    pub fn from_code(code: usize) -> Option<Self> { match code { 0 => Some(Self::File), 1 => Some(Self::Directory), 2 => Some(Self::Device), _ => None } }
}
impl Wire for Kind {
    const MAX: usize = 1;
    fn encode(&self, w: &mut Writer) -> Option<()> { (*self as u8).encode(w) }
    fn decode(r: &mut Reader) -> Option<Self> { Self::from_code(u8::decode(r)? as usize) }
}

/// A directory entry.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Entry { pub name: Text<32>, pub size: u64, pub hidden: bool, pub kind: Kind }
impl Wire for Entry {
    const MAX: usize = <Text<32> as Wire>::MAX + <u64 as Wire>::MAX + <bool as Wire>::MAX + <Kind as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.name.encode(w)?; self.size.encode(w)?; self.hidden.encode(w)?; self.kind.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { name: Wire::decode(r)?, size: Wire::decode(r)?, hidden: Wire::decode(r)?, kind: Wire::decode(r)? }) }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Pair { pub tag: u8, pub entry: Entry }
impl Wire for Pair {
    const MAX: usize = <u8 as Wire>::MAX + <Entry as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.tag.encode(w)?; self.entry.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { tag: Wire::decode(r)?, entry: Wire::decode(r)? }) }
}

/// Scalars only.
pub fn ping(endpoint: Endpoint, x: u32, flag: bool) -> Result<u32> {
    let words = [1 | MAJOR << 8 | ((x) as usize) << 16 | ((flag) as usize) << 48, 0];
    let reply = wire::call(endpoint, words, None)?;
    let _ = wire::check_reply(&reply, [0xffffffff0000, 0x0], false)?;
    Ok(wire::field(&reply, 0, 16, 32) as u32)
}

/// A string argument and a fallible scalar result.
pub fn find(endpoint: Endpoint, dir: u32, name: &str) -> Result<core::result::Result<u32, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        dir.encode(&mut w).ok_or(SysError::Invalid)?;
        codec::encode_str::<64>(name, &mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 2 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 4, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <u32 as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// A list of records as the result.
pub fn list(endpoint: Endpoint, start: u32) -> Result<List<Entry, 16>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        start.encode(&mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 3 | MAJOR << 8, &buffer, length)?;
    let length = wire::buffer_reply(&reply, 706, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <List<Entry, 16> as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? })
}

/// Two bulk arguments and a result without a value.
pub fn put(endpoint: Endpoint, items: &[u16], note: &[u8]) -> Result<core::result::Result<(), Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        codec::encode_slice::<u16, 8>(items, &mut w).ok_or(SysError::Invalid)?;
        codec::encode_bytes::<10>(note, &mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 4 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 0, false, false)?;
    if length != Some(0) { return Err(SysError::Invalid); }
    Ok(Ok(()))
}

/// An enum argument of a buffer call and a nested record result.
pub fn info(endpoint: Endpoint, of: Kind) -> Result<Pair> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        of.encode(&mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 5 | MAJOR << 8, &buffer, length)?;
    let length = wire::buffer_reply(&reply, 45, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <Pair as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? })
}

/// An enum argument of a word call and an optional enum result.
pub fn mode(endpoint: Endpoint, k: Kind) -> Result<Option<Kind>> {
    let words = [6 | MAJOR << 8 | ((k) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, None)?;
    let none = wire::check_reply(&reply, [0xff0000, 0x0], true)?;
    Ok(if none { None } else { Some(Kind::from_code(wire::field(&reply, 0, 16, 8)).ok_or(SysError::Invalid)?) })
}

/// Bytes as the result.
pub fn fetch(endpoint: Endpoint, length: u16, out: &mut [u8]) -> Result<core::result::Result<usize, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        length.encode(&mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 7 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 66, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); let data = codec::decode_bytes::<64>(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)?; out.get_mut(..data.len()).ok_or(SysError::Invalid)?.copy_from_slice(data); data.len() }))
}

/// A capability as the result.
pub fn open(endpoint: Endpoint, id: u32, receive: usize) -> Result<core::result::Result<(), Error>> {
    let words = [8 | MAJOR << 8 | ((id) as usize) << 16, 0];
    let (reply, received) = wire::call_receiving(endpoint, words, None, receive)?;
    match wire::check_cap_reply(&reply, received, receive)? {
        None => Ok(Ok(())),
        Some(code) => Ok(Err(Error::from_code(wire::enum_code(code)?).ok_or(SysError::Invalid)?)),
    }
}

/// An enum result of a word call with a system error.
pub fn sys(endpoint: Endpoint, k: Kind, fail: bool) -> Result<Kind> {
    let words = [9 | MAJOR << 8 | ((k) as usize) << 16 | ((fail) as usize) << 24, 0];
    let reply = wire::call(endpoint, words, None)?;
    wire::check_error(&reply)?;
    let _ = wire::check_reply(&reply, [0xff0000, 0x0], false)?;
    Ok(Kind::from_code(wire::field(&reply, 0, 16, 8)).ok_or(SysError::Invalid)?)
}

/// Size of the scratch buffer `decode` copies a request into (the largest request).
pub const REQUEST_MAX: usize = 70;

/// A request to the `sample` interface that passed the receiver's schema check.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Request<'a> {
    Ping { x: u32, flag: bool },
    Find { dir: u32, name: Text<64> },
    List { start: u32 },
    Put { items: List<u16, 8>, note: &'a [u8] },
    Info { of: Kind },
    Mode { k: Kind },
    Fetch { length: u16 },
    Open { id: u32 },
    Sys { k: Kind, fail: bool },
}

/// Checks a received message against the schema (MC-2.4): method, major version, unused bits, capability kind, and
/// for buffer calls every length and value of a private copy of the request (MC-2.11). `cap` is the slot passed to
/// `recv`; an unexpected capability is dropped (MC-2.12). The `Call` is what the reply functions need.
/// The private copy is `scratch`, which the `bytes` of the request borrow.
pub fn decode<'a>(request: &Received, cap: usize, scratch: &'a mut [u8; REQUEST_MAX]) -> core::result::Result<(Request<'a>, Call), Reject> {
    let words = request.data;
    wire::header(request, cap, MAJOR)?;
    match words[0] & 0xFF {
        1 => {
            wire::body(request, cap, [0x1ffffffff0000, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::Ping { x: wire::field(&words, 0, 16, 32) as u32, flag: wire::field(&words, 0, 48, 1) != 0 }, Call::words(request, cap)))
        }
        2 => {
            let (call, length) = wire::take_buffer(request, cap, 4, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let dir = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let name = <Text<64> as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Find { dir, name }, call))
        }
        3 => {
            let (call, length) = wire::take_buffer(request, cap, 706, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let start = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::List { start }, call))
        }
        4 => {
            let (call, length) = wire::take_buffer(request, cap, 0, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let items = <List<u16, 8> as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let note = codec::decode_bytes::<10>(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Put { items, note }, call))
        }
        5 => {
            let (call, length) = wire::take_buffer(request, cap, 45, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let of = <Kind as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Info { of }, call))
        }
        6 => {
            wire::body(request, cap, [0xff0000, 0x0], CAP_KIND_NONE, false)?;
            let Some(k) = Kind::from_code(wire::field(&words, 0, 16, 8)) else { wire::discard(request, cap); return Err(Reject::Invalid) };
            Ok((Request::Mode { k }, Call::words(request, cap)))
        }
        7 => {
            let (call, length) = wire::take_buffer(request, cap, 66, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let length = <u16 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Fetch { length }, call))
        }
        8 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::Open { id: wire::field(&words, 0, 16, 32) as u32 }, Call::words(request, cap)))
        }
        9 => {
            wire::body(request, cap, [0x1ff0000, 0x0], CAP_KIND_NONE, false)?;
            let Some(k) = Kind::from_code(wire::field(&words, 0, 16, 8)) else { wire::discard(request, cap); return Err(Reject::Invalid) };
            Ok((Request::Sys { k, fail: wire::field(&words, 0, 24, 1) != 0 }, Call::words(request, cap)))
        }
        _ => { wire::discard(request, cap); Err(Reject::Invalid) }
    }
}

pub fn reply_ping(call: Call, value: u32) -> Result<()> {
    wire::finish(call, [((value) as usize) << 16, 0])
}
pub fn reply_find(call: Call, value: core::result::Result<u32, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| value.encode(w))
}
pub fn reply_list(call: Call, value: &[Entry]) -> Result<()> {
    wire::reply_buffer(call, |w| codec::encode_slice::<Entry, 16>(value, w))
}
pub fn reply_put(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |_| Some(()))
}
pub fn reply_info(call: Call, value: &Pair) -> Result<()> {
    wire::reply_buffer(call, |w| value.encode(w))
}
pub fn reply_mode(call: Call, value: Option<Kind>) -> Result<()> {
    let Some(value) = value else { return wire::reply_none(call) };
    wire::finish(call, [((value) as usize) << 16, 0])
}
pub fn reply_fetch(call: Call, value: core::result::Result<&[u8], Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| codec::encode_bytes::<64>(value, w))
}
/// `value` is the handle of the capability to send (copied).
pub fn reply_open(call: Call, value: core::result::Result<usize, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish_cap(call, value, false)
}
pub fn reply_sys(call: Call, value: Result<Kind>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_error(call, error) };
    wire::finish(call, [((value) as usize) << 16, 0])
}