// Generated by scripts/mind_idl.py from tests/idl/sample.wit; do not edit.
//! Test interface for the MIND IDL generator (tests/idl_host.rs): every v0.2 type.
#![allow(clippy::all, unused_imports, unused_variables, unused_mut, dead_code)]
use crate::abi::*;
use crate::ipc::{self, Received};
use crate::sys::{Error as SysError, Result};
use super::wire::{self, Reject};

pub const PACKAGE: &str = "mind:sample";
pub const VERSION: (u8, u8, u8) = (2, 1, 0);
const MAJOR: usize = 2;

/// Why a call failed.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum Error { NotFound = 0, Exists = 1, TooBig = 2 }
impl Error {
    pub fn from_u8(value: u8) -> Option<Self> { match value { 0 => Some(Self::NotFound), 1 => Some(Self::Exists), 2 => Some(Self::TooBig), _ => None } }
}
impl<'a> wire::Item<'a> for Error {
    fn encode(&self, w: &mut wire::Writer) -> Result<()> { w.u8(*self as u8) }
    fn decode(r: &mut wire::Reader<'a>) -> Option<Self> { Self::from_u8(r.u8()?) }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum Kind { File = 0, Directory = 1, Device = 2 }
impl Kind {
    pub fn from_u8(value: u8) -> Option<Self> { match value { 0 => Some(Self::File), 1 => Some(Self::Directory), 2 => Some(Self::Device), _ => None } }
}
impl<'a> wire::Item<'a> for Kind {
    fn encode(&self, w: &mut wire::Writer) -> Result<()> { w.u8(*self as u8) }
    fn decode(r: &mut wire::Reader<'a>) -> Option<Self> { Self::from_u8(r.u8()?) }
}

/// A directory entry.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Entry<'a> { pub name: &'a str, pub size: u64, pub hidden: bool, pub kind: Kind }
impl<'a> wire::Item<'a> for Entry<'a> {
    fn encode(&self, w: &mut wire::Writer) -> Result<()> {
        w.str(self.name, 32)?;
        w.u64(self.size)?;
        w.bool(self.hidden)?;
        w.u8(self.kind as u8)?;
        Ok(())
    }
    fn decode(r: &mut wire::Reader<'a>) -> Option<Self> { Some(Self { name: r.str(32)?, size: r.u64()?, hidden: r.bool()?, kind: Kind::from_u8(r.u8()?)? }) }
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Pair<'a> { pub tag: u8, pub entry: Entry<'a> }
impl<'a> wire::Item<'a> for Pair<'a> {
    fn encode(&self, w: &mut wire::Writer) -> Result<()> {
        w.u8(self.tag)?;
        wire::Item::encode(&self.entry, w)?;
        Ok(())
    }
    fn decode(r: &mut wire::Reader<'a>) -> Option<Self> { Some(Self { tag: r.u8()?, entry: <Entry<'a> as wire::Item>::decode(r)? }) }
}

/// Scalars only, as in v0.
pub fn ping(endpoint: ipc::Endpoint, x: u32, flag: bool) -> Result<u32> {
    let words = [1 | MAJOR << 8 | ((x) as usize) << 16 | ((flag) as usize) << 48, 0];
    let reply = wire::call(endpoint, words, None)?;
    let status = wire::check_reply(&reply, [0xffffffff0000, 0x0], false, false)?;
    Ok(wire::field(&reply, 0, 16, 32) as u32)
}

/// A string argument and a fallible scalar result.
pub fn find<'b>(endpoint: ipc::Endpoint, dir: u32, buffer: wire::Buffer<'b>, name: &'_ str) -> Result<core::result::Result<u32, Error>> {
    let wire::Buffer { cap, bytes } = buffer;
    let mut writer = wire::Writer::new(bytes);
    {
        let w = &mut writer;
        w.str(name, 64)?;
    }
    let payload = writer.len();
    let bytes = writer.into_inner();
    let words = [2 | MAJOR << 8 | ((payload) as usize) << 16, ((dir) as usize) << 0];
    let reply = wire::call(endpoint, words, Some((cap, false)))?;
    let status = wire::check_reply(&reply, [0xffffffff0000, 0x0], false, true)?;
    if let wire::Status::Failed(code) = status { return Error::from_u8(code).map(Err).ok_or(SysError::Invalid); }
    Ok(Ok(wire::field(&reply, 0, 16, 32) as u32))
}

/// A list of records as the result.
pub fn list<'b>(endpoint: ipc::Endpoint, buffer: wire::Buffer<'b>, start: u32) -> Result<wire::List<'b, Entry<'b>>> {
    let wire::Buffer { cap, bytes } = buffer;
    let mut writer = wire::Writer::new(bytes);
    let payload = writer.len();
    let bytes = writer.into_inner();
    let words = [3 | MAJOR << 8 | ((start) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, Some((cap, false)))?;
    let status = wire::check_reply(&reply, [0xffffffff0000, 0x0], false, false)?;
    let len = wire::field(&reply, 0, 16, 32);
    if len > bytes.len() { return Err(SysError::Invalid); }
    let bytes: &'b [u8] = bytes;
    let mut reader = wire::Reader::new(&bytes[..len]);
    let value = (|r: &mut wire::Reader<'b>| -> Option<_> { let value = wire::List::read(r, 16)?; r.end().then_some(value) })(&mut reader).ok_or(SysError::Invalid)?;
    Ok(value)
}

/// Two bulk arguments and a result without a value.
pub fn put<'b>(endpoint: ipc::Endpoint, buffer: wire::Buffer<'b>, items: &'_ [u16], note: &'_ [u8]) -> Result<core::result::Result<(), Error>> {
    let wire::Buffer { cap, bytes } = buffer;
    let mut writer = wire::Writer::new(bytes);
    {
        let w = &mut writer;
        w.list(items, 8)?;
        w.bytes(note, 10)?;
    }
    let payload = writer.len();
    let bytes = writer.into_inner();
    let words = [4 | MAJOR << 8 | ((payload) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, Some((cap, false)))?;
    let status = wire::check_reply(&reply, [0x0, 0x0], false, true)?;
    if let wire::Status::Failed(code) = status { return Error::from_u8(code).map(Err).ok_or(SysError::Invalid); }
    Ok(Ok(()))
}

/// A nested record result.
pub fn info<'b>(endpoint: ipc::Endpoint, buffer: wire::Buffer<'b>, of: Kind) -> Result<Pair<'b>> {
    let wire::Buffer { cap, bytes } = buffer;
    let mut writer = wire::Writer::new(bytes);
    let payload = writer.len();
    let bytes = writer.into_inner();
    let words = [5 | MAJOR << 8 | (((of as u8)) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, Some((cap, false)))?;
    let status = wire::check_reply(&reply, [0xffffffff0000, 0x0], false, false)?;
    let len = wire::field(&reply, 0, 16, 32);
    if len > bytes.len() { return Err(SysError::Invalid); }
    let bytes: &'b [u8] = bytes;
    let mut reader = wire::Reader::new(&bytes[..len]);
    let value = (|r: &mut wire::Reader<'b>| -> Option<_> { let value = <Pair<'b> as wire::Item>::decode(r)?; r.end().then_some(value) })(&mut reader).ok_or(SysError::Invalid)?;
    Ok(value)
}

/// An enum argument and an optional result.
pub fn mode(endpoint: ipc::Endpoint, k: Kind) -> Result<Option<u8>> {
    let words = [6 | MAJOR << 8 | (((k as u8)) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, None)?;
    let status = wire::check_reply(&reply, [0xff0000, 0x0], true, false)?;
    Ok(if status == wire::Status::None { None } else { Some(wire::field(&reply, 0, 16, 8) as u8) })
}

/// A request to the `sample` interface that passed the receiver's schema check.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Request {
    Ping { x: u32, flag: bool },
    Find { payload: u32, dir: u32, buffer: usize },
    List { buffer: usize, start: u32 },
    Put { payload: u32, buffer: usize },
    Info { buffer: usize, of: Kind },
    Mode { k: Kind },
}

/// Checks a received message against the schema (MC-2.4): method, major version, unused bits, enum values, capability
/// kind. `cap` is the slot passed to `recv`; an unexpected capability is dropped (MC-2.12). Bulk arguments are checked
/// by `args_<function>` once the server has mapped the buffer.
pub fn decode(request: &Received, cap: usize) -> core::result::Result<Request, Reject> {
    let words = request.data;
    wire::header(request, cap, MAJOR)?;
    match words[0] & 0xFF {
        1 => {
            wire::body(request, cap, [0x1ffffffff0000, 0x0], CAP_KIND_NONE, false)?;
            Ok(Request::Ping { x: wire::field(&words, 0, 16, 32) as u32, flag: wire::field(&words, 0, 48, 1) != 0 })
        }
        2 => {
            wire::body(request, cap, [0xffffffff0000, 0xffffffff], CAP_KIND_MEMORY, true)?;
            Ok(Request::Find { payload: wire::field(&words, 0, 16, 32) as u32, dir: wire::field(&words, 1, 0, 32) as u32, buffer: cap })
        }
        3 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_MEMORY, true)?;
            Ok(Request::List { buffer: cap, start: wire::field(&words, 0, 16, 32) as u32 })
        }
        4 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_MEMORY, true)?;
            Ok(Request::Put { payload: wire::field(&words, 0, 16, 32) as u32, buffer: cap })
        }
        5 => {
            wire::body(request, cap, [0xff0000, 0x0], CAP_KIND_MEMORY, true)?;
            Ok(Request::Info { buffer: cap, of: match Kind::from_u8(wire::field(&words, 0, 16, 8) as u8) { Some(v) => v, None => { wire::discard(request, cap); return Err(Reject::Invalid); } } })
        }
        6 => {
            wire::body(request, cap, [0xff0000, 0x0], CAP_KIND_NONE, false)?;
            Ok(Request::Mode { k: match Kind::from_u8(wire::field(&words, 0, 16, 8) as u8) { Some(v) => v, None => { wire::discard(request, cap); return Err(Reject::Invalid); } } })
        }
        _ => { wire::discard(request, cap); Err(Reject::Invalid) }
    }
}

/// Bulk arguments of `find` from the mapped buffer: exactly `payload` bytes, every limit checked.
pub fn args_find<'a>(bytes: &'a [u8], payload: u32) -> core::result::Result<&'a str, Reject> {
    let len = payload as usize;
    if len > bytes.len() { return Err(Reject::Invalid); }
    let mut reader = wire::Reader::new(&bytes[..len]);
    let value = (|r: &mut wire::Reader<'a>| -> Option<_> { let value = r.str(64)?; r.end().then_some(value) })(&mut reader);
    value.ok_or(Reject::Invalid)
}

/// Bulk arguments of `put` from the mapped buffer: exactly `payload` bytes, every limit checked.
pub fn args_put<'a>(bytes: &'a [u8], payload: u32) -> core::result::Result<(wire::List<'a, u16>, &'a [u8]), Reject> {
    let len = payload as usize;
    if len > bytes.len() { return Err(Reject::Invalid); }
    let mut reader = wire::Reader::new(&bytes[..len]);
    let value = (|r: &mut wire::Reader<'a>| -> Option<_> { let value = (wire::List::read(r, 8)?, r.bytes(10)?); r.end().then_some(value) })(&mut reader);
    value.ok_or(Reject::Invalid)
}

pub fn reply_ping(value: u32) -> Result<()> {
    wire::reply([((value) as usize) << 16, 0])
}
pub fn reply_find(value: core::result::Result<u32, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(code) => return wire::reply([wire::STATUS_FAILED | (code as usize) << 16, 0]) };
    wire::reply([((value) as usize) << 16, 0])
}
pub fn reply_list(bytes: &mut [u8], value: &'_ [Entry<'_>]) -> Result<()> {
    let mut writer = wire::Writer::new(bytes);
    let encoded = (|w: &mut wire::Writer| -> Result<()> { w.list(value, 16)?; Ok(()) })(&mut writer);
    if encoded.is_err() { return wire::reply([wire::STATUS_OVERFLOW, 0]); }
    wire::reply([(writer.len() as usize) << 16, 0])
}
pub fn reply_put(value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(code) => return wire::reply([wire::STATUS_FAILED | (code as usize) << 16, 0]) };
    wire::reply([0, 0])
}
pub fn reply_info(bytes: &mut [u8], value: Pair<'_>) -> Result<()> {
    let mut writer = wire::Writer::new(bytes);
    let encoded = (|w: &mut wire::Writer| -> Result<()> { wire::Item::encode(&value, w)?; Ok(()) })(&mut writer);
    if encoded.is_err() { return wire::reply([wire::STATUS_OVERFLOW, 0]); }
    wire::reply([(writer.len() as usize) << 16, 0])
}
pub fn reply_mode(value: Option<u8>) -> Result<()> {
    let Some(value) = value else { return wire::reply([wire::STATUS_NONE, 0]) };
    wire::reply([((value) as usize) << 16, 0])
}
