// Generated by scripts/mind_idl.py from idl/gpio.wit; do not edit.
//! The pins of ARM boards (issue 207): the `gpio` service drives the pin controllers the firmware's tables name
//! (BCM2711, PL061) and serves this interface. Reading is open to every client; changing a pin needs the control badge
//! (`mind::gpio::BADGE_CONTROL`), and a pin the board's hwdocs file reserves needs the platform badge. Functions are
//! numbered input 0, output 1, then the alternates ALT0, ALT1, ... from 2. Every change is logged.
#![allow(clippy::all, unused_imports, unused_mut, unused_variables)]
use crate::abi::*;
use crate::ipc::{Endpoint, Received};
use crate::mem::Pages;
use crate::sys::{Error as SysError, Result};
use super::codec::{self, List, Reader, Text, Wire, Writer};
use super::wire::{self, Call, Reject};

pub const PACKAGE: &str = "mind:gpio";
pub const VERSION: (u8, u8, u8) = (1, 0, 0);
const MAJOR: usize = 1;

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[repr(u8)]
pub enum Kind { #[default] Bcm2711 = 0, Pl061 = 1 }
impl Kind {
    /// The case with wire code `code`; None for a code the interface does not define.
    pub fn from_code(code: usize) -> Option<Self> { match code { 0 => Some(Self::Bcm2711), 1 => Some(Self::Pl061), _ => None } }
}
impl Wire for Kind {
    const MAX: usize = 1;
    fn encode(&self, w: &mut Writer) -> Option<()> { (*self as u8).encode(w) }
    fn decode(r: &mut Reader) -> Option<Self> { Self::from_code(u8::decode(r)? as usize) }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[repr(u8)]
pub enum Pull { #[default] None = 0, Up = 1, Down = 2, Unknown = 3 }
impl Pull {
    /// The case with wire code `code`; None for a code the interface does not define.
    pub fn from_code(code: usize) -> Option<Self> { match code { 0 => Some(Self::None), 1 => Some(Self::Up), 2 => Some(Self::Down), 3 => Some(Self::Unknown), _ => None } }
}
impl Wire for Pull {
    const MAX: usize = 1;
    fn encode(&self, w: &mut Writer) -> Option<()> { (*self as u8).encode(w) }
    fn decode(r: &mut Reader) -> Option<Self> { Self::from_code(u8::decode(r)? as usize) }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[repr(u8)]
pub enum Error { #[default] NoController = 0, NoPin = 1, Reserved = 2, Denied = 3, Unsupported = 4 }
impl Error {
    /// The case with wire code `code`; None for a code the interface does not define.
    pub fn from_code(code: usize) -> Option<Self> { match code { 0 => Some(Self::NoController), 1 => Some(Self::NoPin), 2 => Some(Self::Reserved), 3 => Some(Self::Denied), 4 => Some(Self::Unsupported), _ => None } }
}
impl Wire for Error {
    const MAX: usize = 1;
    fn encode(&self, w: &mut Writer) -> Option<()> { (*self as u8).encode(w) }
    fn decode(r: &mut Reader) -> Option<Self> { Self::from_code(u8::decode(r)? as usize) }
}

/// A controller: its kind, its pins, and the hwdocs tables found for it (empty names: none).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Controller { pub kind: Kind, pub pins: u8, pub soc: Text<24>, pub board: Text<24> }
impl Wire for Controller {
    const MAX: usize = <Kind as Wire>::MAX + <u8 as Wire>::MAX + <Text<24> as Wire>::MAX + <Text<24> as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.kind.encode(w)?; self.pins.encode(w)?; self.soc.encode(w)?; self.board.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { kind: Wire::decode(r)?, pins: Wire::decode(r)?, soc: Wire::decode(r)?, board: Wire::decode(r)? }) }
}

/// A pin's state: its active function of `functions`, its level, its pull, whether the board reserves it, and its
/// position on the board's header (0: not on it).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Pin { pub pin: u8, pub function: u8, pub functions: u8, pub level: bool, pub pull: Pull, pub reserved: bool, pub position: u8 }
impl Wire for Pin {
    const MAX: usize = <u8 as Wire>::MAX + <u8 as Wire>::MAX + <u8 as Wire>::MAX + <bool as Wire>::MAX + <Pull as Wire>::MAX + <bool as Wire>::MAX + <u8 as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.pin.encode(w)?; self.function.encode(w)?; self.functions.encode(w)?; self.level.encode(w)?; self.pull.encode(w)?; self.reserved.encode(w)?; self.position.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { pin: Wire::decode(r)?, function: Wire::decode(r)?, functions: Wire::decode(r)?, level: Wire::decode(r)?, pull: Wire::decode(r)?, reserved: Wire::decode(r)?, position: Wire::decode(r)? }) }
}

/// The controllers, in the order the other calls number them.
pub fn controllers(endpoint: Endpoint) -> Result<List<Controller, 4>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 1 | MAJOR << 8, &buffer, length)?;
    let length = wire::buffer_reply(&reply, 218, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <List<Controller, 4> as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? })
}

/// The state of every pin of a controller.
pub fn pins(endpoint: Endpoint, controller: u8) -> Result<core::result::Result<List<Pin, 64>, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        controller.encode(&mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 2 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 450, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <List<Pin, 64> as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// The names of a pin's functions in function order (from hwdocs; an empty name: none, or no table).
pub fn functions(endpoint: Endpoint, controller: u8, pin: u8) -> Result<core::result::Result<List<Text<24>, 8>, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        controller.encode(&mut w).ok_or(SysError::Invalid)?;
        pin.encode(&mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 3 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 210, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <List<Text<24>, 8> as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// Selects a pin's function (input, output, an alternate).
pub fn set_function(endpoint: Endpoint, controller: u8, pin: u8, function: u8) -> Result<core::result::Result<(), Error>> {
    let words = [4 | MAJOR << 8 | ((controller) as usize) << 16 | ((pin) as usize) << 24 | ((function) as usize) << 32, 0];
    let reply = wire::call(endpoint, words, None)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    wire::check_reply(&reply, [0, 0], false)?;
    Ok(Ok(()))
}

/// Drives an output pin high or low.
pub fn write(endpoint: Endpoint, controller: u8, pin: u8, high: bool) -> Result<core::result::Result<(), Error>> {
    let words = [5 | MAJOR << 8 | ((controller) as usize) << 16 | ((pin) as usize) << 24 | ((high) as usize) << 32, 0];
    let reply = wire::call(endpoint, words, None)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    wire::check_reply(&reply, [0, 0], false)?;
    Ok(Ok(()))
}

/// Selects a pin's pull (unsupported where the controller has none).
pub fn set_pull(endpoint: Endpoint, controller: u8, pin: u8, pull: Pull) -> Result<core::result::Result<(), Error>> {
    let words = [6 | MAJOR << 8 | ((controller) as usize) << 16 | ((pin) as usize) << 24 | ((pull) as usize) << 32, 0];
    let reply = wire::call(endpoint, words, None)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    wire::check_reply(&reply, [0, 0], false)?;
    Ok(Ok(()))
}

/// A request to the `gpio` interface that passed the receiver's schema check.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Request {
    Controllers,
    Pins { controller: u8 },
    Functions { controller: u8, pin: u8 },
    SetFunction { controller: u8, pin: u8, function: u8 },
    Write { controller: u8, pin: u8, high: bool },
    SetPull { controller: u8, pin: u8, pull: Pull },
}

/// Checks a received message against the schema (MC-2.4): method, major version, unused bits, capability kind, and
/// for buffer calls every length and value of a private copy of the request (MC-2.11). `cap` is the slot passed to
/// `recv`; an unexpected capability is dropped (MC-2.12). The `Call` is what the reply functions need.
pub fn decode(request: &Received, cap: usize) -> core::result::Result<(Request, Call), Reject> {
    let words = request.data;
    wire::header(request, cap, MAJOR)?;
    match words[0] & 0xFF {
        1 => {
            let mut copy = [0u8; 1];
            let (call, length) = wire::take_buffer(request, cap, 218, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Controllers, call))
        }
        2 => {
            let mut copy = [0u8; 1];
            let (call, length) = wire::take_buffer(request, cap, 450, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            let controller = <u8 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Pins { controller }, call))
        }
        3 => {
            let mut copy = [0u8; 2];
            let (call, length) = wire::take_buffer(request, cap, 210, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            let controller = <u8 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let pin = <u8 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Functions { controller, pin }, call))
        }
        4 => {
            wire::body(request, cap, [0xffffff0000, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::SetFunction { controller: wire::field(&words, 0, 16, 8) as u8, pin: wire::field(&words, 0, 24, 8) as u8, function: wire::field(&words, 0, 32, 8) as u8 }, Call::words(request, cap)))
        }
        5 => {
            wire::body(request, cap, [0x1ffff0000, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::Write { controller: wire::field(&words, 0, 16, 8) as u8, pin: wire::field(&words, 0, 24, 8) as u8, high: wire::field(&words, 0, 32, 1) != 0 }, Call::words(request, cap)))
        }
        6 => {
            wire::body(request, cap, [0xffffff0000, 0x0], CAP_KIND_NONE, false)?;
            let Some(pull) = Pull::from_code(wire::field(&words, 0, 32, 8)) else { wire::discard(request, cap); return Err(Reject::Invalid) };
            Ok((Request::SetPull { controller: wire::field(&words, 0, 16, 8) as u8, pin: wire::field(&words, 0, 24, 8) as u8, pull }, Call::words(request, cap)))
        }
        _ => { wire::discard(request, cap); Err(Reject::Invalid) }
    }
}

pub fn reply_controllers(call: Call, value: &[Controller]) -> Result<()> {
    wire::reply_buffer(call, |w| codec::encode_slice::<Controller, 4>(value, w))
}
pub fn reply_pins(call: Call, value: core::result::Result<&[Pin], Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| codec::encode_slice::<Pin, 64>(value, w))
}
pub fn reply_functions(call: Call, value: core::result::Result<&[Text<24>], Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| codec::encode_slice::<Text<24>, 8>(value, w))
}
pub fn reply_set_function(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [0, 0])
}
pub fn reply_write(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [0, 0])
}
pub fn reply_set_pull(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [0, 0])
}