// Generated by scripts/mind_idl.py from idl/init.wit; do not edit.
//! init: starts boot services by name (the operator's RUN <service> &) and, since 1.1, serves their lifecycle: which
//! services run, stopping and restarting them, stopping an application (roadmap C6). The shell holds a client in
//! SLOT_INIT and lends it in SLOT_LIFECYCLE to programs that ask for lifecycle control (`svc`, `top`). init itself and
//! the shell cannot be stopped.
#![allow(clippy::all, unused_imports, unused_mut, unused_variables)]
use crate::abi::*;
use crate::ipc::{Endpoint, Received};
use crate::mem::Pages;
use crate::sys::{Error as SysError, Result};
use super::codec::{self, List, Reader, Text, Wire, Writer};
use super::wire::{self, Call, Reject};

pub const PACKAGE: &str = "mind:init";
pub const VERSION: (u8, u8, u8) = (1, 2, 0);
const MAJOR: usize = 1;

/// Why a lifecycle request failed: no such service or task, it already runs or does not, it may not be stopped, its
/// device is missing, or the start failed.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[repr(u8)]
pub enum Error { #[default] NotFound = 0, Running = 1, Stopped = 2, Denied = 3, NoDevice = 4, Failed = 5 }
impl Error {
    /// The case with wire code `code`; None for a code the interface does not define.
    pub fn from_code(code: usize) -> Option<Self> { match code { 0 => Some(Self::NotFound), 1 => Some(Self::Running), 2 => Some(Self::Stopped), 3 => Some(Self::Denied), 4 => Some(Self::NoDevice), 5 => Some(Self::Failed), _ => None } }
}
impl Wire for Error {
    const MAX: usize = 1;
    fn encode(&self, w: &mut Writer) -> Option<()> { (*self as u8).encode(w) }
    fn decode(r: &mut Reader) -> Option<Self> { Self::from_code(u8::decode(r)? as usize) }
}

/// A boot service: its PID (0 if it does not run), how often init started it, whether it runs or is quarantined
/// (it failed too often; `run` lifts that), what it holds.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Service { pub name: Text<16>, pub pid: u64, pub starts: u32, pub running: bool, pub quarantined: bool, pub holds: Text<48> }
impl Wire for Service {
    const MAX: usize = <Text<16> as Wire>::MAX + <u64 as Wire>::MAX + <u32 as Wire>::MAX + <bool as Wire>::MAX + <bool as Wire>::MAX + <Text<48> as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.name.encode(w)?; self.pid.encode(w)?; self.starts.encode(w)?; self.running.encode(w)?; self.quarantined.encode(w)?; self.holds.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { name: Wire::decode(r)?, pid: Wire::decode(r)?, starts: Wire::decode(r)?, running: Wire::decode(r)?, quarantined: Wire::decode(r)?, holds: Wire::decode(r)? }) }
}

/// Starts boot service `name`, lifting a quarantine and resetting its restart budget; returns its PID. Errors: busy
/// (already running), not-found (no such service or no device), rights (cannot be started after boot).
pub fn run(endpoint: Endpoint, name: &str) -> Result<u64> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        codec::encode_str::<16>(name, &mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 1 | MAJOR << 8, &buffer, length)?;
    let length = wire::buffer_reply(&reply, 8, false, true)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <u64 as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? })
}

/// The boot services and their further instances in boot order (1.1; up to 32 since issue 205, 64 since 1.2: a
/// third VirtIO disk made 33, 251-KRN-0031).
pub fn list(endpoint: Endpoint) -> Result<core::result::Result<List<Service, 64>, Error>> {
    let mut buffer = Pages::new(8192).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 2 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 5250, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <List<Service, 64> as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// Stops a running service; init does not restart it until it is started again, and its clients' calls fail with
/// ERR_PEER meanwhile (1.1).
pub fn stop(endpoint: Endpoint, name: &str) -> Result<core::result::Result<(), Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        codec::encode_str::<16>(name, &mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 3 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 0, false, false)?;
    if length != Some(0) { return Err(SysError::Invalid); }
    Ok(Ok(()))
}

/// Stops and starts a service; clients granted earlier reach the new instance. Returns its PID (1.1).
pub fn restart(endpoint: Endpoint, name: &str) -> Result<core::result::Result<u64, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        codec::encode_str::<16>(name, &mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 4 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 8, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <u64 as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// Stops an application (a task that is not a boot service) (1.1).
pub fn stop_task(endpoint: Endpoint, pid: u64) -> Result<core::result::Result<(), Error>> {
    let words = [5 | MAJOR << 8, ((pid) as usize) << 0];
    let reply = wire::call(endpoint, words, None)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    wire::check_reply(&reply, [0, 0], false)?;
    Ok(Ok(()))
}

/// A request to the `init` interface that passed the receiver's schema check.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Request {
    Run { name: Text<16> },
    List,
    Stop { name: Text<16> },
    Restart { name: Text<16> },
    StopTask { pid: u64 },
}

/// Checks a received message against the schema (MC-2.4): method, major version, unused bits, capability kind, and
/// for buffer calls every length and value of a private copy of the request (MC-2.11). `cap` is the slot passed to
/// `recv`; an unexpected capability is dropped (MC-2.12). The `Call` is what the reply functions need.
pub fn decode(request: &Received, cap: usize) -> core::result::Result<(Request, Call), Reject> {
    let words = request.data;
    wire::header(request, cap, MAJOR)?;
    match words[0] & 0xFF {
        1 => {
            let mut copy = [0u8; 18];
            let (call, length) = wire::take_buffer(request, cap, 8, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            let name = <Text<16> as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Run { name }, call))
        }
        2 => {
            let mut copy = [0u8; 1];
            let (call, length) = wire::take_buffer(request, cap, 5250, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::List, call))
        }
        3 => {
            let mut copy = [0u8; 18];
            let (call, length) = wire::take_buffer(request, cap, 0, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            let name = <Text<16> as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Stop { name }, call))
        }
        4 => {
            let mut copy = [0u8; 18];
            let (call, length) = wire::take_buffer(request, cap, 8, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            let name = <Text<16> as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Restart { name }, call))
        }
        5 => {
            wire::body(request, cap, [0x0, 0xffffffffffffffff], CAP_KIND_NONE, false)?;
            Ok((Request::StopTask { pid: wire::field(&words, 1, 0, 64) as u64 }, Call::words(request, cap)))
        }
        _ => { wire::discard(request, cap); Err(Reject::Invalid) }
    }
}

pub fn reply_run(call: Call, value: Result<u64>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_error(call, error) };
    wire::reply_buffer(call, |w| value.encode(w))
}
pub fn reply_list(call: Call, value: core::result::Result<&[Service], Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| codec::encode_slice::<Service, 64>(value, w))
}
pub fn reply_stop(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |_| Some(()))
}
pub fn reply_restart(call: Call, value: core::result::Result<u64, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| value.encode(w))
}
pub fn reply_stop_task(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [0, 0])
}