// Generated by scripts/mind_idl.py from idl/keyboard.wit; do not edit.
//! Keyboard layout and layout switch of the PS/2 driver `ps2_kbd` (issue 085). `init` gives `ps2_kbd` a service endpoint
//! and the shell a client of it in SLOT_KEYBOARD (kernel issue 151); the shell's `keymap` command uses it.
#![allow(clippy::all, unused_imports, unused_mut, unused_variables)]
use crate::abi::*;
use crate::ipc::{Endpoint, Received};
use crate::mem::Pages;
use crate::sys::{Error, Result};
use super::codec::{self, List, Reader, Text, Wire, Writer};
use super::wire::{self, Call, Reject};

pub const PACKAGE: &str = "mind:keyboard";
pub const VERSION: (u8, u8, u8) = (1, 0, 0);
const MAJOR: usize = 1;

/// The layouts: US (QWERTY) and Russian (ЙЦУКЕН).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[repr(u8)]
pub enum Layout { #[default] Us = 0, Ru = 1 }
impl Layout {
    /// The case with wire code `code`; None for a code the interface does not define.
    pub fn from_code(code: usize) -> Option<Self> { match code { 0 => Some(Self::Us), 1 => Some(Self::Ru), _ => None } }
}
impl Wire for Layout {
    const MAX: usize = 1;
    fn encode(&self, w: &mut Writer) -> Option<()> { (*self as u8).encode(w) }
    fn decode(r: &mut Reader) -> Option<Self> { Self::from_code(u8::decode(r)? as usize) }
}

/// What switches the layout: Ctrl+Shift or Alt+Shift (either; the default), only one of them, Caps Lock (then it
/// no longer locks capitals), or nothing.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[repr(u8)]
pub enum SwitchKey { #[default] CtrlOrAltShift = 0, CtrlShift = 1, AltShift = 2, CapsLock = 3, None = 4 }
impl SwitchKey {
    /// The case with wire code `code`; None for a code the interface does not define.
    pub fn from_code(code: usize) -> Option<Self> { match code { 0 => Some(Self::CtrlOrAltShift), 1 => Some(Self::CtrlShift), 2 => Some(Self::AltShift), 3 => Some(Self::CapsLock), 4 => Some(Self::None), _ => None } }
}
impl Wire for SwitchKey {
    const MAX: usize = 1;
    fn encode(&self, w: &mut Writer) -> Option<()> { (*self as u8).encode(w) }
    fn decode(r: &mut Reader) -> Option<Self> { Self::from_code(u8::decode(r)? as usize) }
}

#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct State { pub layout: Layout, pub switch_key: SwitchKey }
impl Wire for State {
    const MAX: usize = <Layout as Wire>::MAX + <SwitchKey as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.layout.encode(w)?; self.switch_key.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { layout: Wire::decode(r)?, switch_key: Wire::decode(r)? }) }
}

/// The current layout and switch.
pub fn state(endpoint: Endpoint) -> Result<State> {
    let mut buffer = Pages::new(4096).ok_or(Error::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 1 | MAJOR << 8, &buffer, length)?;
    let length = wire::buffer_reply(&reply, 2, false, false)?;
    let length = length.ok_or(Error::Invalid)?;
    Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <State as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(Error::Invalid)? })
}

/// Selects a layout for the next keys.
pub fn set_layout(endpoint: Endpoint, layout: Layout) -> Result<()> {
    let words = [2 | MAJOR << 8 | ((layout) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, None)?;
    wire::check_error(&reply)?;
    wire::check_reply(&reply, [0, 0], false).map(drop)
}

/// Selects the switch.
pub fn set_switch(endpoint: Endpoint, key: SwitchKey) -> Result<()> {
    let words = [3 | MAJOR << 8 | ((key) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, None)?;
    wire::check_error(&reply)?;
    wire::check_reply(&reply, [0, 0], false).map(drop)
}

/// The names of the layouts, in `layout` order.
pub fn layouts(endpoint: Endpoint) -> Result<List<Text<16>, 8>> {
    let mut buffer = Pages::new(4096).ok_or(Error::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 4 | MAJOR << 8, &buffer, length)?;
    let length = wire::buffer_reply(&reply, 146, false, false)?;
    let length = length.ok_or(Error::Invalid)?;
    Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <List<Text<16>, 8> as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(Error::Invalid)? })
}

/// A request to the `keyboard` interface that passed the receiver's schema check.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Request {
    State,
    SetLayout { layout: Layout },
    SetSwitch { key: SwitchKey },
    Layouts,
}

/// Checks a received message against the schema (MC-2.4): method, major version, unused bits, capability kind, and
/// for buffer calls every length and value of a private copy of the request (MC-2.11). `cap` is the slot passed to
/// `recv`; an unexpected capability is dropped (MC-2.12). The `Call` is what the reply functions need.
pub fn decode(request: &Received, cap: usize) -> core::result::Result<(Request, Call), Reject> {
    let words = request.data;
    wire::header(request, cap, MAJOR)?;
    match words[0] & 0xFF {
        1 => {
            let mut copy = [0u8; 1];
            let (call, length) = wire::take_buffer(request, cap, 2, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::State, call))
        }
        2 => {
            wire::body(request, cap, [0xff0000, 0x0], CAP_KIND_NONE, false)?;
            let Some(layout) = Layout::from_code(wire::field(&words, 0, 16, 8)) else { wire::discard(request, cap); return Err(Reject::Invalid) };
            Ok((Request::SetLayout { layout }, Call::words(request, cap)))
        }
        3 => {
            wire::body(request, cap, [0xff0000, 0x0], CAP_KIND_NONE, false)?;
            let Some(key) = SwitchKey::from_code(wire::field(&words, 0, 16, 8)) else { wire::discard(request, cap); return Err(Reject::Invalid) };
            Ok((Request::SetSwitch { key }, Call::words(request, cap)))
        }
        4 => {
            let mut copy = [0u8; 1];
            let (call, length) = wire::take_buffer(request, cap, 146, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Layouts, call))
        }
        _ => { wire::discard(request, cap); Err(Reject::Invalid) }
    }
}

pub fn reply_state(call: Call, value: &State) -> Result<()> {
    wire::reply_buffer(call, |w| value.encode(w))
}
pub fn reply_set_layout(call: Call, value: Result<()>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_error(call, error) };
    wire::finish(call, [0, 0])
}
pub fn reply_set_switch(call: Call, value: Result<()>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_error(call, error) };
    wire::finish(call, [0, 0])
}
pub fn reply_layouts(call: Call, value: &[Text<16>]) -> Result<()> {
    wire::reply_buffer(call, |w| codec::encode_slice::<Text<16>, 8>(value, w))
}