// Generated by scripts/mind_idl.py from idl/lifecycle.wit; do not edit.
//! Lifecycle of boot services and applications, served by `init` (the lifecycle owner, roadmap C6): which services
//! run, starting, stopping and restarting them, stopping an application. A client is init's endpoint; the shell
//! holds one and lends it to programs that ask for lifecycle control (`REQUEST_LIFECYCLE`: `svc`, `top`). `init`
//! itself and the shell cannot be stopped. Restart budgets, generations and failure notification come with C6.
#![allow(clippy::all, unused_imports, unused_variables, unused_mut, dead_code)]
use crate::abi::*;
use crate::ipc::{self, Received};
use crate::sys::{Error as SysError, Result};
use super::wire::{self, Reject};

pub const PACKAGE: &str = "mind:lifecycle";
pub const VERSION: (u8, u8, u8) = (1, 0, 0);
const MAJOR: usize = 1;

/// Why a request failed: no such service or task, it already runs (start) or does not (stop), it may not be
/// stopped, its device is missing, or the spawn failed.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum Error { NotFound = 0, Running = 1, Stopped = 2, Denied = 3, NoDevice = 4, Failed = 5 }
impl Error {
    pub fn from_u8(value: u8) -> Option<Self> { match value { 0 => Some(Self::NotFound), 1 => Some(Self::Running), 2 => Some(Self::Stopped), 3 => Some(Self::Denied), 4 => Some(Self::NoDevice), 5 => Some(Self::Failed), _ => None } }
}
impl<'a> wire::Item<'a> for Error {
    fn encode(&self, w: &mut wire::Writer) -> Result<()> { w.u8(*self as u8) }
    fn decode(r: &mut wire::Reader<'a>) -> Option<Self> { Self::from_u8(r.u8()?) }
}

/// A boot service: its PID (0 if it does not run), how often init started it, whether it runs, what it holds.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Service<'a> { pub name: &'a str, pub pid: u64, pub starts: u32, pub running: bool, pub holds: &'a str }
impl<'a> wire::Item<'a> for Service<'a> {
    fn encode(&self, w: &mut wire::Writer) -> Result<()> {
        w.str(self.name, 16)?;
        w.u64(self.pid)?;
        w.u32(self.starts)?;
        w.bool(self.running)?;
        w.str(self.holds, 48)?;
        Ok(())
    }
    fn decode(r: &mut wire::Reader<'a>) -> Option<Self> { Some(Self { name: r.str(16)?, pid: r.u64()?, starts: r.u32()?, running: r.bool()?, holds: r.str(48)? }) }
}

/// The boot services in boot order.
pub fn list<'b>(endpoint: ipc::Endpoint, buffer: wire::Buffer<'b>) -> Result<core::result::Result<wire::List<'b, Service<'b>>, Error>> {
    let wire::Buffer { cap, bytes } = buffer;
    let mut writer = wire::Writer::new(bytes);
    let payload = writer.len();
    let bytes = writer.into_inner();
    let words = [1 | MAJOR << 8, 0];
    let reply = wire::call(endpoint, words, Some((cap, false)))?;
    let status = wire::check_reply(&reply, [0xffffffff0000, 0x0], false, true)?;
    if let wire::Status::Failed(code) = status { return Error::from_u8(code).map(Err).ok_or(SysError::Invalid); }
    let len = wire::field(&reply, 0, 16, 32);
    if len > bytes.len() { return Err(SysError::Invalid); }
    let bytes: &'b [u8] = bytes;
    let mut reader = wire::Reader::new(&bytes[..len]);
    let value = (|r: &mut wire::Reader<'b>| -> Option<_> { let value = wire::List::read(r, 24)?; r.end().then_some(value) })(&mut reader).ok_or(SysError::Invalid)?;
    Ok(Ok(value))
}

/// Starts a service that does not run; returns its PID.
pub fn start<'b>(endpoint: ipc::Endpoint, buffer: wire::Buffer<'b>, name: &'_ str) -> Result<core::result::Result<u64, Error>> {
    let wire::Buffer { cap, bytes } = buffer;
    let mut writer = wire::Writer::new(bytes);
    {
        let w = &mut writer;
        w.str(name, 16)?;
    }
    let payload = writer.len();
    let bytes = writer.into_inner();
    let words = [2 | MAJOR << 8 | ((payload) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, Some((cap, false)))?;
    let status = wire::check_reply(&reply, [0x0, 0xffffffffffffffff], false, true)?;
    if let wire::Status::Failed(code) = status { return Error::from_u8(code).map(Err).ok_or(SysError::Invalid); }
    Ok(Ok(wire::field(&reply, 1, 0, 64) as u64))
}

/// Stops a running service; its clients' calls fail with ERR_PEER until it is started again.
pub fn stop<'b>(endpoint: ipc::Endpoint, buffer: wire::Buffer<'b>, name: &'_ str) -> Result<core::result::Result<(), Error>> {
    let wire::Buffer { cap, bytes } = buffer;
    let mut writer = wire::Writer::new(bytes);
    {
        let w = &mut writer;
        w.str(name, 16)?;
    }
    let payload = writer.len();
    let bytes = writer.into_inner();
    let words = [3 | MAJOR << 8 | ((payload) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, Some((cap, false)))?;
    let status = wire::check_reply(&reply, [0x0, 0x0], false, true)?;
    if let wire::Status::Failed(code) = status { return Error::from_u8(code).map(Err).ok_or(SysError::Invalid); }
    Ok(Ok(()))
}

/// Stops and starts a service; clients granted earlier reach the new instance. Returns its PID.
pub fn restart<'b>(endpoint: ipc::Endpoint, buffer: wire::Buffer<'b>, name: &'_ str) -> Result<core::result::Result<u64, Error>> {
    let wire::Buffer { cap, bytes } = buffer;
    let mut writer = wire::Writer::new(bytes);
    {
        let w = &mut writer;
        w.str(name, 16)?;
    }
    let payload = writer.len();
    let bytes = writer.into_inner();
    let words = [4 | MAJOR << 8 | ((payload) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, Some((cap, false)))?;
    let status = wire::check_reply(&reply, [0x0, 0xffffffffffffffff], false, true)?;
    if let wire::Status::Failed(code) = status { return Error::from_u8(code).map(Err).ok_or(SysError::Invalid); }
    Ok(Ok(wire::field(&reply, 1, 0, 64) as u64))
}

/// Stops an application (a task that is not a boot service).
pub fn stop_task(endpoint: ipc::Endpoint, pid: u64) -> Result<core::result::Result<(), Error>> {
    let words = [5 | MAJOR << 8, ((pid) as usize) << 0];
    let reply = wire::call(endpoint, words, None)?;
    let status = wire::check_reply(&reply, [0x0, 0x0], false, true)?;
    if let wire::Status::Failed(code) = status { return Error::from_u8(code).map(Err).ok_or(SysError::Invalid); }
    Ok(Ok(()))
}

/// A request to the `lifecycle` interface that passed the receiver's schema check.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Request {
    List { buffer: usize },
    Start { payload: u32, buffer: usize },
    Stop { payload: u32, buffer: usize },
    Restart { payload: u32, buffer: usize },
    StopTask { pid: u64 },
}

/// Checks a received message against the schema (MC-2.4): method, major version, unused bits, enum values, capability
/// kind. `cap` is the slot passed to `recv`; an unexpected capability is dropped (MC-2.12). Bulk arguments are checked
/// by `args_<function>` once the server has mapped the buffer.
pub fn decode(request: &Received, cap: usize) -> core::result::Result<Request, Reject> {
    let words = request.data;
    wire::header(request, cap, MAJOR)?;
    match words[0] & 0xFF {
        1 => {
            wire::body(request, cap, [0x0, 0x0], CAP_KIND_MEMORY, true)?;
            Ok(Request::List { buffer: cap })
        }
        2 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_MEMORY, true)?;
            Ok(Request::Start { payload: wire::field(&words, 0, 16, 32) as u32, buffer: cap })
        }
        3 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_MEMORY, true)?;
            Ok(Request::Stop { payload: wire::field(&words, 0, 16, 32) as u32, buffer: cap })
        }
        4 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_MEMORY, true)?;
            Ok(Request::Restart { payload: wire::field(&words, 0, 16, 32) as u32, buffer: cap })
        }
        5 => {
            wire::body(request, cap, [0x0, 0xffffffffffffffff], CAP_KIND_NONE, false)?;
            Ok(Request::StopTask { pid: wire::field(&words, 1, 0, 64) as u64 })
        }
        _ => { wire::discard(request, cap); Err(Reject::Invalid) }
    }
}

/// Bulk arguments of `start` from the mapped buffer: exactly `payload` bytes, every limit checked.
pub fn args_start<'a>(bytes: &'a [u8], payload: u32) -> core::result::Result<&'a str, Reject> {
    let len = payload as usize;
    if len > bytes.len() { return Err(Reject::Invalid); }
    let mut reader = wire::Reader::new(&bytes[..len]);
    let value = (|r: &mut wire::Reader<'a>| -> Option<_> { let value = r.str(16)?; r.end().then_some(value) })(&mut reader);
    value.ok_or(Reject::Invalid)
}

/// Bulk arguments of `stop` from the mapped buffer: exactly `payload` bytes, every limit checked.
pub fn args_stop<'a>(bytes: &'a [u8], payload: u32) -> core::result::Result<&'a str, Reject> {
    let len = payload as usize;
    if len > bytes.len() { return Err(Reject::Invalid); }
    let mut reader = wire::Reader::new(&bytes[..len]);
    let value = (|r: &mut wire::Reader<'a>| -> Option<_> { let value = r.str(16)?; r.end().then_some(value) })(&mut reader);
    value.ok_or(Reject::Invalid)
}

/// Bulk arguments of `restart` from the mapped buffer: exactly `payload` bytes, every limit checked.
pub fn args_restart<'a>(bytes: &'a [u8], payload: u32) -> core::result::Result<&'a str, Reject> {
    let len = payload as usize;
    if len > bytes.len() { return Err(Reject::Invalid); }
    let mut reader = wire::Reader::new(&bytes[..len]);
    let value = (|r: &mut wire::Reader<'a>| -> Option<_> { let value = r.str(16)?; r.end().then_some(value) })(&mut reader);
    value.ok_or(Reject::Invalid)
}

pub fn reply_list(bytes: &mut [u8], value: core::result::Result<&'_ [Service<'_>], Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(code) => return wire::reply([wire::STATUS_FAILED | (code as usize) << 16, 0]) };
    let mut writer = wire::Writer::new(bytes);
    let encoded = (|w: &mut wire::Writer| -> Result<()> { w.list(value, 24)?; Ok(()) })(&mut writer);
    if encoded.is_err() { return wire::reply([wire::STATUS_OVERFLOW, 0]); }
    wire::reply([(writer.len() as usize) << 16, 0])
}
pub fn reply_start(value: core::result::Result<u64, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(code) => return wire::reply([wire::STATUS_FAILED | (code as usize) << 16, 0]) };
    wire::reply([0, ((value) as usize) << 0])
}
pub fn reply_stop(value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(code) => return wire::reply([wire::STATUS_FAILED | (code as usize) << 16, 0]) };
    wire::reply([0, 0])
}
pub fn reply_restart(value: core::result::Result<u64, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(code) => return wire::reply([wire::STATUS_FAILED | (code as usize) << 16, 0]) };
    wire::reply([0, ((value) as usize) << 0])
}
pub fn reply_stop_task(value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(code) => return wire::reply([wire::STATUS_FAILED | (code as usize) << 16, 0]) };
    wire::reply([0, 0])
}
