// Generated by scripts/mind_idl.py from idl/loader.wit; do not edit.
//! Program loader: starts applications from the boot disk. A launch is a session: the caller names the program, lends
//! the capabilities it decides to give (MC-3.11: the program only requests them, see `inspect`), then commits.
#![allow(clippy::all, unused_imports, unused_variables, unused_mut, dead_code)]
use crate::abi::*;
use crate::ipc::{self, Received};
use crate::sys::{Error as SysError, Result};
use super::wire::{self, Reject};

pub const PACKAGE: &str = "mind:loader";
pub const VERSION: (u8, u8, u8) = (2, 0, 0);
const MAJOR: usize = 2;

/// Why a request failed.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum Error { NotFound = 0, Invalid = 1, NoMemory = 2, Limit = 3, Busy = 4, Rights = 5, Sessions = 6 }
impl Error {
    pub fn from_u8(value: u8) -> Option<Self> { match value { 0 => Some(Self::NotFound), 1 => Some(Self::Invalid), 2 => Some(Self::NoMemory), 3 => Some(Self::Limit), 4 => Some(Self::Busy), 5 => Some(Self::Rights), 6 => Some(Self::Sessions), _ => None } }
}
impl<'a> wire::Item<'a> for Error {
    fn encode(&self, w: &mut wire::Writer) -> Result<()> { w.u8(*self as u8) }
    fn decode(r: &mut wire::Reader<'a>) -> Option<Self> { Self::from_u8(r.u8()?) }
}

/// What a program asks its launcher for (`mind::request!`, read from its ELF). It grants nothing.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Needs { pub console: bool, pub sysinfo: bool, pub file: bool, pub lifecycle: bool, pub log: bool, pub files: bool }
impl<'a> wire::Item<'a> for Needs {
    fn encode(&self, w: &mut wire::Writer) -> Result<()> {
        w.bool(self.console)?;
        w.bool(self.sysinfo)?;
        w.bool(self.file)?;
        w.bool(self.lifecycle)?;
        w.bool(self.log)?;
        w.bool(self.files)?;
        Ok(())
    }
    fn decode(r: &mut wire::Reader<'a>) -> Option<Self> { Some(Self { console: r.bool()?, sysinfo: r.bool()?, file: r.bool()?, lifecycle: r.bool()?, log: r.bool()?, files: r.bool()? }) }
}

/// Starts a launch of `name` (a program on the boot disk) with `args`; returns the session.
pub fn begin<'b>(endpoint: ipc::Endpoint, buffer: wire::Buffer<'b>, name: &'_ str, args: &'_ str) -> Result<core::result::Result<u32, Error>> {
    let wire::Buffer { cap, bytes } = buffer;
    let mut writer = wire::Writer::new(bytes);
    {
        let w = &mut writer;
        w.str(name, 64)?;
        w.str(args, 1024)?;
    }
    let payload = writer.len();
    let bytes = writer.into_inner();
    let words = [1 | MAJOR << 8 | ((payload) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, Some((cap, false)))?;
    let status = wire::check_reply(&reply, [0xffffffff0000, 0x0], false, true)?;
    if let wire::Status::Failed(code) = status { return Error::from_u8(code).map(Err).ok_or(SysError::Invalid); }
    Ok(Ok(wire::field(&reply, 0, 16, 32) as u32))
}

/// Gives the new program a copy of `cap` in its slot `slot` (7..12; 12, the system log, since 1.1).
pub fn grant(endpoint: ipc::Endpoint, session: u32, slot: u8, cap: usize) -> Result<core::result::Result<(), Error>> {
    let words = [2 | MAJOR << 8 | ((session) as usize) << 16 | ((slot) as usize) << 48, 0];
    let reply = wire::call(endpoint, words, Some((cap, false)))?;
    let status = wire::check_reply(&reply, [0x0, 0x0], false, true)?;
    if let wire::Status::Failed(code) = status { return Error::from_u8(code).map(Err).ok_or(SysError::Invalid); }
    Ok(Ok(()))
}

/// Starts the program (with a screen unless it asked to be a console program); returns its PID.
pub fn commit(endpoint: ipc::Endpoint, session: u32) -> Result<core::result::Result<u64, Error>> {
    let words = [3 | MAJOR << 8 | ((session) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, None)?;
    let status = wire::check_reply(&reply, [0x0, 0xffffffffffffffff], false, true)?;
    if let wire::Status::Failed(code) = status { return Error::from_u8(code).map(Err).ok_or(SysError::Invalid); }
    Ok(Ok(wire::field(&reply, 1, 0, 64) as u64))
}

/// Drops a session and the capabilities granted to it.
pub fn abort(endpoint: ipc::Endpoint, session: u32) -> Result<core::result::Result<(), Error>> {
    let words = [4 | MAJOR << 8 | ((session) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, None)?;
    let status = wire::check_reply(&reply, [0x0, 0x0], false, true)?;
    if let wire::Status::Failed(code) = status { return Error::from_u8(code).map(Err).ok_or(SysError::Invalid); }
    Ok(Ok(()))
}

/// What the program `name` requests.
pub fn inspect<'b>(endpoint: ipc::Endpoint, buffer: wire::Buffer<'b>, name: &'_ str) -> Result<core::result::Result<Needs, Error>> {
    let wire::Buffer { cap, bytes } = buffer;
    let mut writer = wire::Writer::new(bytes);
    {
        let w = &mut writer;
        w.str(name, 64)?;
    }
    let payload = writer.len();
    let bytes = writer.into_inner();
    let words = [5 | MAJOR << 8 | ((payload) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, Some((cap, false)))?;
    let status = wire::check_reply(&reply, [0xffffffff0000, 0x0], false, true)?;
    if let wire::Status::Failed(code) = status { return Error::from_u8(code).map(Err).ok_or(SysError::Invalid); }
    let len = wire::field(&reply, 0, 16, 32);
    if len > bytes.len() { return Err(SysError::Invalid); }
    let bytes: &'b [u8] = bytes;
    let mut reader = wire::Reader::new(&bytes[..len]);
    let value = (|r: &mut wire::Reader<'b>| -> Option<_> { let value = <Needs as wire::Item>::decode(r)?; r.end().then_some(value) })(&mut reader).ok_or(SysError::Invalid)?;
    Ok(Ok(value))
}

/// A request to the `loader` interface that passed the receiver's schema check.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Request {
    Begin { payload: u32, buffer: usize },
    Grant { session: u32, slot: u8, cap: usize },
    Commit { session: u32 },
    Abort { session: u32 },
    Inspect { payload: u32, buffer: usize },
}

/// Checks a received message against the schema (MC-2.4): method, major version, unused bits, enum values, capability
/// kind. `cap` is the slot passed to `recv`; an unexpected capability is dropped (MC-2.12). Bulk arguments are checked
/// by `args_<function>` once the server has mapped the buffer.
pub fn decode(request: &Received, cap: usize) -> core::result::Result<Request, Reject> {
    let words = request.data;
    wire::header(request, cap, MAJOR)?;
    match words[0] & 0xFF {
        1 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_MEMORY, true)?;
            Ok(Request::Begin { payload: wire::field(&words, 0, 16, 32) as u32, buffer: cap })
        }
        2 => {
            wire::body(request, cap, [0xffffffffff0000, 0x0], CAP_KIND_ENDPOINT, true)?;
            Ok(Request::Grant { session: wire::field(&words, 0, 16, 32) as u32, slot: wire::field(&words, 0, 48, 8) as u8, cap: cap })
        }
        3 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_NONE, false)?;
            Ok(Request::Commit { session: wire::field(&words, 0, 16, 32) as u32 })
        }
        4 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_NONE, false)?;
            Ok(Request::Abort { session: wire::field(&words, 0, 16, 32) as u32 })
        }
        5 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_MEMORY, true)?;
            Ok(Request::Inspect { payload: wire::field(&words, 0, 16, 32) as u32, buffer: cap })
        }
        _ => { wire::discard(request, cap); Err(Reject::Invalid) }
    }
}

/// Bulk arguments of `begin` from the mapped buffer: exactly `payload` bytes, every limit checked.
pub fn args_begin<'a>(bytes: &'a [u8], payload: u32) -> core::result::Result<(&'a str, &'a str), Reject> {
    let len = payload as usize;
    if len > bytes.len() { return Err(Reject::Invalid); }
    let mut reader = wire::Reader::new(&bytes[..len]);
    let value = (|r: &mut wire::Reader<'a>| -> Option<_> { let value = (r.str(64)?, r.str(1024)?); r.end().then_some(value) })(&mut reader);
    value.ok_or(Reject::Invalid)
}

/// Bulk arguments of `inspect` from the mapped buffer: exactly `payload` bytes, every limit checked.
pub fn args_inspect<'a>(bytes: &'a [u8], payload: u32) -> core::result::Result<&'a str, Reject> {
    let len = payload as usize;
    if len > bytes.len() { return Err(Reject::Invalid); }
    let mut reader = wire::Reader::new(&bytes[..len]);
    let value = (|r: &mut wire::Reader<'a>| -> Option<_> { let value = r.str(64)?; r.end().then_some(value) })(&mut reader);
    value.ok_or(Reject::Invalid)
}

pub fn reply_begin(value: core::result::Result<u32, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(code) => return wire::reply([wire::STATUS_FAILED | (code as usize) << 16, 0]) };
    wire::reply([((value) as usize) << 16, 0])
}
pub fn reply_grant(value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(code) => return wire::reply([wire::STATUS_FAILED | (code as usize) << 16, 0]) };
    wire::reply([0, 0])
}
pub fn reply_commit(value: core::result::Result<u64, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(code) => return wire::reply([wire::STATUS_FAILED | (code as usize) << 16, 0]) };
    wire::reply([0, ((value) as usize) << 0])
}
pub fn reply_abort(value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(code) => return wire::reply([wire::STATUS_FAILED | (code as usize) << 16, 0]) };
    wire::reply([0, 0])
}
pub fn reply_inspect(bytes: &mut [u8], value: core::result::Result<Needs, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(code) => return wire::reply([wire::STATUS_FAILED | (code as usize) << 16, 0]) };
    let mut writer = wire::Writer::new(bytes);
    let encoded = (|w: &mut wire::Writer| -> Result<()> { wire::Item::encode(&value, w)?; Ok(()) })(&mut writer);
    if encoded.is_err() { return wire::reply([wire::STATUS_OVERFLOW, 0]); }
    wire::reply([(writer.len() as usize) << 16, 0])
}
