// Generated by scripts/mind_idl.py from idl/loader.wit; do not edit.
//! Program loader: lists and starts application programs from the boot disk. A launch with capabilities is a session
//! (1.1): the caller names the program, lends the capabilities it decides to give (MC-3.11: the program only requests
//! them, see `inspect`), then commits.
#![allow(clippy::all, unused_imports, unused_mut, unused_variables)]
use crate::abi::*;
use crate::ipc::{Endpoint, Received};
use crate::mem::Pages;
use crate::sys::{Error as SysError, Result};
use super::codec::{self, List, Reader, Text, Wire, Writer};
use super::wire::{self, Call, Reject};

pub const PACKAGE: &str = "mind:loader";
pub const VERSION: (u8, u8, u8) = (1, 7, 0);
const MAJOR: usize = 1;

/// Why a launch session failed; `unreadable` (1.7): the program's file could not be read, its drive does not answer.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[repr(u8)]
pub enum Error { #[default] NotFound = 0, Invalid = 1, NoMemory = 2, Limit = 3, Busy = 4, Rights = 5, Sessions = 6, Unreadable = 7 }
impl Error {
    /// The case with wire code `code`; None for a code the interface does not define.
    pub fn from_code(code: usize) -> Option<Self> { match code { 0 => Some(Self::NotFound), 1 => Some(Self::Invalid), 2 => Some(Self::NoMemory), 3 => Some(Self::Limit), 4 => Some(Self::Busy), 5 => Some(Self::Rights), 6 => Some(Self::Sessions), 7 => Some(Self::Unreadable), _ => None } }
}
impl Wire for Error {
    const MAX: usize = 1;
    fn encode(&self, w: &mut Writer) -> Option<()> { (*self as u8).encode(w) }
    fn decode(r: &mut Reader) -> Option<Self> { Self::from_code(u8::decode(r)? as usize) }
}

/// A program file in the root of the boot disk.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Program { pub name: Text<16>, pub size: u64, pub service: bool }
impl Wire for Program {
    const MAX: usize = <Text<16> as Wire>::MAX + <u64 as Wire>::MAX + <bool as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.name.encode(w)?; self.size.encode(w)?; self.service.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { name: Wire::decode(r)?, size: Wire::decode(r)?, service: Wire::decode(r)? }) }
}

/// What a program asks its launcher for (`mind::request!`, read from its ELF). It grants nothing.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Needs { pub console: bool, pub sysinfo: bool, pub file: bool, pub lifecycle: bool, pub log: bool, pub files: bool }
impl Wire for Needs {
    const MAX: usize = <bool as Wire>::MAX + <bool as Wire>::MAX + <bool as Wire>::MAX + <bool as Wire>::MAX + <bool as Wire>::MAX + <bool as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.console.encode(w)?; self.sysinfo.encode(w)?; self.file.encode(w)?; self.lifecycle.encode(w)?; self.log.encode(w)?; self.files.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { console: Wire::decode(r)?, sysinfo: Wire::decode(r)?, file: Wire::decode(r)?, lifecycle: Wire::decode(r)?, log: Wire::decode(r)?, files: Wire::decode(r)? }) }
}

/// The `*.elf` programs in the root of the boot disk (at most 128, 1.4: 64 before); services are marked.
pub fn list(endpoint: Endpoint) -> Result<List<Program, 128>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 1 | MAJOR << 8, &buffer, length)?;
    let length = wire::buffer_reply(&reply, 3458, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <List<Program, 128> as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? })
}

/// Starts program `name` (a name, or a path with `.` or `/`) with `args` in its info page; returns its PID.
pub fn run(endpoint: Endpoint, name: &str, args: &str) -> Result<u64> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        codec::encode_str::<64>(name, &mut w).ok_or(SysError::Invalid)?;
        codec::encode_str::<1024>(args, &mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 2 | MAJOR << 8, &buffer, length)?;
    let length = wire::buffer_reply(&reply, 8, false, true)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <u64 as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? })
}

/// Starts a launch of `name` (a program on the boot disk) with `args`; returns the session (1.1).
pub fn begin(endpoint: Endpoint, name: &str, args: &str) -> Result<core::result::Result<u32, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        codec::encode_str::<64>(name, &mut w).ok_or(SysError::Invalid)?;
        codec::encode_str::<1024>(args, &mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 3 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 4, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <u32 as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// Gives the new program a copy of `cap` in its fixed slot `slot` (SLOT_FILE, SLOT_INIT for a ping/pong pair,
/// SLOT_SYSINFO, SLOT_LIFECYCLE, SLOT_LOG) (1.1).
pub fn grant(endpoint: Endpoint, session: u32, slot: u8, cap: usize) -> Result<core::result::Result<(), Error>> {
    let words = [4 | MAJOR << 8 | ((session) as usize) << 16 | ((slot) as usize) << 48, 0];
    let reply = wire::call(endpoint, words, Some((cap, false)))?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    wire::check_reply(&reply, [0, 0], false)?;
    Ok(Ok(()))
}

/// Starts the program (with a screen unless it asked to be a console program); returns its PID (1.1).
pub fn commit(endpoint: Endpoint, session: u32) -> Result<core::result::Result<u64, Error>> {
    let words = [5 | MAJOR << 8 | ((session) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, None)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let _ = wire::check_reply(&reply, [0x0, 0xffffffffffffffff], false)?;
    Ok(Ok(wire::field(&reply, 1, 0, 64) as u64))
}

/// Drops a session and the capabilities granted to it (1.1).
pub fn abort(endpoint: Endpoint, session: u32) -> Result<core::result::Result<(), Error>> {
    let words = [6 | MAJOR << 8 | ((session) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, None)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    wire::check_reply(&reply, [0, 0], false)?;
    Ok(Ok(()))
}

/// What the program `name` requests (1.1).
pub fn inspect(endpoint: Endpoint, name: &str) -> Result<core::result::Result<Needs, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        codec::encode_str::<64>(name, &mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 7 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 6, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <Needs as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// The raw request flags of `name` (`mind::process::REQUEST_*`), including flags `needs` has no field for (1.2).
pub fn inspect_requests(endpoint: Endpoint, name: &str) -> Result<core::result::Result<u32, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        codec::encode_str::<64>(name, &mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 8 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 4, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <u32 as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// Gives the new program a copy of read-only memory `cap` in its fixed slot `slot`: only SLOT_DISPLAY, where a
/// window manager lends the surface of the window to record (issue u014); a writable one is refused (1.3).
pub fn grant_memory(endpoint: Endpoint, session: u32, slot: u8, cap: usize) -> Result<core::result::Result<(), Error>> {
    let words = [9 | MAJOR << 8 | ((session) as usize) << 16 | ((slot) as usize) << 48, 0];
    let reply = wire::call(endpoint, words, Some((cap, false)))?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    wire::check_reply(&reply, [0, 0], false)?;
    Ok(Ok(()))
}

/// `commit` in front: the caller must have the focus now; the program takes it and gives it back when it ends.
/// `rights` when the caller is not in front: nothing starts and the session stays open for `commit`. A console
/// program starts as with `commit` (issue 160, 1.5).
pub fn commit_in_front(endpoint: Endpoint, session: u32) -> Result<core::result::Result<u64, Error>> {
    let words = [10 | MAJOR << 8 | ((session) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, None)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let _ = wire::check_reply(&reply, [0x0, 0xffffffffffffffff], false)?;
    Ok(Ok(wire::field(&reply, 1, 0, 64) as u64))
}

/// Gives the new program a copy of the firmware variable privilege `cap` in SLOT_FIRMWARE, where a launcher lends
/// it with the user's consent for REQUEST_FIRMWARE (351-KRN-0027, 1.6).
pub fn grant_firmware(endpoint: Endpoint, session: u32, cap: usize) -> Result<core::result::Result<(), Error>> {
    let words = [11 | MAJOR << 8 | ((session) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, Some((cap, false)))?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    wire::check_reply(&reply, [0, 0], false)?;
    Ok(Ok(()))
}

/// A request to the `loader` interface that passed the receiver's schema check.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Request {
    List,
    Run { name: Text<64>, args: Text<1024> },
    Begin { name: Text<64>, args: Text<1024> },
    Grant { session: u32, slot: u8, cap: usize },
    Commit { session: u32 },
    Abort { session: u32 },
    Inspect { name: Text<64> },
    InspectRequests { name: Text<64> },
    GrantMemory { session: u32, slot: u8, cap: usize },
    CommitInFront { session: u32 },
    GrantFirmware { session: u32, cap: usize },
}

/// Checks a received message against the schema (MC-2.4): method, major version, unused bits, capability kind, and
/// for buffer calls every length and value of a private copy of the request (MC-2.11). `cap` is the slot passed to
/// `recv`; an unexpected capability is dropped (MC-2.12). The `Call` is what the reply functions need.
pub fn decode(request: &Received, cap: usize) -> core::result::Result<(Request, Call), Reject> {
    let words = request.data;
    wire::header(request, cap, MAJOR)?;
    match words[0] & 0xFF {
        1 => {
            let mut copy = [0u8; 1];
            let (call, length) = wire::take_buffer(request, cap, 3458, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::List, call))
        }
        2 => {
            let mut copy = [0u8; 1092];
            let (call, length) = wire::take_buffer(request, cap, 8, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            let name = <Text<64> as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let args = <Text<1024> as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Run { name, args }, call))
        }
        3 => {
            let mut copy = [0u8; 1092];
            let (call, length) = wire::take_buffer(request, cap, 4, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            let name = <Text<64> as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let args = <Text<1024> as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Begin { name, args }, call))
        }
        4 => {
            wire::body(request, cap, [0xffffffffff0000, 0x0], CAP_KIND_ENDPOINT, true)?;
            Ok((Request::Grant { session: wire::field(&words, 0, 16, 32) as u32, slot: wire::field(&words, 0, 48, 8) as u8, cap: cap }, Call::words(request, cap)))
        }
        5 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::Commit { session: wire::field(&words, 0, 16, 32) as u32 }, Call::words(request, cap)))
        }
        6 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::Abort { session: wire::field(&words, 0, 16, 32) as u32 }, Call::words(request, cap)))
        }
        7 => {
            let mut copy = [0u8; 66];
            let (call, length) = wire::take_buffer(request, cap, 6, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            let name = <Text<64> as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Inspect { name }, call))
        }
        8 => {
            let mut copy = [0u8; 66];
            let (call, length) = wire::take_buffer(request, cap, 4, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            let name = <Text<64> as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::InspectRequests { name }, call))
        }
        9 => {
            wire::body(request, cap, [0xffffffffff0000, 0x0], CAP_KIND_MEMORY, true)?;
            Ok((Request::GrantMemory { session: wire::field(&words, 0, 16, 32) as u32, slot: wire::field(&words, 0, 48, 8) as u8, cap: cap }, Call::words(request, cap)))
        }
        10 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::CommitInFront { session: wire::field(&words, 0, 16, 32) as u32 }, Call::words(request, cap)))
        }
        11 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_FIRMWARE, true)?;
            Ok((Request::GrantFirmware { session: wire::field(&words, 0, 16, 32) as u32, cap: cap }, Call::words(request, cap)))
        }
        _ => { wire::discard(request, cap); Err(Reject::Invalid) }
    }
}

pub fn reply_list(call: Call, value: &[Program]) -> Result<()> {
    wire::reply_buffer(call, |w| codec::encode_slice::<Program, 128>(value, w))
}
pub fn reply_run(call: Call, value: Result<u64>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_error(call, error) };
    wire::reply_buffer(call, |w| value.encode(w))
}
pub fn reply_begin(call: Call, value: core::result::Result<u32, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| value.encode(w))
}
pub fn reply_grant(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [0, 0])
}
pub fn reply_commit(call: Call, value: core::result::Result<u64, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [0, ((value) as usize) << 0])
}
pub fn reply_abort(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [0, 0])
}
pub fn reply_inspect(call: Call, value: core::result::Result<&Needs, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| value.encode(w))
}
pub fn reply_inspect_requests(call: Call, value: core::result::Result<u32, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| value.encode(w))
}
pub fn reply_grant_memory(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [0, 0])
}
pub fn reply_commit_in_front(call: Call, value: core::result::Result<u64, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [0, ((value) as usize) << 0])
}
pub fn reply_grant_firmware(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [0, 0])
}