// Generated by scripts/mind_idl.py from idl/log.wit; do not edit.
//! System log (`logd`, MC-10.6): a bounded ring of records with sequence numbers. The source of a record — the
//! sender's PID and the task name the kernel reports for it — is stamped by the server from the IPC sender, never taken
//! from the message. A reader sees a gap in the sequence numbers when the ring has dropped records it did not read.
//! Services and `init` write (their `println!` lines go here too); reading needs the read badge
//! (`mind::log::BADGE_READ`), which only the shell's client carries (it lends it to `dmesg`).
#![allow(clippy::all, unused_imports, unused_mut, unused_variables)]
use crate::abi::*;
use crate::ipc::{Endpoint, Received};
use crate::mem::Pages;
use crate::sys::{Error as SysError, Result};
use super::codec::{self, List, Reader, Text, Wire, Writer};
use super::wire::{self, Call, Reject};

pub const PACKAGE: &str = "mind:log";
pub const VERSION: (u8, u8, u8) = (1, 0, 0);
const MAJOR: usize = 1;

/// Why a request failed.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[repr(u8)]
pub enum Error { #[default] Denied = 0, Invalid = 1 }
impl Error {
    /// The case with wire code `code`; None for a code the interface does not define.
    pub fn from_code(code: usize) -> Option<Self> { match code { 0 => Some(Self::Denied), 1 => Some(Self::Invalid), _ => None } }
}
impl Wire for Error {
    const MAX: usize = 1;
    fn encode(&self, w: &mut Writer) -> Option<()> { (*self as u8).encode(w) }
    fn decode(r: &mut Reader) -> Option<Self> { Self::from_code(u8::decode(r)? as usize) }
}

/// One record. `level`: 0 debug, 1 info, 2 warning, 3 error; `time-ms`: milliseconds since boot when `logd`
/// received it.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Entry { pub seq: u64, pub time_ms: u64, pub pid: u64, pub name: Text<16>, pub level: u8, pub text: Text<200> }
impl Wire for Entry {
    const MAX: usize = <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <Text<16> as Wire>::MAX + <u8 as Wire>::MAX + <Text<200> as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.seq.encode(w)?; self.time_ms.encode(w)?; self.pid.encode(w)?; self.name.encode(w)?; self.level.encode(w)?; self.text.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { seq: Wire::decode(r)?, time_ms: Wire::decode(r)?, pid: Wire::decode(r)?, name: Wire::decode(r)?, level: Wire::decode(r)?, text: Wire::decode(r)? }) }
}

/// The ring: the oldest record kept, the next sequence number, records dropped to make room and records refused
/// because their sender wrote too fast (MC-10.2).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct State { pub first: u64, pub next: u64, pub dropped: u64, pub suppressed: u64 }
impl Wire for State {
    const MAX: usize = <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.first.encode(w)?; self.next.encode(w)?; self.dropped.encode(w)?; self.suppressed.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { first: Wire::decode(r)?, next: Wire::decode(r)?, dropped: Wire::decode(r)?, suppressed: Wire::decode(r)? }) }
}

/// Adds a record from the caller.
pub fn write(endpoint: Endpoint, level: u8, text: &str) -> Result<core::result::Result<(), Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        level.encode(&mut w).ok_or(SysError::Invalid)?;
        codec::encode_str::<200>(text, &mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 1 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 0, false, false)?;
    if length != Some(0) { return Err(SysError::Invalid); }
    Ok(Ok(()))
}

/// Records from sequence number `from` on (from the oldest kept if that is later), at most 16.
pub fn read(endpoint: Endpoint, from: u64) -> Result<core::result::Result<List<Entry, 16>, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        from.encode(&mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 2 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 3922, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <List<Entry, 16> as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// The state of the ring.
pub fn state(endpoint: Endpoint) -> Result<core::result::Result<State, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 3 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 32, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <State as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// A request to the `log` interface that passed the receiver's schema check.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Request {
    Write { level: u8, text: Text<200> },
    Read { from: u64 },
    State,
}

/// Checks a received message against the schema (MC-2.4): method, major version, unused bits, capability kind, and
/// for buffer calls every length and value of a private copy of the request (MC-2.11). `cap` is the slot passed to
/// `recv`; an unexpected capability is dropped (MC-2.12). The `Call` is what the reply functions need.
pub fn decode(request: &Received, cap: usize) -> core::result::Result<(Request, Call), Reject> {
    let words = request.data;
    wire::header(request, cap, MAJOR)?;
    match words[0] & 0xFF {
        1 => {
            let mut copy = [0u8; 203];
            let (call, length) = wire::take_buffer(request, cap, 0, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            let level = <u8 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let text = <Text<200> as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Write { level, text }, call))
        }
        2 => {
            let mut copy = [0u8; 8];
            let (call, length) = wire::take_buffer(request, cap, 3922, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            let from = <u64 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Read { from }, call))
        }
        3 => {
            let mut copy = [0u8; 1];
            let (call, length) = wire::take_buffer(request, cap, 32, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::State, call))
        }
        _ => { wire::discard(request, cap); Err(Reject::Invalid) }
    }
}

pub fn reply_write(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |_| Some(()))
}
pub fn reply_read(call: Call, value: core::result::Result<&[Entry], Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| codec::encode_slice::<Entry, 16>(value, w))
}
pub fn reply_state(call: Call, value: core::result::Result<&State, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| value.encode(w))
}