// Generated by scripts/mind_idl.py; do not edit.
//! Interfaces generated from idl/*.wit (MIND IDL v0.2).
pub mod codec;
pub mod wire;
pub mod audio;
pub mod block;
pub mod display;
pub mod init;
pub mod keyboard;
pub mod loader;
pub mod log;
pub mod net;
pub mod netpolicy;
pub mod rtc;
pub mod socket;
pub mod sysinfo;
pub mod tts;
pub mod vfs;
