// Generated by scripts/mind_idl.py from idl/net.wit; do not edit.
//! Network card driver (`virtio_net`): raw Ethernet frames of one device. Its only clients are the network stack and
//! the shell's diagnostics (Appendix B.6: the driver gets no say over what the frames mean). Frames travel in MIND IDL
//! buffers, so the driver works on its own copy of a frame to send.
//!
//! 1.1 (issue 106): transmit checksum offload. When the device offers it (`offloads` bit 0), `send-partial` hands it a
//! frame whose TCP or UDP checksum the device completes: the field holds the pseudo-header sum, `start` is where the
//! summed bytes begin (from the start of the frame) and `offset` where the checksum field is, from `start`.
//!
//! 1.2 (issue 107): a frame ring shared with the network stack, so frames need no call each. The client lends a memory
//! region (`attach`, at least `ring-bytes` long); the driver moves sent frames out of its transmit ring and received
//! frames into its receive ring, and `kick` wakes the driver after the client queued frames (and tells it the client
//! still uses the ring: after a second without a kick, received frames go back to `receive`). Layout, little-endian:
//! bytes 0-3 the transmit head (frames the client queued), 64-67 the transmit tail (frames the driver took), 128-131
//! the receive head (frames the driver queued), 192-195 the receive tail (frames the client took), all counting up and
//! wrapping; from 4096, `ring-slots` transmit slots and then as many receive slots of 2048 bytes: a u16 length, a u16
//! checksum start and a u16 checksum offset (both 0: no checksum to complete; transmit only), then the frame from byte
//! 8. Each side checks every index and length it reads from the shared region.
#![allow(clippy::all, unused_imports, unused_mut, unused_variables)]
use crate::abi::*;
use crate::ipc::{Endpoint, Received};
use crate::mem::Pages;
use crate::sys::{Error as SysError, Result};
use super::codec::{self, List, Reader, Text, Wire, Writer};
use super::wire::{self, Call, Reject};

pub const PACKAGE: &str = "mind:net";
pub const VERSION: (u8, u8, u8) = (1, 2, 0);
const MAJOR: usize = 1;

/// Why a request failed.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[repr(u8)]
pub enum Error { #[default] NoDevice = 0, Busy = 1, Empty = 2, Invalid = 3 }
impl Error {
    /// The case with wire code `code`; None for a code the interface does not define.
    pub fn from_code(code: usize) -> Option<Self> { match code { 0 => Some(Self::NoDevice), 1 => Some(Self::Busy), 2 => Some(Self::Empty), 3 => Some(Self::Invalid), _ => None } }
}
impl Wire for Error {
    const MAX: usize = 1;
    fn encode(&self, w: &mut Writer) -> Option<()> { (*self as u8).encode(w) }
    fn decode(r: &mut Reader) -> Option<Self> { Self::from_code(u8::decode(r)? as usize) }
}

/// The device: MAC address (low 48 bits, first byte in bits 40-47), largest frame without the Ethernet header,
/// link state as the device reports it.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Info { pub mac: u64, pub mtu: u16, pub link: bool }
impl Wire for Info {
    const MAX: usize = <u64 as Wire>::MAX + <u16 as Wire>::MAX + <bool as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.mac.encode(w)?; self.mtu.encode(w)?; self.link.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { mac: Wire::decode(r)?, mtu: Wire::decode(r)?, link: Wire::decode(r)? }) }
}

/// Frames since the driver started; `dropped` counts received frames lost because the queue of received frames was full.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Counters { pub sent: u64, pub received: u64, pub dropped: u64, pub interrupts: u64 }
impl Wire for Counters {
    const MAX: usize = <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.sent.encode(w)?; self.received.encode(w)?; self.dropped.encode(w)?; self.interrupts.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { sent: Wire::decode(r)?, received: Wire::decode(r)?, dropped: Wire::decode(r)?, interrupts: Wire::decode(r)? }) }
}

pub fn info(endpoint: Endpoint) -> Result<core::result::Result<Info, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 1 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 11, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <Info as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// Queues one Ethernet frame (destination, source, type and payload, without the checksum). Error busy: the
/// transmit ring is full; invalid: shorter than 14 bytes.
pub fn send(endpoint: Endpoint, frame: &[u8]) -> Result<core::result::Result<(), Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        codec::encode_bytes::<1514>(frame, &mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 2 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 0, false, false)?;
    if length != Some(0) { return Err(SysError::Invalid); }
    Ok(Ok(()))
}

/// The oldest received frame. Error empty: none is waiting.
pub fn receive(endpoint: Endpoint, out: &mut [u8]) -> Result<core::result::Result<usize, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 3 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 1516, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); let data = codec::decode_bytes::<1514>(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)?; out.get_mut(..data.len()).ok_or(SysError::Invalid)?.copy_from_slice(data); data.len() }))
}

/// Answers once a received frame is waiting (the reply comes from the interrupt); returns how many are waiting.
pub fn wait(endpoint: Endpoint) -> Result<u32> {
    let words = [4 | MAJOR << 8, 0];
    let reply = wire::call(endpoint, words, None)?;
    let _ = wire::check_reply(&reply, [0xffffffff0000, 0x0], false)?;
    Ok(wire::field(&reply, 0, 16, 32) as u32)
}

pub fn counters(endpoint: Endpoint) -> Result<Counters> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 5 | MAJOR << 8, &buffer, length)?;
    let length = wire::buffer_reply(&reply, 32, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <Counters as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? })
}

/// What the device can do for the sender (1.1): bit 0, completing TCP and UDP checksums (`send-partial`).
pub fn offloads(endpoint: Endpoint) -> Result<u32> {
    let words = [6 | MAJOR << 8, 0];
    let reply = wire::call(endpoint, words, None)?;
    let _ = wire::check_reply(&reply, [0xffffffff0000, 0x0], false)?;
    Ok(wire::field(&reply, 0, 16, 32) as u32)
}

/// Like `send`, with the checksum completed by the device (1.1). Error invalid also when the device cannot do it or
/// `start` and `offset` do not leave room for the 16-bit field inside the frame.
pub fn send_partial(endpoint: Endpoint, frame: &[u8], start: u16, offset: u16) -> Result<core::result::Result<(), Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        codec::encode_bytes::<1514>(frame, &mut w).ok_or(SysError::Invalid)?;
        start.encode(&mut w).ok_or(SysError::Invalid)?;
        offset.encode(&mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 7 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 0, false, false)?;
    if length != Some(0) { return Err(SysError::Invalid); }
    Ok(Ok(()))
}

/// Uses `ring` as the shared frame ring (1.2); returns the slots per direction. A new ring replaces the old one.
pub fn attach(endpoint: Endpoint, ring: usize) -> Result<core::result::Result<u32, Error>> {
    let words = [8 | MAJOR << 8, 0];
    let reply = wire::call(endpoint, words, Some((ring, false)))?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let _ = wire::check_reply(&reply, [0xffffffff0000, 0x0], false)?;
    Ok(Ok(wire::field(&reply, 0, 16, 32) as u32))
}

/// The client queued frames or still uses the ring (1.2). Error invalid: no ring is attached (attach again).
pub fn kick(endpoint: Endpoint) -> Result<core::result::Result<(), Error>> {
    let words = [9 | MAJOR << 8, 0];
    let reply = wire::call(endpoint, words, None)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    wire::check_reply(&reply, [0, 0], false)?;
    Ok(Ok(()))
}

/// Size of the scratch buffer `decode` copies a request into (the largest request).
pub const REQUEST_MAX: usize = 1520;

/// A request to the `net` interface that passed the receiver's schema check.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Request<'a> {
    Info,
    Send { frame: &'a [u8] },
    Receive,
    Wait,
    Counters,
    Offloads,
    SendPartial { frame: &'a [u8], start: u16, offset: u16 },
    Attach { ring: usize },
    Kick,
}

/// Checks a received message against the schema (MC-2.4): method, major version, unused bits, capability kind, and
/// for buffer calls every length and value of a private copy of the request (MC-2.11). `cap` is the slot passed to
/// `recv`; an unexpected capability is dropped (MC-2.12). The `Call` is what the reply functions need.
/// The private copy is `scratch`, which the `bytes` of the request borrow.
pub fn decode<'a>(request: &Received, cap: usize, scratch: &'a mut [u8; REQUEST_MAX]) -> core::result::Result<(Request<'a>, Call), Reject> {
    let words = request.data;
    wire::header(request, cap, MAJOR)?;
    match words[0] & 0xFF {
        1 => {
            let (call, length) = wire::take_buffer(request, cap, 11, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Info, call))
        }
        2 => {
            let (call, length) = wire::take_buffer(request, cap, 0, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let frame = codec::decode_bytes::<1514>(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Send { frame }, call))
        }
        3 => {
            let (call, length) = wire::take_buffer(request, cap, 1516, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Receive, call))
        }
        4 => {
            wire::body(request, cap, [0x0, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::Wait, Call::words(request, cap)))
        }
        5 => {
            let (call, length) = wire::take_buffer(request, cap, 32, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Counters, call))
        }
        6 => {
            wire::body(request, cap, [0x0, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::Offloads, Call::words(request, cap)))
        }
        7 => {
            let (call, length) = wire::take_buffer(request, cap, 0, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let frame = codec::decode_bytes::<1514>(&mut r).ok_or(Reject::Invalid)?;
            let start = <u16 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let offset = <u16 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::SendPartial { frame, start, offset }, call))
        }
        8 => {
            wire::body(request, cap, [0x0, 0x0], CAP_KIND_MEMORY, true)?;
            Ok((Request::Attach { ring: cap }, Call::words(request, cap)))
        }
        9 => {
            wire::body(request, cap, [0x0, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::Kick, Call::words(request, cap)))
        }
        _ => { wire::discard(request, cap); Err(Reject::Invalid) }
    }
}

pub fn reply_info(call: Call, value: core::result::Result<&Info, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| value.encode(w))
}
pub fn reply_send(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |_| Some(()))
}
pub fn reply_receive(call: Call, value: core::result::Result<&[u8], Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| codec::encode_bytes::<1514>(value, w))
}
pub fn reply_wait(call: Call, value: u32) -> Result<()> {
    wire::finish(call, [((value) as usize) << 16, 0])
}
pub fn reply_counters(call: Call, value: &Counters) -> Result<()> {
    wire::reply_buffer(call, |w| value.encode(w))
}
pub fn reply_offloads(call: Call, value: u32) -> Result<()> {
    wire::finish(call, [((value) as usize) << 16, 0])
}
pub fn reply_send_partial(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |_| Some(()))
}
pub fn reply_attach(call: Call, value: core::result::Result<u32, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [((value) as usize) << 16, 0])
}
pub fn reply_kick(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [0, 0])
}