// Generated by scripts/mind_idl.py from idl/parse.wit; do not edit.
//! Parser service (`parse`, 109-NET-0008, MC-11.11, Appendix B.6): turns bounded bytes from outside into typed messages,
//! so the program that holds the network and the files does not parse them itself. It holds nothing but its own
//! endpoint and the system log: no files, no network, no spawn, no devices. Each request is parsed on its own; nothing
//! of one stays for the next. A refusal is logged with the client's PID. The client still checks what a typed message
//! says against what it asked for (MC-11.5).
#![allow(clippy::all, unused_imports, unused_mut, unused_variables)]
use crate::abi::*;
use crate::ipc::{Endpoint, Received};
use crate::mem::Pages;
use crate::sys::{Error as SysError, Result};
use super::codec::{self, List, Reader, Text, Wire, Writer};
use super::wire::{self, Call, Reject};

pub const PACKAGE: &str = "mind:parse";
pub const VERSION: (u8, u8, u8) = (1, 0, 0);
const MAJOR: usize = 1;

/// Why a request failed: `malformed`, the bytes are not of the form asked for.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[repr(u8)]
pub enum Error { #[default] Malformed = 0 }
impl Error {
    /// The case with wire code `code`; None for a code the interface does not define.
    pub fn from_code(code: usize) -> Option<Self> { match code { 0 => Some(Self::Malformed), _ => None } }
}
impl Wire for Error {
    const MAX: usize = 1;
    fn encode(&self, w: &mut Writer) -> Option<()> { (*self as u8).encode(w) }
    fn decode(r: &mut Reader) -> Option<Self> { Self::from_code(u8::decode(r)? as usize) }
}

/// An HTTP/1.x response head. `length` is `Content-Length` when `has-length`. When `has-range`, `Content-Range` is
/// bytes `range-start` to `range-end` (inclusive) of `range-total`, or nothing of `range-total` when
/// `range-unsatisfied` (`bytes */total`). `chunked`: a transfer coding other than identity.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct HttpHead { pub status: u16, pub has_length: bool, pub length: u64, pub has_range: bool, pub range_unsatisfied: bool, pub range_start: u64, pub range_end: u64, pub range_total: u64, pub chunked: bool }
impl Wire for HttpHead {
    const MAX: usize = <u16 as Wire>::MAX + <bool as Wire>::MAX + <u64 as Wire>::MAX + <bool as Wire>::MAX + <bool as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <bool as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.status.encode(w)?; self.has_length.encode(w)?; self.length.encode(w)?; self.has_range.encode(w)?; self.range_unsatisfied.encode(w)?; self.range_start.encode(w)?; self.range_end.encode(w)?; self.range_total.encode(w)?; self.chunked.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { status: Wire::decode(r)?, has_length: Wire::decode(r)?, length: Wire::decode(r)?, has_range: Wire::decode(r)?, range_unsatisfied: Wire::decode(r)?, range_start: Wire::decode(r)?, range_end: Wire::decode(r)?, range_total: Wire::decode(r)?, chunked: Wire::decode(r)? }) }
}

/// The head of an HTTP response: its status line and header lines, without the blank line that ends them.
pub fn http_head(endpoint: Endpoint, head: &[u8]) -> Result<core::result::Result<HttpHead, Error>> {
    let mut buffer = Pages::new(12288).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        codec::encode_bytes::<8192>(head, &mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 1 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 38, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <HttpHead as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// Size of the scratch buffer `decode` copies a request into (the largest request).
pub const REQUEST_MAX: usize = 8194;

/// A request to the `parse` interface that passed the receiver's schema check.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Request<'a> {
    HttpHead { head: &'a [u8] },
}

/// Checks a received message against the schema (MC-2.4): method, major version, unused bits, capability kind, and
/// for buffer calls every length and value of a private copy of the request (MC-2.11). `cap` is the slot passed to
/// `recv`; an unexpected capability is dropped (MC-2.12). The `Call` is what the reply functions need.
/// The private copy is `scratch`, which the `bytes` of the request borrow.
pub fn decode<'a>(request: &Received, cap: usize, scratch: &'a mut [u8; REQUEST_MAX]) -> core::result::Result<(Request<'a>, Call), Reject> {
    let words = request.data;
    wire::header(request, cap, MAJOR)?;
    match words[0] & 0xFF {
        1 => {
            let (call, length) = wire::take_buffer(request, cap, 38, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let head = codec::decode_bytes::<8192>(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::HttpHead { head }, call))
        }
        _ => { wire::discard(request, cap); Err(Reject::Invalid) }
    }
}

pub fn reply_http_head(call: Call, value: core::result::Result<&HttpHead, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| value.encode(w))
}