// Generated by scripts/mind_idl.py from idl/rtc.wit; do not edit.
//! Calendar time from the CMOS RTC, a service separate from the monotonic clock (MC-5.6).
#![allow(clippy::all, unused_imports, unused_variables, unused_mut, dead_code)]
use crate::abi::*;
use crate::ipc::{Endpoint, Received};
use crate::sys::{Error as SysError, Result};
use super::wire::{self, Reject};

pub const PACKAGE: &str = "mind:rtc";
pub const VERSION: (u8, u8, u8) = (1, 1, 0);
const MAJOR: usize = 1;

/// Seconds since midnight; none if the RTC cannot be read.
pub fn now(endpoint: Endpoint) -> Result<Option<u32>> {
    let words = [1 | MAJOR << 8, 0];
    let reply = wire::call(endpoint, words, None)?;
    let status = wire::check_reply(&reply, [0xffffffff0000, 0x0], true, false)?;
    Ok(if status == wire::Status::None { None } else { Some(wire::field(&reply, 0, 16, 32) as u32) })
}

/// Days since 2000-01-01 (the date of `now`); none if the RTC cannot be read. Added in 1.1.
pub fn date(endpoint: Endpoint) -> Result<Option<u32>> {
    let words = [2 | MAJOR << 8, 0];
    let reply = wire::call(endpoint, words, None)?;
    let status = wire::check_reply(&reply, [0xffffffff0000, 0x0], true, false)?;
    Ok(if status == wire::Status::None { None } else { Some(wire::field(&reply, 0, 16, 32) as u32) })
}

/// A request to the `rtc` interface that passed the receiver's schema check.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Request {
    Now,
    Date,
}

/// Checks a received message against the schema (MC-2.4): method, major version, unused bits, enum values, capability
/// kind. `cap` is the slot passed to `recv`; an unexpected capability is dropped (MC-2.12). Bulk arguments are checked
/// by `args_<function>` once the server has mapped the buffer.
pub fn decode(request: &Received, cap: usize) -> core::result::Result<Request, Reject> {
    let words = request.data;
    wire::header(request, cap, MAJOR)?;
    match words[0] & 0xFF {
        1 => {
            wire::body(request, cap, [0x0, 0x0], CAP_KIND_NONE, false)?;
            Ok(Request::Now)
        }
        2 => {
            wire::body(request, cap, [0x0, 0x0], CAP_KIND_NONE, false)?;
            Ok(Request::Date)
        }
        _ => { wire::discard(request, cap); Err(Reject::Invalid) }
    }
}

pub fn reply_now(value: Option<u32>) -> Result<()> {
    let Some(value) = value else { return wire::reply([wire::STATUS_NONE, 0]) };
    wire::reply([((value) as usize) << 16, 0])
}
pub fn reply_date(value: Option<u32>) -> Result<()> {
    let Some(value) = value else { return wire::reply([wire::STATUS_NONE, 0]) };
    wire::reply([((value) as usize) << 16, 0])
}
