// Generated by scripts/mind_idl.py from idl/rtc.wit; do not edit.
//! Calendar time from the CMOS RTC, a service separate from the monotonic clock (MC-5.6).
#![allow(clippy::all, unused_imports)]
use crate::abi::*;
use crate::ipc::{Endpoint, Received};
use crate::sys::Result;
use super::wire::{self, Reject};

pub const PACKAGE: &str = "mind:rtc";
pub const VERSION: (u8, u8, u8) = (1, 0, 0);
const MAJOR: usize = 1;

/// Seconds since midnight; none if the RTC cannot be read.
pub fn now(endpoint: Endpoint) -> Result<Option<u32>> {
    let words = [1 | MAJOR << 8, 0];
    let reply = wire::call(endpoint, words, None)?;
    let none = wire::check_reply(&reply, [0xffffffff0000, 0x0], true)?;
    Ok(if none { None } else { Some(wire::field(&reply, 0, 16, 32) as u32) })
}

/// A request to the `rtc` interface that passed the receiver's schema check.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Request {
    Now,
}

/// Checks a received message against the schema (MC-2.4): method, major version, unused bits, capability kind.
/// `cap` is the slot passed to `recv`; an unexpected capability is dropped (MC-2.12).
pub fn decode(request: &Received, cap: usize) -> core::result::Result<Request, Reject> {
    let words = request.data;
    wire::header(request, cap, MAJOR)?;
    match words[0] & 0xFF {
        1 => {
            wire::body(request, cap, [0x0, 0x0], CAP_KIND_NONE, false)?;
            Ok(Request::Now)
        }
        _ => { wire::discard(request, cap); Err(Reject::Invalid) }
    }
}

pub fn reply_now(value: Option<u32>) -> Result<()> {
    match value { None => wire::reply([wire::STATUS_NONE, 0]), Some(value) => wire::reply([((value) as usize) << 16, 0]) }
}
