// Generated by scripts/mind_idl.py from idl/socket.wit; do not edit.
//! Network stack (`netstack`): IPv4 over the network card driver, with DHCP, ICMP echo, a DNS resolver, UDP and TCP.
//! Addresses are IPv4 in a u32 (a.b.c.d is a << 24 | b << 16 | c << 8 | d). A socket handle belongs to the client that
//! opened it (PID and endpoint badge); a client has at most 8 sockets, the stack 32, each with bounded buffers.
//! Calls that wait for the network (`ping`, `resolve`, `tcp-connect`) are answered later, when the answer arrives or
//! the timeout passes; the other calls never block (error `again`: try later).
//!
//! What a client may do comes from the badge of its endpoint capability (issue 102): the operator's badge (the shell)
//! may do anything; a flow grant's badge only what the policy broker registered for it (`policy-set`: destinations,
//! protocols, a term and a volume), and is refused (`denied`) otherwise; the policy badge registers grants; an
//! unbadged client is refused. Major version 2: `denied` and the badge rules change what 1.0 calls may answer.
//!
//! Several cards (issue 105, 2.1): each card driver is one interface with its own configuration (DHCP per card). A flow
//! goes out through the interface whose network holds the destination, otherwise through the first interface with a
//! gateway; `config` describes that default interface, `interfaces` all of them.
#![allow(clippy::all, unused_imports, unused_mut, unused_variables)]
use crate::abi::*;
use crate::ipc::{Endpoint, Received};
use crate::mem::Pages;
use crate::sys::{Error as SysError, Result};
use super::codec::{self, List, Reader, Text, Wire, Writer};
use super::wire::{self, Call, Reject};

pub const PACKAGE: &str = "mind:socket";
pub const VERSION: (u8, u8, u8) = (2, 1, 0);
const MAJOR: usize = 2;

/// Why a request failed.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[repr(u8)]
pub enum Error { #[default] NoNetwork = 0, NoSocket = 1, Closed = 2, Again = 3, Refused = 4, Timeout = 5, Invalid = 6, Limit = 7, Unreachable = 8, NotFound = 9, Denied = 10 }
impl Error {
    /// The case with wire code `code`; None for a code the interface does not define.
    pub fn from_code(code: usize) -> Option<Self> { match code { 0 => Some(Self::NoNetwork), 1 => Some(Self::NoSocket), 2 => Some(Self::Closed), 3 => Some(Self::Again), 4 => Some(Self::Refused), 5 => Some(Self::Timeout), 6 => Some(Self::Invalid), 7 => Some(Self::Limit), 8 => Some(Self::Unreachable), 9 => Some(Self::NotFound), 10 => Some(Self::Denied), _ => None } }
}
impl Wire for Error {
    const MAX: usize = 1;
    fn encode(&self, w: &mut Writer) -> Option<()> { (*self as u8).encode(w) }
    fn decode(r: &mut Reader) -> Option<Self> { Self::from_code(u8::decode(r)? as usize) }
}

/// A protocol a rule allows.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[repr(u8)]
pub enum Protocol { #[default] Tcp = 0, Udp = 1, Icmp = 2 }
impl Protocol {
    /// The case with wire code `code`; None for a code the interface does not define.
    pub fn from_code(code: usize) -> Option<Self> { match code { 0 => Some(Self::Tcp), 1 => Some(Self::Udp), 2 => Some(Self::Icmp), _ => None } }
}
impl Wire for Protocol {
    const MAX: usize = 1;
    fn encode(&self, w: &mut Writer) -> Option<()> { (*self as u8).encode(w) }
    fn decode(r: &mut Reader) -> Option<Self> { Self::from_code(u8::decode(r)? as usize) }
}

/// One destination a grant may reach: an address (never 0), a port (0: any; ICMP has none) and a protocol.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Rule { pub address: u32, pub port: u16, pub protocol: Protocol }
impl Wire for Rule {
    const MAX: usize = <u32 as Wire>::MAX + <u16 as Wire>::MAX + <Protocol as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.address.encode(w)?; self.port.encode(w)?; self.protocol.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { address: Wire::decode(r)?, port: Wire::decode(r)?, protocol: Wire::decode(r)? }) }
}

/// A network interface: its card (0: the first driver instance), configuration (address 0: not configured yet),
/// MAC address and the frames it sent and received.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Interface { pub card: u8, pub address: u32, pub prefix: u8, pub gateway: u32, pub dns: u32, pub mac: u64, pub dhcp: bool, pub sent: u64, pub received: u64 }
impl Wire for Interface {
    const MAX: usize = <u8 as Wire>::MAX + <u32 as Wire>::MAX + <u8 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX + <u64 as Wire>::MAX + <bool as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.card.encode(w)?; self.address.encode(w)?; self.prefix.encode(w)?; self.gateway.encode(w)?; self.dns.encode(w)?; self.mac.encode(w)?; self.dhcp.encode(w)?; self.sent.encode(w)?; self.received.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { card: Wire::decode(r)?, address: Wire::decode(r)?, prefix: Wire::decode(r)?, gateway: Wire::decode(r)?, dns: Wire::decode(r)?, mac: Wire::decode(r)?, dhcp: Wire::decode(r)?, sent: Wire::decode(r)?, received: Wire::decode(r)? }) }
}

/// What a grant used: bytes sent and received, sockets open, milliseconds left (0: expired).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Usage { pub sent: u64, pub received: u64, pub sockets: u32, pub left_ms: u32 }
impl Wire for Usage {
    const MAX: usize = <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.sent.encode(w)?; self.received.encode(w)?; self.sockets.encode(w)?; self.left_ms.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { sent: Wire::decode(r)?, received: Wire::decode(r)?, sockets: Wire::decode(r)?, left_ms: Wire::decode(r)? }) }
}

/// The interface: address and prefix length, gateway and DNS server (0: none), MAC address, whether DHCP
/// configured it (or the static fallback did).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Config { pub address: u32, pub prefix: u8, pub gateway: u32, pub dns: u32, pub mac: u64, pub dhcp: bool }
impl Wire for Config {
    const MAX: usize = <u32 as Wire>::MAX + <u8 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX + <u64 as Wire>::MAX + <bool as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.address.encode(w)?; self.prefix.encode(w)?; self.gateway.encode(w)?; self.dns.encode(w)?; self.mac.encode(w)?; self.dhcp.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { address: Wire::decode(r)?, prefix: Wire::decode(r)?, gateway: Wire::decode(r)?, dns: Wire::decode(r)?, mac: Wire::decode(r)?, dhcp: Wire::decode(r)? }) }
}

/// A UDP datagram and where it came from.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Datagram { pub address: u32, pub port: u16, pub data: List<u8, 1472> }
impl Wire for Datagram {
    const MAX: usize = <u32 as Wire>::MAX + <u16 as Wire>::MAX + <List<u8, 1472> as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.address.encode(w)?; self.port.encode(w)?; self.data.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { address: Wire::decode(r)?, port: Wire::decode(r)?, data: Wire::decode(r)? }) }
}

pub fn config(endpoint: Endpoint) -> Result<core::result::Result<Config, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 1 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 22, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <Config as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// ICMP echo to `address`; returns the round trip in microseconds.
pub fn ping(endpoint: Endpoint, address: u32, timeout_ms: u32) -> Result<core::result::Result<u32, Error>> {
    let words = [2 | MAJOR << 8 | ((address) as usize) << 16, ((timeout_ms) as usize) << 0];
    let reply = wire::call(endpoint, words, None)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let _ = wire::check_reply(&reply, [0xffffffff0000, 0x0], false)?;
    Ok(Ok(wire::field(&reply, 0, 16, 32) as u32))
}

/// IPv4 address of `name` from DNS server `server` (0: the configured one) on `port` (0: 53).
pub fn resolve(endpoint: Endpoint, name: &str, server: u32, port: u16, timeout_ms: u32) -> Result<core::result::Result<u32, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        codec::encode_str::<253>(name, &mut w).ok_or(SysError::Invalid)?;
        server.encode(&mut w).ok_or(SysError::Invalid)?;
        port.encode(&mut w).ok_or(SysError::Invalid)?;
        timeout_ms.encode(&mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 3 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 4, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <u32 as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// A UDP socket on local `port` (0: any free port).
pub fn udp_open(endpoint: Endpoint, port: u16) -> Result<core::result::Result<u32, Error>> {
    let words = [4 | MAJOR << 8 | ((port) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, None)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let _ = wire::check_reply(&reply, [0xffffffff0000, 0x0], false)?;
    Ok(Ok(wire::field(&reply, 0, 16, 32) as u32))
}

pub fn udp_send(endpoint: Endpoint, socket: u32, address: u32, port: u16, data: &[u8]) -> Result<core::result::Result<(), Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        socket.encode(&mut w).ok_or(SysError::Invalid)?;
        address.encode(&mut w).ok_or(SysError::Invalid)?;
        port.encode(&mut w).ok_or(SysError::Invalid)?;
        codec::encode_bytes::<1472>(data, &mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 5 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 0, false, false)?;
    if length != Some(0) { return Err(SysError::Invalid); }
    Ok(Ok(()))
}

/// The oldest datagram received on the socket. Error again: none is waiting.
pub fn udp_receive(endpoint: Endpoint, socket: u32) -> Result<core::result::Result<Datagram, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        socket.encode(&mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 6 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 1480, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <Datagram as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// A TCP connection to `address` and `port`, answered once it is established (or refused, or timed out).
pub fn tcp_connect(endpoint: Endpoint, address: u32, port: u16, timeout_ms: u32) -> Result<core::result::Result<u32, Error>> {
    let words = [7 | MAJOR << 8 | ((address) as usize) << 16 | ((port) as usize) << 48, ((timeout_ms) as usize) << 0];
    let reply = wire::call(endpoint, words, None)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let _ = wire::check_reply(&reply, [0xffffffff0000, 0x0], false)?;
    Ok(Ok(wire::field(&reply, 0, 16, 32) as u32))
}

/// Queues data; returns how many bytes were taken (0 with a full send buffer).
pub fn tcp_send(endpoint: Endpoint, socket: u32, data: &[u8]) -> Result<core::result::Result<u32, Error>> {
    let mut buffer = Pages::new(8192).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        socket.encode(&mut w).ok_or(SysError::Invalid)?;
        codec::encode_bytes::<4096>(data, &mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 8 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 4, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <u32 as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// Up to `length` received bytes. Error again: nothing yet; closed: the peer closed and everything was read.
pub fn tcp_receive(endpoint: Endpoint, socket: u32, length: u32, out: &mut [u8]) -> Result<core::result::Result<usize, Error>> {
    let mut buffer = Pages::new(8192).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        socket.encode(&mut w).ok_or(SysError::Invalid)?;
        length.encode(&mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 9 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 4098, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); let data = codec::decode_bytes::<4096>(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)?; out.get_mut(..data.len()).ok_or(SysError::Invalid)?.copy_from_slice(data); data.len() }))
}

/// Closes a socket (TCP: after the queued data is sent) and frees its handle.
pub fn close(endpoint: Endpoint, socket: u32) -> Result<core::result::Result<(), Error>> {
    let words = [10 | MAJOR << 8 | ((socket) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, None)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    wire::check_reply(&reply, [0, 0], false)?;
    Ok(Ok(()))
}

/// Registers what clients with `badge` may reach, for `seconds`, up to `bytes` in both directions (policy badge only).
pub fn policy_set(endpoint: Endpoint, badge: u16, rules: &[Rule], seconds: u32, bytes: u64) -> Result<core::result::Result<(), Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        badge.encode(&mut w).ok_or(SysError::Invalid)?;
        codec::encode_slice::<Rule, 16>(rules, &mut w).ok_or(SysError::Invalid)?;
        seconds.encode(&mut w).ok_or(SysError::Invalid)?;
        bytes.encode(&mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 11 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 0, false, false)?;
    if length != Some(0) { return Err(SysError::Invalid); }
    Ok(Ok(()))
}

/// Drops a grant: its sockets are closed and further requests with its badge are refused (policy badge only).
pub fn policy_drop(endpoint: Endpoint, badge: u16) -> Result<core::result::Result<u32, Error>> {
    let words = [12 | MAJOR << 8 | ((badge) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, None)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let _ = wire::check_reply(&reply, [0xffffffff0000, 0x0], false)?;
    Ok(Ok(wire::field(&reply, 0, 16, 32) as u32))
}

/// What a grant has used (policy badge only).
pub fn policy_usage(endpoint: Endpoint, badge: u16) -> Result<core::result::Result<Usage, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        badge.encode(&mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 13 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 24, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <Usage as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// Every interface whose card driver answered (2.1).
pub fn interfaces(endpoint: Endpoint) -> Result<core::result::Result<List<Interface, 4>, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 14 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 158, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <List<Interface, 4> as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// Size of the scratch buffer `decode` copies a request into (the largest request).
pub const REQUEST_MAX: usize = 4102;

/// A request to the `socket` interface that passed the receiver's schema check.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Request<'a> {
    Config,
    Ping { address: u32, timeout_ms: u32 },
    Resolve { name: Text<253>, server: u32, port: u16, timeout_ms: u32 },
    UdpOpen { port: u16 },
    UdpSend { socket: u32, address: u32, port: u16, data: &'a [u8] },
    UdpReceive { socket: u32 },
    TcpConnect { address: u32, port: u16, timeout_ms: u32 },
    TcpSend { socket: u32, data: &'a [u8] },
    TcpReceive { socket: u32, length: u32 },
    Close { socket: u32 },
    PolicySet { badge: u16, rules: List<Rule, 16>, seconds: u32, bytes: u64 },
    PolicyDrop { badge: u16 },
    PolicyUsage { badge: u16 },
    Interfaces,
}

/// Checks a received message against the schema (MC-2.4): method, major version, unused bits, capability kind, and
/// for buffer calls every length and value of a private copy of the request (MC-2.11). `cap` is the slot passed to
/// `recv`; an unexpected capability is dropped (MC-2.12). The `Call` is what the reply functions need.
/// The private copy is `scratch`, which the `bytes` of the request borrow.
pub fn decode<'a>(request: &Received, cap: usize, scratch: &'a mut [u8; REQUEST_MAX]) -> core::result::Result<(Request<'a>, Call), Reject> {
    let words = request.data;
    wire::header(request, cap, MAJOR)?;
    match words[0] & 0xFF {
        1 => {
            let (call, length) = wire::take_buffer(request, cap, 22, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Config, call))
        }
        2 => {
            wire::body(request, cap, [0xffffffff0000, 0xffffffff], CAP_KIND_NONE, false)?;
            Ok((Request::Ping { address: wire::field(&words, 0, 16, 32) as u32, timeout_ms: wire::field(&words, 1, 0, 32) as u32 }, Call::words(request, cap)))
        }
        3 => {
            let (call, length) = wire::take_buffer(request, cap, 4, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let name = <Text<253> as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let server = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let port = <u16 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let timeout_ms = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Resolve { name, server, port, timeout_ms }, call))
        }
        4 => {
            wire::body(request, cap, [0xffff0000, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::UdpOpen { port: wire::field(&words, 0, 16, 16) as u16 }, Call::words(request, cap)))
        }
        5 => {
            let (call, length) = wire::take_buffer(request, cap, 0, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let socket = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let address = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let port = <u16 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let data = codec::decode_bytes::<1472>(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::UdpSend { socket, address, port, data }, call))
        }
        6 => {
            let (call, length) = wire::take_buffer(request, cap, 1480, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let socket = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::UdpReceive { socket }, call))
        }
        7 => {
            wire::body(request, cap, [0xffffffffffff0000, 0xffffffff], CAP_KIND_NONE, false)?;
            Ok((Request::TcpConnect { address: wire::field(&words, 0, 16, 32) as u32, port: wire::field(&words, 0, 48, 16) as u16, timeout_ms: wire::field(&words, 1, 0, 32) as u32 }, Call::words(request, cap)))
        }
        8 => {
            let (call, length) = wire::take_buffer(request, cap, 4, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let socket = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let data = codec::decode_bytes::<4096>(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::TcpSend { socket, data }, call))
        }
        9 => {
            let (call, length) = wire::take_buffer(request, cap, 4098, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let socket = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let length = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::TcpReceive { socket, length }, call))
        }
        10 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::Close { socket: wire::field(&words, 0, 16, 32) as u32 }, Call::words(request, cap)))
        }
        11 => {
            let (call, length) = wire::take_buffer(request, cap, 0, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let badge = <u16 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let rules = <List<Rule, 16> as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let seconds = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let bytes = <u64 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::PolicySet { badge, rules, seconds, bytes }, call))
        }
        12 => {
            wire::body(request, cap, [0xffff0000, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::PolicyDrop { badge: wire::field(&words, 0, 16, 16) as u16 }, Call::words(request, cap)))
        }
        13 => {
            let (call, length) = wire::take_buffer(request, cap, 24, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let badge = <u16 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::PolicyUsage { badge }, call))
        }
        14 => {
            let (call, length) = wire::take_buffer(request, cap, 158, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Interfaces, call))
        }
        _ => { wire::discard(request, cap); Err(Reject::Invalid) }
    }
}

pub fn reply_config(call: Call, value: core::result::Result<&Config, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| value.encode(w))
}
pub fn reply_ping(call: Call, value: core::result::Result<u32, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [((value) as usize) << 16, 0])
}
pub fn reply_resolve(call: Call, value: core::result::Result<u32, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| value.encode(w))
}
pub fn reply_udp_open(call: Call, value: core::result::Result<u32, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [((value) as usize) << 16, 0])
}
pub fn reply_udp_send(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |_| Some(()))
}
pub fn reply_udp_receive(call: Call, value: core::result::Result<&Datagram, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| value.encode(w))
}
pub fn reply_tcp_connect(call: Call, value: core::result::Result<u32, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [((value) as usize) << 16, 0])
}
pub fn reply_tcp_send(call: Call, value: core::result::Result<u32, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| value.encode(w))
}
pub fn reply_tcp_receive(call: Call, value: core::result::Result<&[u8], Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| codec::encode_bytes::<4096>(value, w))
}
pub fn reply_close(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [0, 0])
}
pub fn reply_policy_set(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |_| Some(()))
}
pub fn reply_policy_drop(call: Call, value: core::result::Result<u32, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [((value) as usize) << 16, 0])
}
pub fn reply_policy_usage(call: Call, value: core::result::Result<&Usage, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| value.encode(w))
}
pub fn reply_interfaces(call: Call, value: core::result::Result<&[Interface], Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| codec::encode_slice::<Interface, 4>(value, w))
}