// Generated by scripts/mind_idl.py from idl/sysinfo.wit; do not edit.
//! System information from `sysmon` (MC-10.2): the kernel's STAT records and a history of load samples. Clients get
//! an endpoint from the shell at launch (SLOT_SYSINFO); `sysmon` holds the observe privilege and limits each client's
//! request rate.
#![allow(clippy::all, unused_imports, unused_mut, unused_variables)]
use crate::abi::*;
use crate::ipc::{Endpoint, Received};
use crate::mem::Pages;
use crate::sys::{Error as SysError, Result};
use super::codec::{self, List, Reader, Text, Wire, Writer};
use super::wire::{self, Call, Reject};

pub const PACKAGE: &str = "mind:sysinfo";
pub const VERSION: (u8, u8, u8) = (1, 0, 0);
const MAJOR: usize = 1;

/// Why a request failed.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[repr(u8)]
pub enum Error { #[default] Busy = 0, NotFound = 1, Unavailable = 2 }
impl Error {
    /// The case with wire code `code`; None for a code the interface does not define.
    pub fn from_code(code: usize) -> Option<Self> { match code { 0 => Some(Self::Busy), 1 => Some(Self::NotFound), 2 => Some(Self::Unavailable), _ => None } }
}
impl Wire for Error {
    const MAX: usize = 1;
    fn encode(&self, w: &mut Writer) -> Option<()> { (*self as u8).encode(w) }
    fn decode(r: &mut Reader) -> Option<Self> { Self::from_code(u8::decode(r)? as usize) }
}

/// A task (StatTask). `wait` is WAIT_* and `wait-on` the endpoint index, IRQ line or server PID it waits for;
/// `flags`: `mind::stat::TASK_SERVICE`, `TASK_SCREEN`, `TASK_FOCUS`.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Task { pub pid: u64, pub parent: u64, pub run_ns: u64, pub runs: u64, pub ticks: u64, pub calls: u64, pub sends: u64, pub receives: u64, pub started_ns: u64, pub image: u64, pub stack: u64, pub screen: u64, pub heap: u64, pub shared: u64, pub retained: u64, pub budget_ns: u64, pub period_ns: u64, pub wait_on: u32, pub heap_blocks: u32, pub caps: u32, pub quota_tasks: u16, pub used_tasks: u16, pub quota_endpoints: u16, pub used_endpoints: u16, pub name: Text<16>, pub wait: u8, pub cpu: u8, pub flags: u8, pub band: u8, pub throttled: bool }
impl Wire for Task {
    const MAX: usize = <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX + <u16 as Wire>::MAX + <u16 as Wire>::MAX + <u16 as Wire>::MAX + <u16 as Wire>::MAX + <Text<16> as Wire>::MAX + <u8 as Wire>::MAX + <u8 as Wire>::MAX + <u8 as Wire>::MAX + <u8 as Wire>::MAX + <bool as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.pid.encode(w)?; self.parent.encode(w)?; self.run_ns.encode(w)?; self.runs.encode(w)?; self.ticks.encode(w)?; self.calls.encode(w)?; self.sends.encode(w)?; self.receives.encode(w)?; self.started_ns.encode(w)?; self.image.encode(w)?; self.stack.encode(w)?; self.screen.encode(w)?; self.heap.encode(w)?; self.shared.encode(w)?; self.retained.encode(w)?; self.budget_ns.encode(w)?; self.period_ns.encode(w)?; self.wait_on.encode(w)?; self.heap_blocks.encode(w)?; self.caps.encode(w)?; self.quota_tasks.encode(w)?; self.used_tasks.encode(w)?; self.quota_endpoints.encode(w)?; self.used_endpoints.encode(w)?; self.name.encode(w)?; self.wait.encode(w)?; self.cpu.encode(w)?; self.flags.encode(w)?; self.band.encode(w)?; self.throttled.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { pid: Wire::decode(r)?, parent: Wire::decode(r)?, run_ns: Wire::decode(r)?, runs: Wire::decode(r)?, ticks: Wire::decode(r)?, calls: Wire::decode(r)?, sends: Wire::decode(r)?, receives: Wire::decode(r)?, started_ns: Wire::decode(r)?, image: Wire::decode(r)?, stack: Wire::decode(r)?, screen: Wire::decode(r)?, heap: Wire::decode(r)?, shared: Wire::decode(r)?, retained: Wire::decode(r)?, budget_ns: Wire::decode(r)?, period_ns: Wire::decode(r)?, wait_on: Wire::decode(r)?, heap_blocks: Wire::decode(r)?, caps: Wire::decode(r)?, quota_tasks: Wire::decode(r)?, used_tasks: Wire::decode(r)?, quota_endpoints: Wire::decode(r)?, used_endpoints: Wire::decode(r)?, name: Wire::decode(r)?, wait: Wire::decode(r)?, cpu: Wire::decode(r)?, flags: Wire::decode(r)?, band: Wire::decode(r)?, throttled: Wire::decode(r)? }) }
}

/// A CPU (StatCpu).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Cpu { pub busy_ns: u64, pub idle_ns: u64, pub ticks: u64, pub switches: u64, pub interrupts: u64, pub current: u64, pub apic: u32, pub online: bool }
impl Wire for Cpu {
    const MAX: usize = <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u32 as Wire>::MAX + <bool as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.busy_ns.encode(w)?; self.idle_ns.encode(w)?; self.ticks.encode(w)?; self.switches.encode(w)?; self.interrupts.encode(w)?; self.current.encode(w)?; self.apic.encode(w)?; self.online.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { busy_ns: Wire::decode(r)?, idle_ns: Wire::decode(r)?, ticks: Wire::decode(r)?, switches: Wire::decode(r)?, interrupts: Wire::decode(r)?, current: Wire::decode(r)?, apic: Wire::decode(r)?, online: Wire::decode(r)? }) }
}

/// Kernel memory by use (StatMemory, bytes).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Memory { pub arena: u64, pub used: u64, pub free: u64, pub images: u64, pub stacks: u64, pub task_pages: u64, pub screens: u64, pub heaps: u64, pub objects: u64, pub objects_limit: u64, pub dma: u64, pub dma_limit: u64, pub tasks: u32, pub endpoints: u32 }
impl Wire for Memory {
    const MAX: usize = <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.arena.encode(w)?; self.used.encode(w)?; self.free.encode(w)?; self.images.encode(w)?; self.stacks.encode(w)?; self.task_pages.encode(w)?; self.screens.encode(w)?; self.heaps.encode(w)?; self.objects.encode(w)?; self.objects_limit.encode(w)?; self.dma.encode(w)?; self.dma_limit.encode(w)?; self.tasks.encode(w)?; self.endpoints.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { arena: Wire::decode(r)?, used: Wire::decode(r)?, free: Wire::decode(r)?, images: Wire::decode(r)?, stacks: Wire::decode(r)?, task_pages: Wire::decode(r)?, screens: Wire::decode(r)?, heaps: Wire::decode(r)?, objects: Wire::decode(r)?, objects_limit: Wire::decode(r)?, dma: Wire::decode(r)?, dma_limit: Wire::decode(r)?, tasks: Wire::decode(r)?, endpoints: Wire::decode(r)? }) }
}

/// A physical range (StatPhys): UEFI memory type, or the platform layout from PHYS_PLATFORM on.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Range { pub start: u64, pub pages: u64, pub kind: u32, pub index: u32 }
impl Wire for Range {
    const MAX: usize = <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.start.encode(w)?; self.pages.encode(w)?; self.kind.encode(w)?; self.index.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { start: Wire::decode(r)?, pages: Wire::decode(r)?, kind: Wire::decode(r)?, index: Wire::decode(r)? }) }
}

/// A region of an address space (StatRegion: REGION_* kind and flags).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Region { pub start: u64, pub size: u64, pub kind: u32, pub flags: u32 }
impl Wire for Region {
    const MAX: usize = <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.start.encode(w)?; self.size.encode(w)?; self.kind.encode(w)?; self.flags.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { start: Wire::decode(r)?, size: Wire::decode(r)?, kind: Wire::decode(r)?, flags: Wire::decode(r)? }) }
}

/// A capability of a task (StatCap: no physical addresses; ports give their base and an IRQ its line in `rights`).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Capability { pub node: u64, pub parent: u64, pub size: u64, pub slot: u32, pub generation: u32, pub kind: u32, pub rights: u32, pub badge: u32 }
impl Wire for Capability {
    const MAX: usize = <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.node.encode(w)?; self.parent.encode(w)?; self.size.encode(w)?; self.slot.encode(w)?; self.generation.encode(w)?; self.kind.encode(w)?; self.rights.encode(w)?; self.badge.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { node: Wire::decode(r)?, parent: Wire::decode(r)?, size: Wire::decode(r)?, slot: Wire::decode(r)?, generation: Wire::decode(r)?, kind: Wire::decode(r)?, rights: Wire::decode(r)?, badge: Wire::decode(r)? }) }
}

/// An endpoint (StatEndpoint: the index is a label, not an authority).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct EndpointInfo { pub messages: u64, pub busy: u64, pub timeouts: u64, pub creator: u64, pub index: u32, pub receivers: u32, pub senders: u32, pub receiving: u32 }
impl Wire for EndpointInfo {
    const MAX: usize = <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.messages.encode(w)?; self.busy.encode(w)?; self.timeouts.encode(w)?; self.creator.encode(w)?; self.index.encode(w)?; self.receivers.encode(w)?; self.senders.encode(w)?; self.receiving.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { messages: Wire::decode(r)?, busy: Wire::decode(r)?, timeouts: Wire::decode(r)?, creator: Wire::decode(r)?, index: Wire::decode(r)?, receivers: Wire::decode(r)?, senders: Wire::decode(r)?, receiving: Wire::decode(r)? }) }
}

/// An interrupt line (StatIrq).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Irq { pub count: u64, pub holder: u64, pub line: u32, pub endpoint: u32, pub masked: bool }
impl Wire for Irq {
    const MAX: usize = <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX + <bool as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.count.encode(w)?; self.holder.encode(w)?; self.line.encode(w)?; self.endpoint.encode(w)?; self.masked.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { count: Wire::decode(r)?, holder: Wire::decode(r)?, line: Wire::decode(r)?, endpoint: Wire::decode(r)?, masked: Wire::decode(r)? }) }
}

/// A PCI function (StatDevice): BAR sizes, class, IRQ, the task holding it.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Device { pub bar0: u64, pub bar1: u64, pub bar2: u64, pub bar3: u64, pub bar4: u64, pub bar5: u64, pub holder: u64, pub class: u32, pub irq: u32 }
impl Wire for Device {
    const MAX: usize = <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.bar0.encode(w)?; self.bar1.encode(w)?; self.bar2.encode(w)?; self.bar3.encode(w)?; self.bar4.encode(w)?; self.bar5.encode(w)?; self.holder.encode(w)?; self.class.encode(w)?; self.irq.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { bar0: Wire::decode(r)?, bar1: Wire::decode(r)?, bar2: Wire::decode(r)?, bar3: Wire::decode(r)?, bar4: Wire::decode(r)?, bar5: Wire::decode(r)?, holder: Wire::decode(r)?, class: Wire::decode(r)?, irq: Wire::decode(r)? }) }
}

/// One sample of the load history: busy per mille of CPUs 0..3 and 4..7 (16 bits each), counts during the interval.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Sample { pub busy_low: u64, pub busy_high: u64, pub interrupts: u32, pub syscalls: u32, pub messages: u32, pub switches: u32, pub used_kib: u32, pub tasks: u8, pub runnable: u8 }
impl Wire for Sample {
    const MAX: usize = <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX + <u8 as Wire>::MAX + <u8 as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.busy_low.encode(w)?; self.busy_high.encode(w)?; self.interrupts.encode(w)?; self.syscalls.encode(w)?; self.messages.encode(w)?; self.switches.encode(w)?; self.used_kib.encode(w)?; self.tasks.encode(w)?; self.runnable.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { busy_low: Wire::decode(r)?, busy_high: Wire::decode(r)?, interrupts: Wire::decode(r)?, syscalls: Wire::decode(r)?, messages: Wire::decode(r)?, switches: Wire::decode(r)?, used_kib: Wire::decode(r)?, tasks: Wire::decode(r)?, runnable: Wire::decode(r)? }) }
}

/// Load averages (runnable tasks x 100) over 1, 5 and 15 minutes, uptime and sampling periods.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Load { pub one: u32, pub five: u32, pub fifteen: u32, pub uptime_ms: u64, pub fast_ms: u32, pub slow_ms: u32, pub fast_count: u32, pub slow_count: u32 }
impl Wire for Load {
    const MAX: usize = <u32 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX + <u64 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.one.encode(w)?; self.five.encode(w)?; self.fifteen.encode(w)?; self.uptime_ms.encode(w)?; self.fast_ms.encode(w)?; self.slow_ms.encode(w)?; self.fast_count.encode(w)?; self.slow_count.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { one: Wire::decode(r)?, five: Wire::decode(r)?, fifteen: Wire::decode(r)?, uptime_ms: Wire::decode(r)?, fast_ms: Wire::decode(r)?, slow_ms: Wire::decode(r)?, fast_count: Wire::decode(r)?, slow_count: Wire::decode(r)? }) }
}

pub fn tasks(endpoint: Endpoint) -> Result<core::result::Result<List<Task, 40>, Error>> {
    let mut buffer = Pages::new(8192).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 1 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 7162, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <List<Task, 40> as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

pub fn cpus(endpoint: Endpoint) -> Result<core::result::Result<List<Cpu, 8>, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 2 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 426, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <List<Cpu, 8> as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

pub fn memory(endpoint: Endpoint) -> Result<core::result::Result<Memory, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 3 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 104, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <Memory as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

pub fn physmap(endpoint: Endpoint) -> Result<core::result::Result<List<Range, 256>, Error>> {
    let mut buffer = Pages::new(8192).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 4 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 6146, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <List<Range, 256> as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// Address space of task `pid`.
pub fn vmap(endpoint: Endpoint, pid: u64) -> Result<core::result::Result<List<Region, 80>, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        pid.encode(&mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 5 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 1922, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <List<Region, 80> as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// Capabilities of task `pid`.
pub fn caps(endpoint: Endpoint, pid: u64) -> Result<core::result::Result<List<Capability, 64>, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        pid.encode(&mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 6 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 2818, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <List<Capability, 64> as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

pub fn endpoints(endpoint: Endpoint) -> Result<core::result::Result<List<EndpointInfo, 128>, Error>> {
    let mut buffer = Pages::new(8192).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 7 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 6146, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <List<EndpointInfo, 128> as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

pub fn irqs(endpoint: Endpoint) -> Result<core::result::Result<List<Irq, 16>, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 8 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 402, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <List<Irq, 16> as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

pub fn devices(endpoint: Endpoint) -> Result<core::result::Result<List<Device, 64>, Error>> {
    let mut buffer = Pages::new(8192).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 9 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 4098, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <List<Device, 64> as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// The last `count` samples, oldest first: every 100 ms (`slow` false, up to 300) or every second (up to 600); a reply
/// holds those from position `start` on, at most 150 (call again with a larger `start` for the rest).
pub fn history(endpoint: Endpoint, slow: bool, count: u16, start: u16) -> Result<core::result::Result<List<Sample, 150>, Error>> {
    let mut buffer = Pages::new(8192).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        slow.encode(&mut w).ok_or(SysError::Invalid)?;
        count.encode(&mut w).ok_or(SysError::Invalid)?;
        start.encode(&mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 10 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 5702, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <List<Sample, 150> as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

pub fn load(endpoint: Endpoint) -> Result<core::result::Result<Load, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 11 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 36, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <Load as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// A request to the `sysinfo` interface that passed the receiver's schema check.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Request {
    Tasks,
    Cpus,
    Memory,
    Physmap,
    Vmap { pid: u64 },
    Caps { pid: u64 },
    Endpoints,
    Irqs,
    Devices,
    History { slow: bool, count: u16, start: u16 },
    Load,
}

/// Checks a received message against the schema (MC-2.4): method, major version, unused bits, capability kind, and
/// for buffer calls every length and value of a private copy of the request (MC-2.11). `cap` is the slot passed to
/// `recv`; an unexpected capability is dropped (MC-2.12). The `Call` is what the reply functions need.
pub fn decode(request: &Received, cap: usize) -> core::result::Result<(Request, Call), Reject> {
    let words = request.data;
    wire::header(request, cap, MAJOR)?;
    match words[0] & 0xFF {
        1 => {
            let mut copy = [0u8; 1];
            let (call, length) = wire::take_buffer(request, cap, 7162, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Tasks, call))
        }
        2 => {
            let mut copy = [0u8; 1];
            let (call, length) = wire::take_buffer(request, cap, 426, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Cpus, call))
        }
        3 => {
            let mut copy = [0u8; 1];
            let (call, length) = wire::take_buffer(request, cap, 104, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Memory, call))
        }
        4 => {
            let mut copy = [0u8; 1];
            let (call, length) = wire::take_buffer(request, cap, 6146, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Physmap, call))
        }
        5 => {
            let mut copy = [0u8; 8];
            let (call, length) = wire::take_buffer(request, cap, 1922, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            let pid = <u64 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Vmap { pid }, call))
        }
        6 => {
            let mut copy = [0u8; 8];
            let (call, length) = wire::take_buffer(request, cap, 2818, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            let pid = <u64 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Caps { pid }, call))
        }
        7 => {
            let mut copy = [0u8; 1];
            let (call, length) = wire::take_buffer(request, cap, 6146, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Endpoints, call))
        }
        8 => {
            let mut copy = [0u8; 1];
            let (call, length) = wire::take_buffer(request, cap, 402, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Irqs, call))
        }
        9 => {
            let mut copy = [0u8; 1];
            let (call, length) = wire::take_buffer(request, cap, 4098, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Devices, call))
        }
        10 => {
            let mut copy = [0u8; 5];
            let (call, length) = wire::take_buffer(request, cap, 5702, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            let slow = <bool as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let count = <u16 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let start = <u16 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::History { slow, count, start }, call))
        }
        11 => {
            let mut copy = [0u8; 1];
            let (call, length) = wire::take_buffer(request, cap, 36, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Load, call))
        }
        _ => { wire::discard(request, cap); Err(Reject::Invalid) }
    }
}

pub fn reply_tasks(call: Call, value: core::result::Result<&[Task], Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| codec::encode_slice::<Task, 40>(value, w))
}
pub fn reply_cpus(call: Call, value: core::result::Result<&[Cpu], Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| codec::encode_slice::<Cpu, 8>(value, w))
}
pub fn reply_memory(call: Call, value: core::result::Result<&Memory, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| value.encode(w))
}
pub fn reply_physmap(call: Call, value: core::result::Result<&[Range], Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| codec::encode_slice::<Range, 256>(value, w))
}
pub fn reply_vmap(call: Call, value: core::result::Result<&[Region], Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| codec::encode_slice::<Region, 80>(value, w))
}
pub fn reply_caps(call: Call, value: core::result::Result<&[Capability], Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| codec::encode_slice::<Capability, 64>(value, w))
}
pub fn reply_endpoints(call: Call, value: core::result::Result<&[EndpointInfo], Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| codec::encode_slice::<EndpointInfo, 128>(value, w))
}
pub fn reply_irqs(call: Call, value: core::result::Result<&[Irq], Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| codec::encode_slice::<Irq, 16>(value, w))
}
pub fn reply_devices(call: Call, value: core::result::Result<&[Device], Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| codec::encode_slice::<Device, 64>(value, w))
}
pub fn reply_history(call: Call, value: core::result::Result<&[Sample], Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| codec::encode_slice::<Sample, 150>(value, w))
}
pub fn reply_load(call: Call, value: core::result::Result<&Load, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| value.encode(w))
}