// Generated by scripts/mind_idl.py from idl/tls.wit; do not edit.
//! TLS service (`tls`, issue 103, Appendix B.6): TLS 1.3 client sessions over the client's own network flow. A client
//! lends its network stack capability (`attach`), so the network policy that applies to the client applies to its TLS
//! connections too; the service holds no network access of its own. Server certificates are verified against the root
//! store `tlsroots.pem` on the boot disk. With `client-certificate`, the device certificate is offered when a server
//! asks for one and the key service signs the handshake: the TLS service never sees the private key. A session belongs
//! to the process that attached it; the service runs one handshake at a time. 1.1 adds `connect-pinned`: a server known
//! by its key alone, such as the update server (351-NET-0002).
#![allow(clippy::all, unused_imports, unused_mut, unused_variables)]
use crate::abi::*;
use crate::ipc::{Endpoint, Received};
use crate::mem::Pages;
use crate::sys::{Error as SysError, Result};
use super::codec::{self, List, Reader, Text, Wire, Writer};
use super::wire::{self, Call, Reject};

pub const PACKAGE: &str = "mind:tls";
pub const VERSION: (u8, u8, u8) = (1, 1, 0);
const MAJOR: usize = 1;

/// Why a request failed. `certificate`: the server certificate is not valid for the name or not trusted;
/// `handshake`: the handshake failed otherwise; `no-entropy`: the processor has no RDRAND (the service fails
/// closed); `no-roots`: no usable root certificate.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[repr(u8)]
pub enum Error { #[default] NoNetwork = 0, Refused = 1, Timeout = 2, Closed = 3, Again = 4, Invalid = 5, Limit = 6, NotFound = 7, Denied = 8, Certificate = 9, Handshake = 10, NoEntropy = 11, NoRoots = 12 }
impl Error {
    /// The case with wire code `code`; None for a code the interface does not define.
    pub fn from_code(code: usize) -> Option<Self> { match code { 0 => Some(Self::NoNetwork), 1 => Some(Self::Refused), 2 => Some(Self::Timeout), 3 => Some(Self::Closed), 4 => Some(Self::Again), 5 => Some(Self::Invalid), 6 => Some(Self::Limit), 7 => Some(Self::NotFound), 8 => Some(Self::Denied), 9 => Some(Self::Certificate), 10 => Some(Self::Handshake), 11 => Some(Self::NoEntropy), 12 => Some(Self::NoRoots), _ => None } }
}
impl Wire for Error {
    const MAX: usize = 1;
    fn encode(&self, w: &mut Writer) -> Option<()> { (*self as u8).encode(w) }
    fn decode(r: &mut Reader) -> Option<Self> { Self::from_code(u8::decode(r)? as usize) }
}

/// An established session: the cipher suite and key exchange group (IANA numbers), whether the device certificate
/// was sent.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Peer { pub suite: u16, pub group: u16, pub client_certificate: bool }
impl Wire for Peer {
    const MAX: usize = <u16 as Wire>::MAX + <u16 as Wire>::MAX + <bool as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.suite.encode(w)?; self.group.encode(w)?; self.client_certificate.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { suite: Wire::decode(r)?, group: Wire::decode(r)?, client_certificate: Wire::decode(r)? }) }
}

/// A new session on the client's network flow (its socket client, idl/socket.wit).
pub fn attach(endpoint: Endpoint, flow: usize) -> Result<core::result::Result<u32, Error>> {
    let words = [1 | MAJOR << 8, 0];
    let reply = wire::call(endpoint, words, Some((flow, false)))?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let _ = wire::check_reply(&reply, [0xffffffff0000, 0x0], false)?;
    Ok(Ok(wire::field(&reply, 0, 16, 32) as u32))
}

/// TCP to `address`:`port`, then the TLS 1.3 handshake verifying the server for `name` (a DNS name or an IPv4
/// address in dotted form).
pub fn connect(endpoint: Endpoint, session: u32, name: &str, address: u32, port: u16, client_certificate: bool, timeout_ms: u32) -> Result<core::result::Result<Peer, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        session.encode(&mut w).ok_or(SysError::Invalid)?;
        codec::encode_str::<253>(name, &mut w).ok_or(SysError::Invalid)?;
        address.encode(&mut w).ok_or(SysError::Invalid)?;
        port.encode(&mut w).ok_or(SysError::Invalid)?;
        client_certificate.encode(&mut w).ok_or(SysError::Invalid)?;
        timeout_ms.encode(&mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 2 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 5, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <Peer as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// Encrypts and sends `data`; returns how many bytes were taken.
pub fn send(endpoint: Endpoint, session: u32, data: &[u8]) -> Result<core::result::Result<u32, Error>> {
    let mut buffer = Pages::new(8192).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        session.encode(&mut w).ok_or(SysError::Invalid)?;
        codec::encode_bytes::<4096>(data, &mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 3 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 4, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <u32 as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// Up to `length` decrypted bytes. Error again: nothing yet; closed: the peer closed and everything was read.
pub fn receive(endpoint: Endpoint, session: u32, length: u32, out: &mut [u8]) -> Result<core::result::Result<usize, Error>> {
    let mut buffer = Pages::new(8192).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        session.encode(&mut w).ok_or(SysError::Invalid)?;
        length.encode(&mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 4 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 4098, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); let data = codec::decode_bytes::<4096>(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)?; out.get_mut(..data.len()).ok_or(SysError::Invalid)?.copy_from_slice(data); data.len() }))
}

/// Sends close_notify, closes the connection and frees the session and the lent flow.
pub fn close(endpoint: Endpoint, session: u32) -> Result<core::result::Result<(), Error>> {
    let words = [5 | MAJOR << 8 | ((session) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, None)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    wire::check_reply(&reply, [0, 0], false)?;
    Ok(Ok(()))
}

/// The device certificate (DER), from the key service.
pub fn certificate(endpoint: Endpoint, out: &mut [u8]) -> Result<core::result::Result<usize, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 6 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 514, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); let data = codec::decode_bytes::<512>(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)?; out.get_mut(..data.len()).ok_or(SysError::Invalid)?.copy_from_slice(data); data.len() }))
}

/// As `connect`, the server verified by its key alone (1.1): the SHA-256 of its certificate's SubjectPublicKeyInfo
/// must be `pin` (32 bytes), or the connection is refused (`certificate`). No root, name or validity period is
/// checked; the handshake's signature by that key is. `name` is sent as the server name.
pub fn connect_pinned(endpoint: Endpoint, session: u32, name: &str, address: u32, port: u16, pin: &[u8], timeout_ms: u32) -> Result<core::result::Result<Peer, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        session.encode(&mut w).ok_or(SysError::Invalid)?;
        codec::encode_str::<253>(name, &mut w).ok_or(SysError::Invalid)?;
        address.encode(&mut w).ok_or(SysError::Invalid)?;
        port.encode(&mut w).ok_or(SysError::Invalid)?;
        codec::encode_bytes::<32>(pin, &mut w).ok_or(SysError::Invalid)?;
        timeout_ms.encode(&mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 7 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 5, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <Peer as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// Size of the scratch buffer `decode` copies a request into (the largest request).
pub const REQUEST_MAX: usize = 4102;

/// A request to the `tls` interface that passed the receiver's schema check.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Request<'a> {
    Attach { flow: usize },
    Connect { session: u32, name: Text<253>, address: u32, port: u16, client_certificate: bool, timeout_ms: u32 },
    Send { session: u32, data: &'a [u8] },
    Receive { session: u32, length: u32 },
    Close { session: u32 },
    Certificate,
    ConnectPinned { session: u32, name: Text<253>, address: u32, port: u16, pin: &'a [u8], timeout_ms: u32 },
}

/// Checks a received message against the schema (MC-2.4): method, major version, unused bits, capability kind, and
/// for buffer calls every length and value of a private copy of the request (MC-2.11). `cap` is the slot passed to
/// `recv`; an unexpected capability is dropped (MC-2.12). The `Call` is what the reply functions need.
/// The private copy is `scratch`, which the `bytes` of the request borrow.
pub fn decode<'a>(request: &Received, cap: usize, scratch: &'a mut [u8; REQUEST_MAX]) -> core::result::Result<(Request<'a>, Call), Reject> {
    let words = request.data;
    wire::header(request, cap, MAJOR)?;
    match words[0] & 0xFF {
        1 => {
            wire::body(request, cap, [0x0, 0x0], CAP_KIND_ENDPOINT, true)?;
            Ok((Request::Attach { flow: cap }, Call::words(request, cap)))
        }
        2 => {
            let (call, length) = wire::take_buffer(request, cap, 5, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let session = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let name = <Text<253> as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let address = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let port = <u16 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let client_certificate = <bool as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let timeout_ms = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Connect { session, name, address, port, client_certificate, timeout_ms }, call))
        }
        3 => {
            let (call, length) = wire::take_buffer(request, cap, 4, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let session = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let data = codec::decode_bytes::<4096>(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Send { session, data }, call))
        }
        4 => {
            let (call, length) = wire::take_buffer(request, cap, 4098, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let session = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let length = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Receive { session, length }, call))
        }
        5 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::Close { session: wire::field(&words, 0, 16, 32) as u32 }, Call::words(request, cap)))
        }
        6 => {
            let (call, length) = wire::take_buffer(request, cap, 514, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Certificate, call))
        }
        7 => {
            let (call, length) = wire::take_buffer(request, cap, 5, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let session = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let name = <Text<253> as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let address = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let port = <u16 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let pin = codec::decode_bytes::<32>(&mut r).ok_or(Reject::Invalid)?;
            let timeout_ms = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::ConnectPinned { session, name, address, port, pin, timeout_ms }, call))
        }
        _ => { wire::discard(request, cap); Err(Reject::Invalid) }
    }
}

pub fn reply_attach(call: Call, value: core::result::Result<u32, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [((value) as usize) << 16, 0])
}
pub fn reply_connect(call: Call, value: core::result::Result<&Peer, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| value.encode(w))
}
pub fn reply_send(call: Call, value: core::result::Result<u32, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| value.encode(w))
}
pub fn reply_receive(call: Call, value: core::result::Result<&[u8], Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| codec::encode_bytes::<4096>(value, w))
}
pub fn reply_close(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [0, 0])
}
pub fn reply_certificate(call: Call, value: core::result::Result<&[u8], Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| codec::encode_bytes::<512>(value, w))
}
pub fn reply_connect_pinned(call: Call, value: core::result::Result<&Peer, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| value.encode(w))
}