// Generated by scripts/mind_idl.py from idl/tpm.wit; do not edit.
//! TPM service (`tpm`, 351-DRV-0015, MC-11.9): the only holder of the TPM 2.0's registers (CRB or FIFO), which `init`
//! gives it from the firmware's tables. It seals secrets to this TPM and unseals them for the client with the seal
//! badge (the key service); no call sends a raw command. A sealed blob opens only in the TPM that sealed it: the TPM
//! derives its storage key from its own seed. There is no policy on the boot state yet: whoever holds the seal badge
//! on this machine can unseal. Every seal, unseal and refusal is logged with the client's PID.
#![allow(clippy::all, unused_imports, unused_mut, unused_variables)]
use crate::abi::*;
use crate::ipc::{Endpoint, Received};
use crate::mem::Pages;
use crate::sys::{Error as SysError, Result};
use super::codec::{self, List, Reader, Text, Wire, Writer};
use super::wire::{self, Call, Reject};

pub const PACKAGE: &str = "mind:tpm";
pub const VERSION: (u8, u8, u8) = (1, 0, 0);
const MAJOR: usize = 1;

/// `no-tpm`: the machine has none; `rights`: the client's badge does not allow the call; `invalid`: a secret or
/// blob of the wrong size or form; `refused`: the TPM refused (a blob another TPM sealed, or an error it logged).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[repr(u8)]
pub enum Error { #[default] NoTpm = 0, Rights = 1, Invalid = 2, Refused = 3 }
impl Error {
    /// The case with wire code `code`; None for a code the interface does not define.
    pub fn from_code(code: usize) -> Option<Self> { match code { 0 => Some(Self::NoTpm), 1 => Some(Self::Rights), 2 => Some(Self::Invalid), 3 => Some(Self::Refused), _ => None } }
}
impl Wire for Error {
    const MAX: usize = 1;
    fn encode(&self, w: &mut Writer) -> Option<()> { (*self as u8).encode(w) }
    fn decode(r: &mut Reader) -> Option<Self> { Self::from_code(u8::decode(r)? as usize) }
}

/// The TPM: its manufacturer (four ASCII letters, as TPM_PT_MANUFACTURER gives them) and whether its interface is
/// the CRB (else the FIFO).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Info { pub manufacturer: u32, pub crb: bool }
impl Wire for Info {
    const MAX: usize = <u32 as Wire>::MAX + <bool as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.manufacturer.encode(w)?; self.crb.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { manufacturer: Wire::decode(r)?, crb: Wire::decode(r)? }) }
}

/// Any client.
pub fn info(endpoint: Endpoint) -> Result<core::result::Result<Info, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 1 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 5, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <Info as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// Seals `secret` (1 to 128 bytes) to this TPM; the blob to keep (seal badge only).
pub fn seal(endpoint: Endpoint, secret: &[u8], out: &mut [u8]) -> Result<core::result::Result<usize, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        codec::encode_bytes::<128>(secret, &mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 2 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 1026, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); let data = codec::decode_bytes::<1024>(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)?; out.get_mut(..data.len()).ok_or(SysError::Invalid)?.copy_from_slice(data); data.len() }))
}

/// The secret of a blob this TPM sealed (seal badge only).
pub fn unseal(endpoint: Endpoint, blob: &[u8], out: &mut [u8]) -> Result<core::result::Result<usize, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        codec::encode_bytes::<1024>(blob, &mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 3 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 130, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); let data = codec::decode_bytes::<128>(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)?; out.get_mut(..data.len()).ok_or(SysError::Invalid)?.copy_from_slice(data); data.len() }))
}

/// Size of the scratch buffer `decode` copies a request into (the largest request).
pub const REQUEST_MAX: usize = 1026;

/// A request to the `tpm` interface that passed the receiver's schema check.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Request<'a> {
    Info,
    Seal { secret: &'a [u8] },
    Unseal { blob: &'a [u8] },
}

/// Checks a received message against the schema (MC-2.4): method, major version, unused bits, capability kind, and
/// for buffer calls every length and value of a private copy of the request (MC-2.11). `cap` is the slot passed to
/// `recv`; an unexpected capability is dropped (MC-2.12). The `Call` is what the reply functions need.
/// The private copy is `scratch`, which the `bytes` of the request borrow.
pub fn decode<'a>(request: &Received, cap: usize, scratch: &'a mut [u8; REQUEST_MAX]) -> core::result::Result<(Request<'a>, Call), Reject> {
    let words = request.data;
    wire::header(request, cap, MAJOR)?;
    match words[0] & 0xFF {
        1 => {
            let (call, length) = wire::take_buffer(request, cap, 5, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Info, call))
        }
        2 => {
            let (call, length) = wire::take_buffer(request, cap, 1026, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let secret = codec::decode_bytes::<128>(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Seal { secret }, call))
        }
        3 => {
            let (call, length) = wire::take_buffer(request, cap, 130, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let blob = codec::decode_bytes::<1024>(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Unseal { blob }, call))
        }
        _ => { wire::discard(request, cap); Err(Reject::Invalid) }
    }
}

pub fn reply_info(call: Call, value: core::result::Result<&Info, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| value.encode(w))
}
pub fn reply_seal(call: Call, value: core::result::Result<&[u8], Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| codec::encode_bytes::<1024>(value, w))
}
pub fn reply_unseal(call: Call, value: core::result::Result<&[u8], Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| codec::encode_bytes::<128>(value, w))
}