// Generated by scripts/mind_idl.py from idl/tts.wit; do not edit.
//! Speech synthesis (Russian and Latin script), streamed to the audio gateway.
#![allow(clippy::all, unused_imports, unused_mut, unused_variables)]
use crate::abi::*;
use crate::ipc::{Endpoint, Received};
use crate::mem::Pages;
use crate::sys::{Error, Result};
use super::codec::{self, List, Reader, Text, Wire, Writer};
use super::wire::{self, Call, Reject};

pub const PACKAGE: &str = "mind:tts";
pub const VERSION: (u8, u8, u8) = (1, 0, 0);
const MAJOR: usize = 1;

/// Speaks `text` with `pitch` (Hz, 0: 112) and `rate` (%, 0: 100); returns the speech duration in ms once it is
/// queued. Error not-found without an audio device, invalid for empty text.
pub fn say(endpoint: Endpoint, text: &str, pitch: u16, rate: u16) -> Result<u32> {
    let mut buffer = Pages::new(4096).ok_or(Error::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        codec::encode_str::<4000>(text, &mut w).ok_or(Error::Invalid)?;
        pitch.encode(&mut w).ok_or(Error::Invalid)?;
        rate.encode(&mut w).ok_or(Error::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 1 | MAJOR << 8, &buffer, length)?;
    let length = wire::buffer_reply(&reply, 4, false, true)?;
    let length = length.ok_or(Error::Invalid)?;
    Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <u32 as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(Error::Invalid)? })
}

/// A request to the `tts` interface that passed the receiver's schema check.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Request {
    Say { text: Text<4000>, pitch: u16, rate: u16 },
}

/// Checks a received message against the schema (MC-2.4): method, major version, unused bits, capability kind, and
/// for buffer calls every length and value of a private copy of the request (MC-2.11). `cap` is the slot passed to
/// `recv`; an unexpected capability is dropped (MC-2.12). The `Call` is what the reply functions need.
pub fn decode(request: &Received, cap: usize) -> core::result::Result<(Request, Call), Reject> {
    let words = request.data;
    wire::header(request, cap, MAJOR)?;
    match words[0] & 0xFF {
        1 => {
            let mut copy = [0u8; 4006];
            let (call, length) = wire::take_buffer(request, cap, 4, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            let text = <Text<4000> as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let pitch = <u16 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let rate = <u16 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Say { text, pitch, rate }, call))
        }
        _ => { wire::discard(request, cap); Err(Reject::Invalid) }
    }
}

pub fn reply_say(call: Call, value: Result<u32>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_error(call, error) };
    wire::reply_buffer(call, |w| value.encode(w))
}