// Generated by scripts/mind_idl.py from idl/update.wit; do not edit.
//! The updater (`updater`, 351-UPD-0007, docs/update/updater.md): turns a published release into a staged, verified
//! slot, and nothing more (MC-9.2–9.4, MC-3.11). It checks a channel's signature with the release key built into it,
//! a manifest's with the boot key, and every file it stages by size and SHA-256, before a boot record names the slot.
//! The parser service reads the metadata (MC-11.11). The source, the channel and what the updater does by itself are
//! in `update.txt` on the boot volume. A request runs to its end before the next one is read.
#![allow(clippy::all, unused_imports, unused_mut, unused_variables)]
use crate::abi::*;
use crate::ipc::{Endpoint, Received};
use crate::mem::Pages;
use crate::sys::{Error as SysError, Result};
use super::codec::{self, List, Reader, Text, Wire, Writer};
use super::wire::{self, Call, Reject};

pub const PACKAGE: &str = "mind:update";
pub const VERSION: (u8, u8, u8) = (1, 0, 0);
const MAJOR: usize = 1;

/// Why a request failed. `no-source`: update.txt names no source; `no-slot`: the system did not boot from a slot;
/// `trial`: the running slot is on trial, so the other one is its fallback and stays as it is; `network`: the
/// source did not answer, or a transfer failed after its tries; `missing`: the source has no such file, or the
/// channel no manifest for this architecture; `malformed`: the parser refused the metadata, or its answer does not
/// make the bytes; `signature`: a channel or manifest not signed by its key; `expired`: the channel's expiry has
/// passed, or the clock cannot be read; `older`: the channel names the running version or an older one; `digest`:
/// a file not as its manifest lists it; `write`: the slot or a boot record could not be written; `not-staged`: no
/// verified newer release in the other slot; `no-fallback`: no slot to roll back to, or its version is not known or
/// is below the minimum; `denied`: init refused the restart; `no-parser`: the parser service did not answer.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[repr(u8)]
pub enum Error { #[default] NoSource = 0, NoSlot = 1, Trial = 2, Network = 3, Missing = 4, Malformed = 5, Signature = 6, Expired = 7, Older = 8, Digest = 9, Write = 10, NotStaged = 11, NoFallback = 12, Denied = 13, NoParser = 14 }
impl Error {
    /// The case with wire code `code`; None for a code the interface does not define.
    pub fn from_code(code: usize) -> Option<Self> { match code { 0 => Some(Self::NoSource), 1 => Some(Self::NoSlot), 2 => Some(Self::Trial), 3 => Some(Self::Network), 4 => Some(Self::Missing), 5 => Some(Self::Malformed), 6 => Some(Self::Signature), 7 => Some(Self::Expired), 8 => Some(Self::Older), 9 => Some(Self::Digest), 10 => Some(Self::Write), 11 => Some(Self::NotStaged), 12 => Some(Self::NoFallback), 13 => Some(Self::Denied), 14 => Some(Self::NoParser), _ => None } }
}
impl Wire for Error {
    const MAX: usize = 1;
    fn encode(&self, w: &mut Writer) -> Option<()> { (*self as u8).encode(w) }
    fn decode(r: &mut Reader) -> Option<Self> { Self::from_code(u8::decode(r)? as usize) }
}

/// What a channel offers: its name, latest version, minimum and expiry, and the running version (0: not known).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Offer { pub channel: Text<32>, pub version: u64, pub minimum: u64, pub expires: Text<20>, pub running: u64 }
impl Wire for Offer {
    const MAX: usize = <Text<32> as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <Text<20> as Wire>::MAX + <u64 as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.channel.encode(w)?; self.version.encode(w)?; self.minimum.encode(w)?; self.expires.encode(w)?; self.running.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { channel: Wire::decode(r)?, version: Wire::decode(r)?, minimum: Wire::decode(r)?, expires: Wire::decode(r)?, running: Wire::decode(r)? }) }
}

/// The updater's view: the running slot (`A`, `B`, or 0 when the system booted from the volume's root), whether it
/// runs on trial, its version (0: not known); the slot the newer boot record names (0: none) and whether that
/// record is confirmed; the version staged in the other slot (0: none); the last failure (empty: none).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct State { pub slot: u8, pub trial: bool, pub running: u64, pub recorded: u8, pub confirmed: bool, pub staged: u64, pub failure: Text<64> }
impl Wire for State {
    const MAX: usize = <u8 as Wire>::MAX + <bool as Wire>::MAX + <u64 as Wire>::MAX + <u8 as Wire>::MAX + <bool as Wire>::MAX + <u64 as Wire>::MAX + <Text<64> as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.slot.encode(w)?; self.trial.encode(w)?; self.running.encode(w)?; self.recorded.encode(w)?; self.confirmed.encode(w)?; self.staged.encode(w)?; self.failure.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { slot: Wire::decode(r)?, trial: Wire::decode(r)?, running: Wire::decode(r)?, recorded: Wire::decode(r)?, confirmed: Wire::decode(r)?, staged: Wire::decode(r)?, failure: Wire::decode(r)? }) }
}

/// Reads the channel and checks its signature, its form and its expiry. A version not above the running one is
/// `older`.
pub fn check(endpoint: Endpoint) -> Result<core::result::Result<Offer, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 1 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 80, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <Offer as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// Checks, then stages the newer release in the other slot: every boot file its manifest lists, resumed where a
/// partial file ends and checked by size and SHA-256, then the manifest, its signature and the channel. Returns the
/// version staged.
pub fn fetch(endpoint: Endpoint) -> Result<core::result::Result<u64, Error>> {
    let words = [2 | MAJOR << 8, 0];
    let reply = wire::call(endpoint, words, None)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let _ = wire::check_reply(&reply, [0x0, 0xffffffffffffffff], false)?;
    Ok(Ok(wire::field(&reply, 1, 0, 64) as u64))
}

/// Checks the other slot as the bootloader will, writes the boot record that boots it on trial with `tries` (1 to
/// 9), falling back to the running slot, and asks init to restart the machine.
pub fn apply(endpoint: Endpoint, tries: u8) -> Result<core::result::Result<(), Error>> {
    let words = [3 | MAJOR << 8 | ((tries) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, None)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    wire::check_reply(&reply, [0, 0], false)?;
    Ok(Ok(()))
}

/// Writes the boot record that boots the other slot on trial, falling back to the running one, if the channel kept
/// there shows a version not below the minimum the updater knows; then asks init to restart the machine.
pub fn rollback(endpoint: Endpoint) -> Result<core::result::Result<(), Error>> {
    let words = [4 | MAJOR << 8, 0];
    let reply = wire::call(endpoint, words, None)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    wire::check_reply(&reply, [0, 0], false)?;
    Ok(Ok(()))
}

/// The updater's view (above).
pub fn status(endpoint: Endpoint) -> Result<State> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 5 | MAJOR << 8, &buffer, length)?;
    let length = wire::buffer_reply(&reply, 86, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <State as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? })
}

/// A request to the `update` interface that passed the receiver's schema check.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Request {
    Check,
    Fetch,
    Apply { tries: u8 },
    Rollback,
    Status,
}

/// Checks a received message against the schema (MC-2.4): method, major version, unused bits, capability kind, and
/// for buffer calls every length and value of a private copy of the request (MC-2.11). `cap` is the slot passed to
/// `recv`; an unexpected capability is dropped (MC-2.12). The `Call` is what the reply functions need.
pub fn decode(request: &Received, cap: usize) -> core::result::Result<(Request, Call), Reject> {
    let words = request.data;
    wire::header(request, cap, MAJOR)?;
    match words[0] & 0xFF {
        1 => {
            let mut copy = [0u8; 1];
            let (call, length) = wire::take_buffer(request, cap, 80, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Check, call))
        }
        2 => {
            wire::body(request, cap, [0x0, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::Fetch, Call::words(request, cap)))
        }
        3 => {
            wire::body(request, cap, [0xff0000, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::Apply { tries: wire::field(&words, 0, 16, 8) as u8 }, Call::words(request, cap)))
        }
        4 => {
            wire::body(request, cap, [0x0, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::Rollback, Call::words(request, cap)))
        }
        5 => {
            let mut copy = [0u8; 1];
            let (call, length) = wire::take_buffer(request, cap, 86, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Status, call))
        }
        _ => { wire::discard(request, cap); Err(Reject::Invalid) }
    }
}

pub fn reply_check(call: Call, value: core::result::Result<&Offer, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| value.encode(w))
}
pub fn reply_fetch(call: Call, value: core::result::Result<u64, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [0, ((value) as usize) << 0])
}
pub fn reply_apply(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [0, 0])
}
pub fn reply_rollback(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [0, 0])
}
pub fn reply_status(call: Call, value: &State) -> Result<()> {
    wire::reply_buffer(call, |w| value.encode(w))
}