// Generated by scripts/mind_idl.py from idl/usb.wit; do not edit.
//! The USB host controller driver `usb_host` and its class drivers (issue 164): `usb_host` owns the xHCI controller,
//! enumerates devices (through hubs) and hands each interface to one class driver; `usb_hid` and `usb_storage` are its
//! clients. A client's badge names the device class it may claim (`mind::usb::BADGE_HID`, `BADGE_STORAGE`), so a class
//! driver reaches only its own interfaces (MC-3.3). Data travel through the client's buffer, lent with `attach`.
#![allow(clippy::all, unused_imports, unused_mut, unused_variables)]
use crate::abi::*;
use crate::ipc::{Endpoint, Received};
use crate::mem::Pages;
use crate::sys::{Error, Result};
use super::codec::{self, List, Reader, Text, Wire, Writer};
use super::wire::{self, Call, Reject};

pub const PACKAGE: &str = "mind:usb";
pub const VERSION: (u8, u8, u8) = (1, 0, 0);
const MAJOR: usize = 1;

/// Lends the client's transfer buffer (at least `mind::usb::BUFFER` bytes) to this host driver instance. A restarted
/// instance has none: every other call then fails with not-found and the client attaches again.
pub fn attach(endpoint: Endpoint, buffer: usize) -> Result<()> {
    let words = [1 | MAJOR << 8, 0];
    let reply = wire::call(endpoint, words, Some((buffer, false)))?;
    wire::check_error(&reply)?;
    wire::check_reply(&reply, [0, 0], false).map(drop)
}

/// Claims the next interface of the client's class that no client holds; returns its handle and writes its
/// description (`mind::usb::Interface`) at the buffer's start. Errors: not-found, none now (a device may come later);
/// invalid, no buffer is attached to this instance (it was restarted): attach, then claim again.
pub fn claim(endpoint: Endpoint) -> Result<u32> {
    let words = [2 | MAJOR << 8, 0];
    let reply = wire::call(endpoint, words, None)?;
    wire::check_error(&reply)?;
    let _ = wire::check_reply(&reply, [0xffffffff0000, 0x0], false)?;
    Ok(wire::field(&reply, 0, 16, 32) as u32)
}

/// Gives a claimed interface back.
pub fn release(endpoint: Endpoint, handle: u32) -> Result<()> {
    let words = [3 | MAJOR << 8 | ((handle) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, None)?;
    wire::check_error(&reply)?;
    wire::check_reply(&reply, [0, 0], false).map(drop)
}

/// A control transfer on the device's endpoint 0; the data stage (up to 4096 bytes) is at the buffer's start.
/// Returns the bytes transferred. Error not-found: the device is gone or the handle is not the client's.
pub fn control(endpoint: Endpoint, handle: u32, request_type: u8, request: u8, value: u16, index: u16, length: u16) -> Result<u16> {
    let words = [4 | MAJOR << 8 | ((handle) as usize) << 16 | ((request_type) as usize) << 48 | ((request) as usize) << 56, ((value) as usize) << 0 | ((index) as usize) << 16 | ((length) as usize) << 32];
    let reply = wire::call(endpoint, words, None)?;
    wire::check_error(&reply)?;
    let _ = wire::check_reply(&reply, [0xffff0000, 0x0], false)?;
    Ok(wire::field(&reply, 0, 16, 16) as u16)
}

/// A bulk transfer on the endpoint with address `address` (bit 7 set for IN) of the claimed interface, `length` bytes
/// (up to 64 KiB) at `offset` in the buffer. Returns the bytes transferred.
pub fn bulk(endpoint: Endpoint, handle: u32, address: u8, offset: u32, length: u32) -> Result<u32> {
    let words = [5 | MAJOR << 8 | ((handle) as usize) << 16 | ((address) as usize) << 48, ((offset) as usize) << 0 | ((length) as usize) << 32];
    let reply = wire::call(endpoint, words, None)?;
    wire::check_error(&reply)?;
    let _ = wire::check_reply(&reply, [0xffffffff0000, 0x0], false)?;
    Ok(wire::field(&reply, 0, 16, 32) as u32)
}

/// The reports received on the interrupt IN endpoint with address `address` since the last call, written at the buffer's start as
/// a length byte and the report each; returns their count. The first call starts polling the endpoint.
pub fn reports(endpoint: Endpoint, handle: u32, address: u8) -> Result<u16> {
    let words = [6 | MAJOR << 8 | ((handle) as usize) << 16 | ((address) as usize) << 48, 0];
    let reply = wire::call(endpoint, words, None)?;
    wire::check_error(&reply)?;
    let _ = wire::check_reply(&reply, [0xffff0000, 0x0], false)?;
    Ok(wire::field(&reply, 0, 16, 16) as u16)
}

/// A request to the `usb` interface that passed the receiver's schema check.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Request {
    Attach { buffer: usize },
    Claim,
    Release { handle: u32 },
    Control { handle: u32, request_type: u8, request: u8, value: u16, index: u16, length: u16 },
    Bulk { handle: u32, address: u8, offset: u32, length: u32 },
    Reports { handle: u32, address: u8 },
}

/// Checks a received message against the schema (MC-2.4): method, major version, unused bits, capability kind, and
/// for buffer calls every length and value of a private copy of the request (MC-2.11). `cap` is the slot passed to
/// `recv`; an unexpected capability is dropped (MC-2.12). The `Call` is what the reply functions need.
pub fn decode(request: &Received, cap: usize) -> core::result::Result<(Request, Call), Reject> {
    let words = request.data;
    wire::header(request, cap, MAJOR)?;
    match words[0] & 0xFF {
        1 => {
            wire::body(request, cap, [0x0, 0x0], CAP_KIND_MEMORY, true)?;
            Ok((Request::Attach { buffer: cap }, Call::words(request, cap)))
        }
        2 => {
            wire::body(request, cap, [0x0, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::Claim, Call::words(request, cap)))
        }
        3 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::Release { handle: wire::field(&words, 0, 16, 32) as u32 }, Call::words(request, cap)))
        }
        4 => {
            wire::body(request, cap, [0xffffffffffff0000, 0xffffffffffff], CAP_KIND_NONE, false)?;
            Ok((Request::Control { handle: wire::field(&words, 0, 16, 32) as u32, request_type: wire::field(&words, 0, 48, 8) as u8, request: wire::field(&words, 0, 56, 8) as u8, value: wire::field(&words, 1, 0, 16) as u16, index: wire::field(&words, 1, 16, 16) as u16, length: wire::field(&words, 1, 32, 16) as u16 }, Call::words(request, cap)))
        }
        5 => {
            wire::body(request, cap, [0xffffffffff0000, 0xffffffffffffffff], CAP_KIND_NONE, false)?;
            Ok((Request::Bulk { handle: wire::field(&words, 0, 16, 32) as u32, address: wire::field(&words, 0, 48, 8) as u8, offset: wire::field(&words, 1, 0, 32) as u32, length: wire::field(&words, 1, 32, 32) as u32 }, Call::words(request, cap)))
        }
        6 => {
            wire::body(request, cap, [0xffffffffff0000, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::Reports { handle: wire::field(&words, 0, 16, 32) as u32, address: wire::field(&words, 0, 48, 8) as u8 }, Call::words(request, cap)))
        }
        _ => { wire::discard(request, cap); Err(Reject::Invalid) }
    }
}

pub fn reply_attach(call: Call, value: Result<()>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_error(call, error) };
    wire::finish(call, [0, 0])
}
pub fn reply_claim(call: Call, value: Result<u32>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_error(call, error) };
    wire::finish(call, [((value) as usize) << 16, 0])
}
pub fn reply_release(call: Call, value: Result<()>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_error(call, error) };
    wire::finish(call, [0, 0])
}
pub fn reply_control(call: Call, value: Result<u16>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_error(call, error) };
    wire::finish(call, [((value) as usize) << 16, 0])
}
pub fn reply_bulk(call: Call, value: Result<u32>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_error(call, error) };
    wire::finish(call, [((value) as usize) << 16, 0])
}
pub fn reply_reports(call: Call, value: Result<u16>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_error(call, error) };
    wire::finish(call, [((value) as usize) << 16, 0])
}