// Generated by scripts/mind_idl.py from idl/vfs.wit; do not edit.
//! Files on the boot volume (read-only FAT). Descriptors belong to the calling process. VFS v2 (directory handles,
//! writing) follows in issue 048.
#![allow(clippy::all, unused_imports, unused_mut, unused_variables)]
use crate::abi::*;
use crate::ipc::{Endpoint, Received};
use crate::mem::Pages;
use crate::sys::{Error, Result};
use super::codec::{self, List, Reader, Text, Wire, Writer};
use super::wire::{self, Call, Reject};

pub const PACKAGE: &str = "mind:vfs";
pub const VERSION: (u8, u8, u8) = (1, 0, 0);
const MAJOR: usize = 1;

/// An open file.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct File { pub fd: u32, pub size: u64 }
impl Wire for File {
    const MAX: usize = <u32 as Wire>::MAX + <u64 as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.fd.encode(w)?; self.size.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { fd: Wire::decode(r)?, size: Wire::decode(r)? }) }
}

/// A directory entry.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Entry { pub name: Text<255>, pub size: u32, pub directory: bool }
impl Wire for Entry {
    const MAX: usize = <Text<255> as Wire>::MAX + <u32 as Wire>::MAX + <bool as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.name.encode(w)?; self.size.encode(w)?; self.directory.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { name: Wire::decode(r)?, size: Wire::decode(r)?, directory: Wire::decode(r)? }) }
}

/// Entries of a directory from some index on; `next` is the index of the following page, 0 at the end.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Page { pub entries: List<Entry, 16>, pub next: u32 }
impl Wire for Page {
    const MAX: usize = <List<Entry, 16> as Wire>::MAX + <u32 as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.entries.encode(w)?; self.next.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { entries: Wire::decode(r)?, next: Wire::decode(r)? }) }
}

/// Opens a file by path. Errors: not-found, invalid (a directory), no-slot (descriptor table full).
pub fn open(endpoint: Endpoint, path: &str) -> Result<File> {
    let mut buffer = Pages::new(4096).ok_or(Error::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        codec::encode_str::<255>(path, &mut w).ok_or(Error::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 1 | MAJOR << 8, &buffer, length)?;
    let length = wire::buffer_reply(&reply, 12, false, true)?;
    let length = length.ok_or(Error::Invalid)?;
    Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <File as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(Error::Invalid)? })
}

/// Reads up to `length` bytes at `offset`; fewer at the end of the file.
pub fn read(endpoint: Endpoint, fd: u32, offset: u64, length: u16) -> Result<List<u8, 4096>> {
    let mut buffer = Pages::new(8192).ok_or(Error::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        fd.encode(&mut w).ok_or(Error::Invalid)?;
        offset.encode(&mut w).ok_or(Error::Invalid)?;
        length.encode(&mut w).ok_or(Error::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 2 | MAJOR << 8, &buffer, length)?;
    let length = wire::buffer_reply(&reply, 4098, false, true)?;
    let length = length.ok_or(Error::Invalid)?;
    Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <List<u8, 4096> as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(Error::Invalid)? })
}

/// Size of an open file.
pub fn size(endpoint: Endpoint, fd: u32) -> Result<u64> {
    let words = [3 | MAJOR << 8 | ((fd) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, None)?;
    wire::check_error(&reply)?;
    let _ = wire::check_reply(&reply, [0x0, 0xffffffffffffffff], false)?;
    Ok(wire::field(&reply, 1, 0, 64) as u64)
}

pub fn close(endpoint: Endpoint, fd: u32) -> Result<()> {
    let words = [4 | MAJOR << 8 | ((fd) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, None)?;
    wire::check_error(&reply)?;
    wire::check_reply(&reply, [0, 0], false).map(drop)
}

/// Lists the directory `path` ("" is the root) from entry `start`.
pub fn list(endpoint: Endpoint, path: &str, start: u32) -> Result<Page> {
    let mut buffer = Pages::new(8192).ok_or(Error::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        codec::encode_str::<255>(path, &mut w).ok_or(Error::Invalid)?;
        start.encode(&mut w).ok_or(Error::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 5 | MAJOR << 8, &buffer, length)?;
    let length = wire::buffer_reply(&reply, 4198, false, true)?;
    let length = length.ok_or(Error::Invalid)?;
    Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <Page as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(Error::Invalid)? })
}

/// A request to the `vfs` interface that passed the receiver's schema check.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Request {
    Open { path: Text<255> },
    Read { fd: u32, offset: u64, length: u16 },
    Size { fd: u32 },
    Close { fd: u32 },
    List { path: Text<255>, start: u32 },
}

/// Checks a received message against the schema (MC-2.4): method, major version, unused bits, capability kind, and
/// for buffer calls every length and value of a private copy of the request (MC-2.11). `cap` is the slot passed to
/// `recv`; an unexpected capability is dropped (MC-2.12). The `Call` is what the reply functions need.
pub fn decode(request: &Received, cap: usize) -> core::result::Result<(Request, Call), Reject> {
    let words = request.data;
    wire::header(request, cap, MAJOR)?;
    match words[0] & 0xFF {
        1 => {
            let mut copy = [0u8; 257];
            let (call, length) = wire::take_buffer(request, cap, 12, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            let path = <Text<255> as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Open { path }, call))
        }
        2 => {
            let mut copy = [0u8; 14];
            let (call, length) = wire::take_buffer(request, cap, 4098, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            let fd = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let offset = <u64 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let length = <u16 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Read { fd, offset, length }, call))
        }
        3 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::Size { fd: wire::field(&words, 0, 16, 32) as u32 }, Call::words(request, cap)))
        }
        4 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::Close { fd: wire::field(&words, 0, 16, 32) as u32 }, Call::words(request, cap)))
        }
        5 => {
            let mut copy = [0u8; 261];
            let (call, length) = wire::take_buffer(request, cap, 4198, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            let path = <Text<255> as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let start = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::List { path, start }, call))
        }
        _ => { wire::discard(request, cap); Err(Reject::Invalid) }
    }
}

pub fn reply_open(call: Call, value: Result<&File>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_error(call, error) };
    wire::reply_buffer(call, |w| value.encode(w))
}
pub fn reply_read(call: Call, value: Result<&[u8]>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_error(call, error) };
    wire::reply_buffer(call, |w| codec::encode_slice::<u8, 4096>(value, w))
}
pub fn reply_size(call: Call, value: Result<u64>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_error(call, error) };
    wire::finish(call, [0, ((value) as usize) << 0])
}
pub fn reply_close(call: Call, value: Result<()>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_error(call, error) };
    wire::finish(call, [0, 0])
}
pub fn reply_list(call: Call, value: Result<&Page>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_error(call, error) };
    wire::reply_buffer(call, |w| value.encode(w))
}