// Generated by scripts/mind_idl.py from idl/vfs.wit; do not edit.
//! File service (`vfs_server`) v2: volumes, directory handles and files on FAT, read and write. Every path is relative
//! to a directory handle and cannot leave it (`..` is refused). A handle belongs to the client that opened it (PID and
//! endpoint badge) and never allows more than the handle it was opened from (MC-3.4). What a client may write comes
//! from the badge of its endpoint capability: none for applications, `ram` and the boot disk's `data` directory for
//! the shell (Appendix B.6); boot files are never writable.
#![allow(clippy::all, unused_imports, unused_variables, unused_mut, dead_code)]
use crate::abi::*;
use crate::ipc::{self, Received};
use crate::sys::{Error as SysError, Result};
use super::wire::{self, Reject};

pub const PACKAGE: &str = "mind:vfs";
pub const VERSION: (u8, u8, u8) = (2, 0, 0);
const MAJOR: usize = 2;

/// Why a request failed.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
#[repr(u8)]
pub enum Error { NotFound = 0, Exists = 1, NotEmpty = 2, Invalid = 3, Denied = 4, NoSpace = 5, ReadOnly = 6, Io = 7, Handles = 8, Name = 9, NotDirectory = 10, IsDirectory = 11 }
impl Error {
    pub fn from_u8(value: u8) -> Option<Self> { match value { 0 => Some(Self::NotFound), 1 => Some(Self::Exists), 2 => Some(Self::NotEmpty), 3 => Some(Self::Invalid), 4 => Some(Self::Denied), 5 => Some(Self::NoSpace), 6 => Some(Self::ReadOnly), 7 => Some(Self::Io), 8 => Some(Self::Handles), 9 => Some(Self::Name), 10 => Some(Self::NotDirectory), 11 => Some(Self::IsDirectory), _ => None } }
}
impl<'a> wire::Item<'a> for Error {
    fn encode(&self, w: &mut wire::Writer) -> Result<()> { w.u8(*self as u8) }
    fn decode(r: &mut wire::Reader<'a>) -> Option<Self> { Self::from_u8(r.u8()?) }
}

/// An entry of a directory, or what `stat` reports. `modified` is FAT date << 16 | FAT time; `attributes` are
/// `VFS_ENTRY_*` bits.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Entry<'a> { pub name: &'a str, pub size: u32, pub modified: u32, pub attributes: u8, pub directory: bool }
impl<'a> wire::Item<'a> for Entry<'a> {
    fn encode(&self, w: &mut wire::Writer) -> Result<()> {
        w.str(self.name, 255)?;
        w.u32(self.size)?;
        w.u32(self.modified)?;
        w.u8(self.attributes)?;
        w.bool(self.directory)?;
        Ok(())
    }
    fn decode(r: &mut wire::Reader<'a>) -> Option<Self> { Some(Self { name: r.str(255)?, size: r.u32()?, modified: r.u32()?, attributes: r.u8()?, directory: r.bool()? }) }
}

/// A mounted volume: its name (empty for the boot disk, `ram`), FAT label and type, size and free space.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct Volume<'a> { pub name: &'a str, pub label: &'a str, pub fat_bits: u8, pub bytes: u64, pub free: u64, pub cluster: u32, pub writable: bool }
impl<'a> wire::Item<'a> for Volume<'a> {
    fn encode(&self, w: &mut wire::Writer) -> Result<()> {
        w.str(self.name, 16)?;
        w.str(self.label, 11)?;
        w.u8(self.fat_bits)?;
        w.u64(self.bytes)?;
        w.u64(self.free)?;
        w.u32(self.cluster)?;
        w.bool(self.writable)?;
        Ok(())
    }
    fn decode(r: &mut wire::Reader<'a>) -> Option<Self> { Some(Self { name: r.str(16)?, label: r.str(11)?, fat_bits: r.u8()?, bytes: r.u64()?, free: r.u64()?, cluster: r.u32()?, writable: r.bool()? }) }
}

/// The root directory of volume `name`.
pub fn root<'b>(endpoint: ipc::Endpoint, buffer: wire::Buffer<'b>, name: &'_ str) -> Result<core::result::Result<u32, Error>> {
    let wire::Buffer { cap, bytes } = buffer;
    let mut writer = wire::Writer::new(bytes);
    {
        let w = &mut writer;
        w.str(name, 16)?;
    }
    let payload = writer.len();
    let bytes = writer.into_inner();
    let words = [1 | MAJOR << 8 | ((payload) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, Some((cap, false)))?;
    let status = wire::check_reply(&reply, [0xffffffff0000, 0x0], false, true)?;
    if let wire::Status::Failed(code) = status { return Error::from_u8(code).map(Err).ok_or(SysError::Invalid); }
    Ok(Ok(wire::field(&reply, 0, 16, 32) as u32))
}

/// A directory below `dir`; with `create` it is made if missing.
pub fn open_dir<'b>(endpoint: ipc::Endpoint, buffer: wire::Buffer<'b>, dir: u32, create: bool, path: &'_ str) -> Result<core::result::Result<u32, Error>> {
    let wire::Buffer { cap, bytes } = buffer;
    let mut writer = wire::Writer::new(bytes);
    {
        let w = &mut writer;
        w.str(path, 255)?;
    }
    let payload = writer.len();
    let bytes = writer.into_inner();
    let words = [2 | MAJOR << 8 | ((payload) as usize) << 16, ((dir) as usize) << 0 | ((create) as usize) << 32];
    let reply = wire::call(endpoint, words, Some((cap, false)))?;
    let status = wire::check_reply(&reply, [0xffffffff0000, 0x0], false, true)?;
    if let wire::Status::Failed(code) = status { return Error::from_u8(code).map(Err).ok_or(SysError::Invalid); }
    Ok(Ok(wire::field(&reply, 0, 16, 32) as u32))
}

/// A file below `dir`. `mode` bits: 1 write, 2 create, 4 truncate, 8 refuse an existing file.
pub fn open<'b>(endpoint: ipc::Endpoint, buffer: wire::Buffer<'b>, dir: u32, mode: u8, path: &'_ str) -> Result<core::result::Result<u32, Error>> {
    let wire::Buffer { cap, bytes } = buffer;
    let mut writer = wire::Writer::new(bytes);
    {
        let w = &mut writer;
        w.str(path, 255)?;
    }
    let payload = writer.len();
    let bytes = writer.into_inner();
    let words = [3 | MAJOR << 8 | ((payload) as usize) << 16, ((dir) as usize) << 0 | ((mode) as usize) << 32];
    let reply = wire::call(endpoint, words, Some((cap, false)))?;
    let status = wire::check_reply(&reply, [0xffffffff0000, 0x0], false, true)?;
    if let wire::Status::Failed(code) = status { return Error::from_u8(code).map(Err).ok_or(SysError::Invalid); }
    Ok(Ok(wire::field(&reply, 0, 16, 32) as u32))
}

/// Up to `length` bytes from `offset` (fewer at the end of the file).
pub fn read<'b>(endpoint: ipc::Endpoint, buffer: wire::Buffer<'b>, file: u32, offset: u32, length: u32) -> Result<core::result::Result<&'b [u8], Error>> {
    let wire::Buffer { cap, bytes } = buffer;
    let mut writer = wire::Writer::new(bytes);
    let payload = writer.len();
    let bytes = writer.into_inner();
    let words = [4 | MAJOR << 8 | ((file) as usize) << 16, ((offset) as usize) << 0 | ((length) as usize) << 32];
    let reply = wire::call(endpoint, words, Some((cap, false)))?;
    let status = wire::check_reply(&reply, [0xffffffff0000, 0x0], false, true)?;
    if let wire::Status::Failed(code) = status { return Error::from_u8(code).map(Err).ok_or(SysError::Invalid); }
    let len = wire::field(&reply, 0, 16, 32);
    if len > bytes.len() { return Err(SysError::Invalid); }
    let bytes: &'b [u8] = bytes;
    let mut reader = wire::Reader::new(&bytes[..len]);
    let value = (|r: &mut wire::Reader<'b>| -> Option<_> { let value = r.bytes(65536)?; r.end().then_some(value) })(&mut reader).ok_or(SysError::Invalid)?;
    Ok(Ok(value))
}

/// Writes `data` at `offset`; the file grows (a gap reads as zeros). Returns the bytes written.
pub fn write<'b>(endpoint: ipc::Endpoint, buffer: wire::Buffer<'b>, file: u32, offset: u32, data: &'_ [u8]) -> Result<core::result::Result<u32, Error>> {
    let wire::Buffer { cap, bytes } = buffer;
    let mut writer = wire::Writer::new(bytes);
    {
        let w = &mut writer;
        w.bytes(data, 65536)?;
    }
    let payload = writer.len();
    let bytes = writer.into_inner();
    let words = [5 | MAJOR << 8 | ((payload) as usize) << 16, ((file) as usize) << 0 | ((offset) as usize) << 32];
    let reply = wire::call(endpoint, words, Some((cap, false)))?;
    let status = wire::check_reply(&reply, [0xffffffff0000, 0x0], false, true)?;
    if let wire::Status::Failed(code) = status { return Error::from_u8(code).map(Err).ok_or(SysError::Invalid); }
    Ok(Ok(wire::field(&reply, 0, 16, 32) as u32))
}

/// Sets the size of a file: clusters past it are freed, a longer file reads zeros.
pub fn truncate(endpoint: ipc::Endpoint, file: u32, size: u32) -> Result<core::result::Result<(), Error>> {
    let words = [6 | MAJOR << 8 | ((file) as usize) << 16, ((size) as usize) << 0];
    let reply = wire::call(endpoint, words, None)?;
    let status = wire::check_reply(&reply, [0x0, 0x0], false, true)?;
    if let wire::Status::Failed(code) = status { return Error::from_u8(code).map(Err).ok_or(SysError::Invalid); }
    Ok(Ok(()))
}

/// The entry of an open file or directory.
pub fn stat<'b>(endpoint: ipc::Endpoint, buffer: wire::Buffer<'b>, handle: u32) -> Result<core::result::Result<Entry<'b>, Error>> {
    let wire::Buffer { cap, bytes } = buffer;
    let mut writer = wire::Writer::new(bytes);
    let payload = writer.len();
    let bytes = writer.into_inner();
    let words = [7 | MAJOR << 8 | ((handle) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, Some((cap, false)))?;
    let status = wire::check_reply(&reply, [0xffffffff0000, 0x0], false, true)?;
    if let wire::Status::Failed(code) = status { return Error::from_u8(code).map(Err).ok_or(SysError::Invalid); }
    let len = wire::field(&reply, 0, 16, 32);
    if len > bytes.len() { return Err(SysError::Invalid); }
    let bytes: &'b [u8] = bytes;
    let mut reader = wire::Reader::new(&bytes[..len]);
    let value = (|r: &mut wire::Reader<'b>| -> Option<_> { let value = <Entry<'b> as wire::Item>::decode(r)?; r.end().then_some(value) })(&mut reader).ok_or(SysError::Invalid)?;
    Ok(Ok(value))
}

/// Entries of `dir` from index `start`, as many as fit the buffer (an empty list: the end).
pub fn list<'b>(endpoint: ipc::Endpoint, buffer: wire::Buffer<'b>, dir: u32, start: u32) -> Result<core::result::Result<wire::List<'b, Entry<'b>>, Error>> {
    let wire::Buffer { cap, bytes } = buffer;
    let mut writer = wire::Writer::new(bytes);
    let payload = writer.len();
    let bytes = writer.into_inner();
    let words = [8 | MAJOR << 8 | ((dir) as usize) << 16, ((start) as usize) << 0];
    let reply = wire::call(endpoint, words, Some((cap, false)))?;
    let status = wire::check_reply(&reply, [0xffffffff0000, 0x0], false, true)?;
    if let wire::Status::Failed(code) = status { return Error::from_u8(code).map(Err).ok_or(SysError::Invalid); }
    let len = wire::field(&reply, 0, 16, 32);
    if len > bytes.len() { return Err(SysError::Invalid); }
    let bytes: &'b [u8] = bytes;
    let mut reader = wire::Reader::new(&bytes[..len]);
    let value = (|r: &mut wire::Reader<'b>| -> Option<_> { let value = wire::List::read(r, 256)?; r.end().then_some(value) })(&mut reader).ok_or(SysError::Invalid)?;
    Ok(Ok(value))
}

/// Removes a file or an empty directory below `dir`.
pub fn remove<'b>(endpoint: ipc::Endpoint, buffer: wire::Buffer<'b>, dir: u32, path: &'_ str) -> Result<core::result::Result<(), Error>> {
    let wire::Buffer { cap, bytes } = buffer;
    let mut writer = wire::Writer::new(bytes);
    {
        let w = &mut writer;
        w.str(path, 255)?;
    }
    let payload = writer.len();
    let bytes = writer.into_inner();
    let words = [9 | MAJOR << 8 | ((payload) as usize) << 16, ((dir) as usize) << 0];
    let reply = wire::call(endpoint, words, Some((cap, false)))?;
    let status = wire::check_reply(&reply, [0x0, 0x0], false, true)?;
    if let wire::Status::Failed(code) = status { return Error::from_u8(code).map(Err).ok_or(SysError::Invalid); }
    Ok(Ok(()))
}

/// Renames or moves `from` (below `dir`) to `to` (below `target`, on the same volume).
pub fn rename<'b>(endpoint: ipc::Endpoint, buffer: wire::Buffer<'b>, dir: u32, target: u32, from: &'_ str, to: &'_ str) -> Result<core::result::Result<(), Error>> {
    let wire::Buffer { cap, bytes } = buffer;
    let mut writer = wire::Writer::new(bytes);
    {
        let w = &mut writer;
        w.str(from, 255)?;
        w.str(to, 255)?;
    }
    let payload = writer.len();
    let bytes = writer.into_inner();
    let words = [10 | MAJOR << 8 | ((payload) as usize) << 16, ((dir) as usize) << 0 | ((target) as usize) << 32];
    let reply = wire::call(endpoint, words, Some((cap, false)))?;
    let status = wire::check_reply(&reply, [0x0, 0x0], false, true)?;
    if let wire::Status::Failed(code) = status { return Error::from_u8(code).map(Err).ok_or(SysError::Invalid); }
    Ok(Ok(()))
}

/// The volume a handle is on.
pub fn volume<'b>(endpoint: ipc::Endpoint, buffer: wire::Buffer<'b>, handle: u32) -> Result<core::result::Result<Volume<'b>, Error>> {
    let wire::Buffer { cap, bytes } = buffer;
    let mut writer = wire::Writer::new(bytes);
    let payload = writer.len();
    let bytes = writer.into_inner();
    let words = [11 | MAJOR << 8 | ((handle) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, Some((cap, false)))?;
    let status = wire::check_reply(&reply, [0xffffffff0000, 0x0], false, true)?;
    if let wire::Status::Failed(code) = status { return Error::from_u8(code).map(Err).ok_or(SysError::Invalid); }
    let len = wire::field(&reply, 0, 16, 32);
    if len > bytes.len() { return Err(SysError::Invalid); }
    let bytes: &'b [u8] = bytes;
    let mut reader = wire::Reader::new(&bytes[..len]);
    let value = (|r: &mut wire::Reader<'b>| -> Option<_> { let value = <Volume<'b> as wire::Item>::decode(r)?; r.end().then_some(value) })(&mut reader).ok_or(SysError::Invalid)?;
    Ok(Ok(value))
}

/// Writes what is cached for the volume of `handle` to the disk.
pub fn flush(endpoint: ipc::Endpoint, handle: u32) -> Result<core::result::Result<(), Error>> {
    let words = [12 | MAJOR << 8 | ((handle) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, None)?;
    let status = wire::check_reply(&reply, [0x0, 0x0], false, true)?;
    if let wire::Status::Failed(code) = status { return Error::from_u8(code).map(Err).ok_or(SysError::Invalid); }
    Ok(Ok(()))
}

pub fn close(endpoint: ipc::Endpoint, handle: u32) -> Result<core::result::Result<(), Error>> {
    let words = [13 | MAJOR << 8 | ((handle) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, None)?;
    let status = wire::check_reply(&reply, [0x0, 0x0], false, true)?;
    if let wire::Status::Failed(code) = status { return Error::from_u8(code).map(Err).ok_or(SysError::Invalid); }
    Ok(Ok(()))
}

/// A request to the `vfs` interface that passed the receiver's schema check.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Request {
    Root { payload: u32, buffer: usize },
    OpenDir { payload: u32, buffer: usize, dir: u32, create: bool },
    Open { payload: u32, buffer: usize, dir: u32, mode: u8 },
    Read { buffer: usize, file: u32, offset: u32, length: u32 },
    Write { payload: u32, buffer: usize, file: u32, offset: u32 },
    Truncate { file: u32, size: u32 },
    Stat { buffer: usize, handle: u32 },
    List { buffer: usize, dir: u32, start: u32 },
    Remove { payload: u32, buffer: usize, dir: u32 },
    Rename { payload: u32, buffer: usize, dir: u32, target: u32 },
    Volume { buffer: usize, handle: u32 },
    Flush { handle: u32 },
    Close { handle: u32 },
}

/// Checks a received message against the schema (MC-2.4): method, major version, unused bits, enum values, capability
/// kind. `cap` is the slot passed to `recv`; an unexpected capability is dropped (MC-2.12). Bulk arguments are checked
/// by `args_<function>` once the server has mapped the buffer.
pub fn decode(request: &Received, cap: usize) -> core::result::Result<Request, Reject> {
    let words = request.data;
    wire::header(request, cap, MAJOR)?;
    match words[0] & 0xFF {
        1 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_MEMORY, true)?;
            Ok(Request::Root { payload: wire::field(&words, 0, 16, 32) as u32, buffer: cap })
        }
        2 => {
            wire::body(request, cap, [0xffffffff0000, 0x1ffffffff], CAP_KIND_MEMORY, true)?;
            Ok(Request::OpenDir { payload: wire::field(&words, 0, 16, 32) as u32, buffer: cap, dir: wire::field(&words, 1, 0, 32) as u32, create: wire::field(&words, 1, 32, 1) != 0 })
        }
        3 => {
            wire::body(request, cap, [0xffffffff0000, 0xffffffffff], CAP_KIND_MEMORY, true)?;
            Ok(Request::Open { payload: wire::field(&words, 0, 16, 32) as u32, buffer: cap, dir: wire::field(&words, 1, 0, 32) as u32, mode: wire::field(&words, 1, 32, 8) as u8 })
        }
        4 => {
            wire::body(request, cap, [0xffffffff0000, 0xffffffffffffffff], CAP_KIND_MEMORY, true)?;
            Ok(Request::Read { buffer: cap, file: wire::field(&words, 0, 16, 32) as u32, offset: wire::field(&words, 1, 0, 32) as u32, length: wire::field(&words, 1, 32, 32) as u32 })
        }
        5 => {
            wire::body(request, cap, [0xffffffff0000, 0xffffffffffffffff], CAP_KIND_MEMORY, true)?;
            Ok(Request::Write { payload: wire::field(&words, 0, 16, 32) as u32, buffer: cap, file: wire::field(&words, 1, 0, 32) as u32, offset: wire::field(&words, 1, 32, 32) as u32 })
        }
        6 => {
            wire::body(request, cap, [0xffffffff0000, 0xffffffff], CAP_KIND_NONE, false)?;
            Ok(Request::Truncate { file: wire::field(&words, 0, 16, 32) as u32, size: wire::field(&words, 1, 0, 32) as u32 })
        }
        7 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_MEMORY, true)?;
            Ok(Request::Stat { buffer: cap, handle: wire::field(&words, 0, 16, 32) as u32 })
        }
        8 => {
            wire::body(request, cap, [0xffffffff0000, 0xffffffff], CAP_KIND_MEMORY, true)?;
            Ok(Request::List { buffer: cap, dir: wire::field(&words, 0, 16, 32) as u32, start: wire::field(&words, 1, 0, 32) as u32 })
        }
        9 => {
            wire::body(request, cap, [0xffffffff0000, 0xffffffff], CAP_KIND_MEMORY, true)?;
            Ok(Request::Remove { payload: wire::field(&words, 0, 16, 32) as u32, buffer: cap, dir: wire::field(&words, 1, 0, 32) as u32 })
        }
        10 => {
            wire::body(request, cap, [0xffffffff0000, 0xffffffffffffffff], CAP_KIND_MEMORY, true)?;
            Ok(Request::Rename { payload: wire::field(&words, 0, 16, 32) as u32, buffer: cap, dir: wire::field(&words, 1, 0, 32) as u32, target: wire::field(&words, 1, 32, 32) as u32 })
        }
        11 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_MEMORY, true)?;
            Ok(Request::Volume { buffer: cap, handle: wire::field(&words, 0, 16, 32) as u32 })
        }
        12 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_NONE, false)?;
            Ok(Request::Flush { handle: wire::field(&words, 0, 16, 32) as u32 })
        }
        13 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_NONE, false)?;
            Ok(Request::Close { handle: wire::field(&words, 0, 16, 32) as u32 })
        }
        _ => { wire::discard(request, cap); Err(Reject::Invalid) }
    }
}

/// Bulk arguments of `root` from the mapped buffer: exactly `payload` bytes, every limit checked.
pub fn args_root<'a>(bytes: &'a [u8], payload: u32) -> core::result::Result<&'a str, Reject> {
    let len = payload as usize;
    if len > bytes.len() { return Err(Reject::Invalid); }
    let mut reader = wire::Reader::new(&bytes[..len]);
    let value = (|r: &mut wire::Reader<'a>| -> Option<_> { let value = r.str(16)?; r.end().then_some(value) })(&mut reader);
    value.ok_or(Reject::Invalid)
}

/// Bulk arguments of `open_dir` from the mapped buffer: exactly `payload` bytes, every limit checked.
pub fn args_open_dir<'a>(bytes: &'a [u8], payload: u32) -> core::result::Result<&'a str, Reject> {
    let len = payload as usize;
    if len > bytes.len() { return Err(Reject::Invalid); }
    let mut reader = wire::Reader::new(&bytes[..len]);
    let value = (|r: &mut wire::Reader<'a>| -> Option<_> { let value = r.str(255)?; r.end().then_some(value) })(&mut reader);
    value.ok_or(Reject::Invalid)
}

/// Bulk arguments of `open` from the mapped buffer: exactly `payload` bytes, every limit checked.
pub fn args_open<'a>(bytes: &'a [u8], payload: u32) -> core::result::Result<&'a str, Reject> {
    let len = payload as usize;
    if len > bytes.len() { return Err(Reject::Invalid); }
    let mut reader = wire::Reader::new(&bytes[..len]);
    let value = (|r: &mut wire::Reader<'a>| -> Option<_> { let value = r.str(255)?; r.end().then_some(value) })(&mut reader);
    value.ok_or(Reject::Invalid)
}

/// Bulk arguments of `write` from the mapped buffer: exactly `payload` bytes, every limit checked.
pub fn args_write<'a>(bytes: &'a [u8], payload: u32) -> core::result::Result<&'a [u8], Reject> {
    let len = payload as usize;
    if len > bytes.len() { return Err(Reject::Invalid); }
    let mut reader = wire::Reader::new(&bytes[..len]);
    let value = (|r: &mut wire::Reader<'a>| -> Option<_> { let value = r.bytes(65536)?; r.end().then_some(value) })(&mut reader);
    value.ok_or(Reject::Invalid)
}

/// Bulk arguments of `remove` from the mapped buffer: exactly `payload` bytes, every limit checked.
pub fn args_remove<'a>(bytes: &'a [u8], payload: u32) -> core::result::Result<&'a str, Reject> {
    let len = payload as usize;
    if len > bytes.len() { return Err(Reject::Invalid); }
    let mut reader = wire::Reader::new(&bytes[..len]);
    let value = (|r: &mut wire::Reader<'a>| -> Option<_> { let value = r.str(255)?; r.end().then_some(value) })(&mut reader);
    value.ok_or(Reject::Invalid)
}

/// Bulk arguments of `rename` from the mapped buffer: exactly `payload` bytes, every limit checked.
pub fn args_rename<'a>(bytes: &'a [u8], payload: u32) -> core::result::Result<(&'a str, &'a str), Reject> {
    let len = payload as usize;
    if len > bytes.len() { return Err(Reject::Invalid); }
    let mut reader = wire::Reader::new(&bytes[..len]);
    let value = (|r: &mut wire::Reader<'a>| -> Option<_> { let value = (r.str(255)?, r.str(255)?); r.end().then_some(value) })(&mut reader);
    value.ok_or(Reject::Invalid)
}

pub fn reply_root(value: core::result::Result<u32, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(code) => return wire::reply([wire::STATUS_FAILED | (code as usize) << 16, 0]) };
    wire::reply([((value) as usize) << 16, 0])
}
pub fn reply_open_dir(value: core::result::Result<u32, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(code) => return wire::reply([wire::STATUS_FAILED | (code as usize) << 16, 0]) };
    wire::reply([((value) as usize) << 16, 0])
}
pub fn reply_open(value: core::result::Result<u32, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(code) => return wire::reply([wire::STATUS_FAILED | (code as usize) << 16, 0]) };
    wire::reply([((value) as usize) << 16, 0])
}
pub fn reply_read(bytes: &mut [u8], value: core::result::Result<&'_ [u8], Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(code) => return wire::reply([wire::STATUS_FAILED | (code as usize) << 16, 0]) };
    let mut writer = wire::Writer::new(bytes);
    let encoded = (|w: &mut wire::Writer| -> Result<()> { w.bytes(value, 65536)?; Ok(()) })(&mut writer);
    if encoded.is_err() { return wire::reply([wire::STATUS_OVERFLOW, 0]); }
    wire::reply([(writer.len() as usize) << 16, 0])
}
pub fn reply_write(value: core::result::Result<u32, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(code) => return wire::reply([wire::STATUS_FAILED | (code as usize) << 16, 0]) };
    wire::reply([((value) as usize) << 16, 0])
}
pub fn reply_truncate(value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(code) => return wire::reply([wire::STATUS_FAILED | (code as usize) << 16, 0]) };
    wire::reply([0, 0])
}
pub fn reply_stat(bytes: &mut [u8], value: core::result::Result<Entry<'_>, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(code) => return wire::reply([wire::STATUS_FAILED | (code as usize) << 16, 0]) };
    let mut writer = wire::Writer::new(bytes);
    let encoded = (|w: &mut wire::Writer| -> Result<()> { wire::Item::encode(&value, w)?; Ok(()) })(&mut writer);
    if encoded.is_err() { return wire::reply([wire::STATUS_OVERFLOW, 0]); }
    wire::reply([(writer.len() as usize) << 16, 0])
}
pub fn reply_list(bytes: &mut [u8], value: core::result::Result<&'_ [Entry<'_>], Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(code) => return wire::reply([wire::STATUS_FAILED | (code as usize) << 16, 0]) };
    let mut writer = wire::Writer::new(bytes);
    let encoded = (|w: &mut wire::Writer| -> Result<()> { w.list(value, 256)?; Ok(()) })(&mut writer);
    if encoded.is_err() { return wire::reply([wire::STATUS_OVERFLOW, 0]); }
    wire::reply([(writer.len() as usize) << 16, 0])
}
pub fn reply_remove(value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(code) => return wire::reply([wire::STATUS_FAILED | (code as usize) << 16, 0]) };
    wire::reply([0, 0])
}
pub fn reply_rename(value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(code) => return wire::reply([wire::STATUS_FAILED | (code as usize) << 16, 0]) };
    wire::reply([0, 0])
}
pub fn reply_volume(bytes: &mut [u8], value: core::result::Result<Volume<'_>, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(code) => return wire::reply([wire::STATUS_FAILED | (code as usize) << 16, 0]) };
    let mut writer = wire::Writer::new(bytes);
    let encoded = (|w: &mut wire::Writer| -> Result<()> { wire::Item::encode(&value, w)?; Ok(()) })(&mut writer);
    if encoded.is_err() { return wire::reply([wire::STATUS_OVERFLOW, 0]); }
    wire::reply([(writer.len() as usize) << 16, 0])
}
pub fn reply_flush(value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(code) => return wire::reply([wire::STATUS_FAILED | (code as usize) << 16, 0]) };
    wire::reply([0, 0])
}
pub fn reply_close(value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(code) => return wire::reply([wire::STATUS_FAILED | (code as usize) << 16, 0]) };
    wire::reply([0, 0])
}
