// Generated by scripts/mind_idl.py from idl/vfs.wit; do not edit.
//! File service (`vfs_server`) v2: volumes, directory handles and files on FAT, read and write. Every path is relative
//! to a directory handle and cannot leave it (`..` is refused). A handle belongs to the client that opened it (PID and
//! endpoint badge) and never allows more than the handle it was opened from (MC-3.4). What a client may write comes
//! from the badge of its endpoint capability: none for applications, `ram` and the boot disk's `data` directory for
//! the shell (`mind::fs::BADGE_USER`, Appendix B.6); boot files and the model disk `models` are never writable. Major
//! version 2: directory handles change the meaning of `open` and `list` of 1.0.
#![allow(clippy::all, unused_imports, unused_mut, unused_variables)]
use crate::abi::*;
use crate::ipc::{Endpoint, Received};
use crate::mem::Pages;
use crate::sys::{Error as SysError, Result};
use super::codec::{self, List, Reader, Text, Wire, Writer};
use super::wire::{self, Call, Reject};

pub const PACKAGE: &str = "mind:vfs";
pub const VERSION: (u8, u8, u8) = (2, 3, 0);
const MAJOR: usize = 2;

/// Why a request failed.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[repr(u8)]
pub enum Error { #[default] NotFound = 0, Exists = 1, NotEmpty = 2, Invalid = 3, Denied = 4, NoSpace = 5, ReadOnly = 6, Io = 7, Handles = 8, Name = 9, NotDirectory = 10, IsDirectory = 11 }
impl Error {
    /// The case with wire code `code`; None for a code the interface does not define.
    pub fn from_code(code: usize) -> Option<Self> { match code { 0 => Some(Self::NotFound), 1 => Some(Self::Exists), 2 => Some(Self::NotEmpty), 3 => Some(Self::Invalid), 4 => Some(Self::Denied), 5 => Some(Self::NoSpace), 6 => Some(Self::ReadOnly), 7 => Some(Self::Io), 8 => Some(Self::Handles), 9 => Some(Self::Name), 10 => Some(Self::NotDirectory), 11 => Some(Self::IsDirectory), _ => None } }
}
impl Wire for Error {
    const MAX: usize = 1;
    fn encode(&self, w: &mut Writer) -> Option<()> { (*self as u8).encode(w) }
    fn decode(r: &mut Reader) -> Option<Self> { Self::from_code(u8::decode(r)? as usize) }
}

/// An entry of a directory, or what `stat` reports. `modified` is FAT date << 16 | FAT time; `attributes` are
/// `mind::fs::ENTRY_*` bits.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Entry { pub name: Text<255>, pub size: u32, pub modified: u32, pub attributes: u8, pub directory: bool }
impl Wire for Entry {
    const MAX: usize = <Text<255> as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX + <u8 as Wire>::MAX + <bool as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.name.encode(w)?; self.size.encode(w)?; self.modified.encode(w)?; self.attributes.encode(w)?; self.directory.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { name: Wire::decode(r)?, size: Wire::decode(r)?, modified: Wire::decode(r)?, attributes: Wire::decode(r)?, directory: Wire::decode(r)? }) }
}

/// A mounted volume: its name (empty for the boot disk, `ram`, `models`), FAT label and type, size and free space.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Volume { pub name: Text<16>, pub label: Text<11>, pub fat_bits: u8, pub bytes: u64, pub free: u64, pub cluster: u32, pub writable: bool }
impl Wire for Volume {
    const MAX: usize = <Text<16> as Wire>::MAX + <Text<11> as Wire>::MAX + <u8 as Wire>::MAX + <u64 as Wire>::MAX + <u64 as Wire>::MAX + <u32 as Wire>::MAX + <bool as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.name.encode(w)?; self.label.encode(w)?; self.fat_bits.encode(w)?; self.bytes.encode(w)?; self.free.encode(w)?; self.cluster.encode(w)?; self.writable.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { name: Wire::decode(r)?, label: Wire::decode(r)?, fat_bits: Wire::decode(r)?, bytes: Wire::decode(r)?, free: Wire::decode(r)?, cluster: Wire::decode(r)?, writable: Wire::decode(r)? }) }
}

/// What a check of a volume found (nothing is changed): `used` clusters are reached from the directory tree, `lost`
/// ones are in use but reached by nothing (forming `lost-chains` chains), `cross-linked` ones are reached twice;
/// `bad-chains` run into a free or invalid cluster; `sizes` counts files whose size does not match their chain,
/// `bad-entries` invalid directory entries; `dirty`: not flushed since a change; `first`: the first problem found.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Report { pub files: u32, pub directories: u32, pub used: u32, pub free: u32, pub lost: u32, pub lost_chains: u32, pub cross_linked: u32, pub bad_chains: u32, pub sizes: u32, pub bad_entries: u32, pub dirty: bool, pub first: Text<255> }
impl Wire for Report {
    const MAX: usize = <u32 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX + <u32 as Wire>::MAX + <bool as Wire>::MAX + <Text<255> as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.files.encode(w)?; self.directories.encode(w)?; self.used.encode(w)?; self.free.encode(w)?; self.lost.encode(w)?; self.lost_chains.encode(w)?; self.cross_linked.encode(w)?; self.bad_chains.encode(w)?; self.sizes.encode(w)?; self.bad_entries.encode(w)?; self.dirty.encode(w)?; self.first.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { files: Wire::decode(r)?, directories: Wire::decode(r)?, used: Wire::decode(r)?, free: Wire::decode(r)?, lost: Wire::decode(r)?, lost_chains: Wire::decode(r)?, cross_linked: Wire::decode(r)?, bad_chains: Wire::decode(r)?, sizes: Wire::decode(r)?, bad_entries: Wire::decode(r)?, dirty: Wire::decode(r)?, first: Wire::decode(r)? }) }
}

/// The root directory of volume `name`.
pub fn root(endpoint: Endpoint, name: &str) -> Result<core::result::Result<u32, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        codec::encode_str::<16>(name, &mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 1 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 4, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <u32 as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// A directory below `dir`; with `create` it is made if missing.
pub fn open_dir(endpoint: Endpoint, dir: u32, path: &str, create: bool) -> Result<core::result::Result<u32, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        dir.encode(&mut w).ok_or(SysError::Invalid)?;
        codec::encode_str::<255>(path, &mut w).ok_or(SysError::Invalid)?;
        create.encode(&mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 2 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 4, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <u32 as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// A file below `dir`. `mode` bits (`mind::fs::MODE_*`): 1 write, 2 create, 4 truncate, 8 refuse an existing file.
pub fn open(endpoint: Endpoint, dir: u32, path: &str, mode: u8) -> Result<core::result::Result<u32, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        dir.encode(&mut w).ok_or(SysError::Invalid)?;
        codec::encode_str::<255>(path, &mut w).ok_or(SysError::Invalid)?;
        mode.encode(&mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 3 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 4, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <u32 as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// Up to `length` bytes from `offset` (fewer at the end of the file).
pub fn read(endpoint: Endpoint, file: u32, offset: u32, length: u32, out: &mut [u8]) -> Result<core::result::Result<usize, Error>> {
    let mut buffer = Pages::new(20480).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        file.encode(&mut w).ok_or(SysError::Invalid)?;
        offset.encode(&mut w).ok_or(SysError::Invalid)?;
        length.encode(&mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 4 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 16386, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); let data = codec::decode_bytes::<16384>(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)?; out.get_mut(..data.len()).ok_or(SysError::Invalid)?.copy_from_slice(data); data.len() }))
}

/// Writes `data` at `offset`; the file grows (a gap reads as zeros). Returns the bytes written.
pub fn write(endpoint: Endpoint, file: u32, offset: u32, data: &[u8]) -> Result<core::result::Result<u32, Error>> {
    let mut buffer = Pages::new(20480).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        file.encode(&mut w).ok_or(SysError::Invalid)?;
        offset.encode(&mut w).ok_or(SysError::Invalid)?;
        codec::encode_bytes::<16384>(data, &mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 5 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 4, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <u32 as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// Sets the size of a file: clusters past it are freed, a longer file reads zeros.
pub fn truncate(endpoint: Endpoint, file: u32, size: u32) -> Result<core::result::Result<(), Error>> {
    let words = [6 | MAJOR << 8 | ((file) as usize) << 16, ((size) as usize) << 0];
    let reply = wire::call(endpoint, words, None)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    wire::check_reply(&reply, [0, 0], false)?;
    Ok(Ok(()))
}

/// The entry of an open file or directory.
pub fn stat(endpoint: Endpoint, handle: u32) -> Result<core::result::Result<Entry, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        handle.encode(&mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 7 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 267, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <Entry as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// Entries of `dir` from index `start`, at most 16 (an empty list: the end).
pub fn list(endpoint: Endpoint, dir: u32, start: u32) -> Result<core::result::Result<List<Entry, 16>, Error>> {
    let mut buffer = Pages::new(8192).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        dir.encode(&mut w).ok_or(SysError::Invalid)?;
        start.encode(&mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 8 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 4274, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <List<Entry, 16> as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// Removes a file or an empty directory below `dir`.
pub fn remove(endpoint: Endpoint, dir: u32, path: &str) -> Result<core::result::Result<(), Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        dir.encode(&mut w).ok_or(SysError::Invalid)?;
        codec::encode_str::<255>(path, &mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 9 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 0, false, false)?;
    if length != Some(0) { return Err(SysError::Invalid); }
    Ok(Ok(()))
}

/// Renames or moves `from` (below `dir`) to `to` (below `target`, on the same volume).
pub fn rename(endpoint: Endpoint, dir: u32, from: &str, target: u32, to: &str) -> Result<core::result::Result<(), Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        dir.encode(&mut w).ok_or(SysError::Invalid)?;
        codec::encode_str::<255>(from, &mut w).ok_or(SysError::Invalid)?;
        target.encode(&mut w).ok_or(SysError::Invalid)?;
        codec::encode_str::<255>(to, &mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 10 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 0, false, false)?;
    if length != Some(0) { return Err(SysError::Invalid); }
    Ok(Ok(()))
}

/// The volume a handle is on.
pub fn volume(endpoint: Endpoint, handle: u32) -> Result<core::result::Result<Volume, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        handle.encode(&mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 11 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 53, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <Volume as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// Writes what is cached for the volume of `handle` to the disk.
pub fn flush(endpoint: Endpoint, handle: u32) -> Result<core::result::Result<(), Error>> {
    let words = [12 | MAJOR << 8 | ((handle) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, None)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    wire::check_reply(&reply, [0, 0], false)?;
    Ok(Ok(()))
}

pub fn close(endpoint: Endpoint, handle: u32) -> Result<core::result::Result<(), Error>> {
    let words = [13 | MAJOR << 8 | ((handle) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, None)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    wire::check_reply(&reply, [0, 0], false)?;
    Ok(Ok(()))
}

/// Checks the volume of `handle` without changing it (2.1).
pub fn check(endpoint: Endpoint, handle: u32) -> Result<core::result::Result<Report, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        handle.encode(&mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 14 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 298, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <Report as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// A client confined to directory `dir` (a handle of the caller), placed in the caller's fixed slot `receive`: its
/// `root` of the directory's volume is that directory, every other root is refused, and it may change files there
/// only if `writable` and the caller may (never more than `dir`, MC-3.4). It works for the first task that uses it
/// and ends when that task does: vfs_server then revokes it. For a launcher to give a program one directory (2.2).
pub fn scope(endpoint: Endpoint, dir: u32, writable: bool, receive: usize) -> Result<core::result::Result<(), Error>> {
    let words = [15 | MAJOR << 8 | ((dir) as usize) << 16 | ((writable) as usize) << 48, 0];
    let (reply, received) = wire::call_receiving(endpoint, words, None, receive)?;
    match wire::check_cap_reply(&reply, received, receive)? {
        None => Ok(Ok(())),
        Some(code) => Ok(Err(Error::from_code(wire::enum_code(code)?).ok_or(SysError::Invalid)?)),
    }
}

/// Writes a new empty FAT volume labelled `label` (ASCII, upper-cased) over the RAM disk and mounts it; `handle` is
/// the root of `ram` opened with the user's badge. Handles below the root and scopes on the volume end; root handles
/// stay valid. The boot disk is refused (denied) (2.3).
pub fn format(endpoint: Endpoint, handle: u32, label: &str) -> Result<core::result::Result<(), Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        handle.encode(&mut w).ok_or(SysError::Invalid)?;
        codec::encode_str::<11>(label, &mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 16 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 0, false, false)?;
    if length != Some(0) { return Err(SysError::Invalid); }
    Ok(Ok(()))
}

/// Size of the scratch buffer `decode` copies a request into (the largest request).
pub const REQUEST_MAX: usize = 16394;

/// A request to the `vfs` interface that passed the receiver's schema check.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Request<'a> {
    Root { name: Text<16> },
    OpenDir { dir: u32, path: Text<255>, create: bool },
    Open { dir: u32, path: Text<255>, mode: u8 },
    Read { file: u32, offset: u32, length: u32 },
    Write { file: u32, offset: u32, data: &'a [u8] },
    Truncate { file: u32, size: u32 },
    Stat { handle: u32 },
    List { dir: u32, start: u32 },
    Remove { dir: u32, path: Text<255> },
    Rename { dir: u32, from: Text<255>, target: u32, to: Text<255> },
    Volume { handle: u32 },
    Flush { handle: u32 },
    Close { handle: u32 },
    Check { handle: u32 },
    Scope { dir: u32, writable: bool },
    Format { handle: u32, label: Text<11> },
}

/// Checks a received message against the schema (MC-2.4): method, major version, unused bits, capability kind, and
/// for buffer calls every length and value of a private copy of the request (MC-2.11). `cap` is the slot passed to
/// `recv`; an unexpected capability is dropped (MC-2.12). The `Call` is what the reply functions need.
/// The private copy is `scratch`, which the `bytes` of the request borrow.
pub fn decode<'a>(request: &Received, cap: usize, scratch: &'a mut [u8; REQUEST_MAX]) -> core::result::Result<(Request<'a>, Call), Reject> {
    let words = request.data;
    wire::header(request, cap, MAJOR)?;
    match words[0] & 0xFF {
        1 => {
            let (call, length) = wire::take_buffer(request, cap, 4, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let name = <Text<16> as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Root { name }, call))
        }
        2 => {
            let (call, length) = wire::take_buffer(request, cap, 4, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let dir = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let path = <Text<255> as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let create = <bool as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::OpenDir { dir, path, create }, call))
        }
        3 => {
            let (call, length) = wire::take_buffer(request, cap, 4, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let dir = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let path = <Text<255> as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let mode = <u8 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Open { dir, path, mode }, call))
        }
        4 => {
            let (call, length) = wire::take_buffer(request, cap, 16386, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let file = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let offset = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let length = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Read { file, offset, length }, call))
        }
        5 => {
            let (call, length) = wire::take_buffer(request, cap, 4, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let file = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let offset = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let data = codec::decode_bytes::<16384>(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Write { file, offset, data }, call))
        }
        6 => {
            wire::body(request, cap, [0xffffffff0000, 0xffffffff], CAP_KIND_NONE, false)?;
            Ok((Request::Truncate { file: wire::field(&words, 0, 16, 32) as u32, size: wire::field(&words, 1, 0, 32) as u32 }, Call::words(request, cap)))
        }
        7 => {
            let (call, length) = wire::take_buffer(request, cap, 267, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let handle = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Stat { handle }, call))
        }
        8 => {
            let (call, length) = wire::take_buffer(request, cap, 4274, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let dir = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let start = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::List { dir, start }, call))
        }
        9 => {
            let (call, length) = wire::take_buffer(request, cap, 0, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let dir = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let path = <Text<255> as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Remove { dir, path }, call))
        }
        10 => {
            let (call, length) = wire::take_buffer(request, cap, 0, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let dir = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let from = <Text<255> as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let target = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let to = <Text<255> as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Rename { dir, from, target, to }, call))
        }
        11 => {
            let (call, length) = wire::take_buffer(request, cap, 53, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let handle = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Volume { handle }, call))
        }
        12 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::Flush { handle: wire::field(&words, 0, 16, 32) as u32 }, Call::words(request, cap)))
        }
        13 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::Close { handle: wire::field(&words, 0, 16, 32) as u32 }, Call::words(request, cap)))
        }
        14 => {
            let (call, length) = wire::take_buffer(request, cap, 298, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let handle = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Check { handle }, call))
        }
        15 => {
            wire::body(request, cap, [0x1ffffffff0000, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::Scope { dir: wire::field(&words, 0, 16, 32) as u32, writable: wire::field(&words, 0, 48, 1) != 0 }, Call::words(request, cap)))
        }
        16 => {
            let (call, length) = wire::take_buffer(request, cap, 0, &mut *scratch)?;
            let copy: &'a [u8; REQUEST_MAX] = scratch;
            let mut r = Reader::new(&copy[..length]);
            let handle = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let label = <Text<11> as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Format { handle, label }, call))
        }
        _ => { wire::discard(request, cap); Err(Reject::Invalid) }
    }
}

pub fn reply_root(call: Call, value: core::result::Result<u32, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| value.encode(w))
}
pub fn reply_open_dir(call: Call, value: core::result::Result<u32, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| value.encode(w))
}
pub fn reply_open(call: Call, value: core::result::Result<u32, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| value.encode(w))
}
pub fn reply_read(call: Call, value: core::result::Result<&[u8], Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| codec::encode_bytes::<16384>(value, w))
}
pub fn reply_write(call: Call, value: core::result::Result<u32, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| value.encode(w))
}
pub fn reply_truncate(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [0, 0])
}
pub fn reply_stat(call: Call, value: core::result::Result<&Entry, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| value.encode(w))
}
pub fn reply_list(call: Call, value: core::result::Result<&[Entry], Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| codec::encode_slice::<Entry, 16>(value, w))
}
pub fn reply_remove(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |_| Some(()))
}
pub fn reply_rename(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |_| Some(()))
}
pub fn reply_volume(call: Call, value: core::result::Result<&Volume, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| value.encode(w))
}
pub fn reply_flush(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [0, 0])
}
pub fn reply_close(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [0, 0])
}
pub fn reply_check(call: Call, value: core::result::Result<&Report, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| value.encode(w))
}
/// `value` is the handle of the capability to send (copied).
pub fn reply_scope(call: Call, value: core::result::Result<usize, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish_cap(call, value, false)
}
pub fn reply_format(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |_| Some(()))
}