// Generated by scripts/mind_idl.py from idl/voice.wit; do not edit.
//! Voice control (docs/voice V2, issue 079): the line from the `voice` program to the shell. The shell starts `voice` and
//! lends it a client of this interface in SLOT_INIT; `voice` hears and recognizes, the shell — the user's agent —
//! decides what a phrase does and what to answer, with the same rules as for typed commands (Art. 8.1–8.2, MC-3.11).
#![allow(clippy::all, unused_imports, unused_mut, unused_variables)]
use crate::abi::*;
use crate::ipc::{Endpoint, Received};
use crate::mem::Pages;
use crate::sys::{Error, Result};
use super::codec::{self, List, Reader, Text, Wire, Writer};
use super::wire::{self, Call, Reject};

pub const PACKAGE: &str = "mind:voice";
pub const VERSION: (u8, u8, u8) = (1, 0, 0);
const MAJOR: usize = 1;

/// What `voice` does after speaking the order's text: wait for the next push-to-talk, listen at once (for a
/// question the shell asked), listen for yes or no only (a confirmation), or end.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[repr(u8)]
pub enum Action { #[default] Wait = 0, Listen = 1, ListenYesNo = 2, Quit = 3 }
impl Action {
    /// The case with wire code `code`; None for a code the interface does not define.
    pub fn from_code(code: usize) -> Option<Self> { match code { 0 => Some(Self::Wait), 1 => Some(Self::Listen), 2 => Some(Self::ListenYesNo), 3 => Some(Self::Quit), _ => None } }
}
impl Wire for Action {
    const MAX: usize = 1;
    fn encode(&self, w: &mut Writer) -> Option<()> { (*self as u8).encode(w) }
    fn decode(r: &mut Reader) -> Option<Self> { Self::from_code(u8::decode(r)? as usize) }
}

/// Speak `say` (nothing if empty), then do `action`.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Order { pub say: Text<240>, pub action: Action }
impl Wire for Order {
    const MAX: usize = <Text<240> as Wire>::MAX + <Action as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.say.encode(w)?; self.action.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { say: Wire::decode(r)?, action: Wire::decode(r)? }) }
}

/// What the last utterance was — `heard` false at the start, after `wait` and when nothing was heard; `understood`
/// false when the recognizer refused it — and the next order. The shell answers when it has one: at push-to-talk,
/// or at once with its reply.
pub fn next(endpoint: Endpoint, heard: bool, understood: bool, text: &str, intent: &str, slots: &str, confidence: u16) -> Result<Order> {
    let mut buffer = Pages::new(4096).ok_or(Error::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        heard.encode(&mut w).ok_or(Error::Invalid)?;
        understood.encode(&mut w).ok_or(Error::Invalid)?;
        codec::encode_str::<120>(text, &mut w).ok_or(Error::Invalid)?;
        codec::encode_str::<16>(intent, &mut w).ok_or(Error::Invalid)?;
        codec::encode_str::<120>(slots, &mut w).ok_or(Error::Invalid)?;
        confidence.encode(&mut w).ok_or(Error::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 1 | MAJOR << 8, &buffer, length)?;
    let length = wire::buffer_reply(&reply, 243, false, false)?;
    let length = length.ok_or(Error::Invalid)?;
    Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <Order as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(Error::Invalid)? })
}

/// A request to the `voice` interface that passed the receiver's schema check.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Request {
    Next { heard: bool, understood: bool, text: Text<120>, intent: Text<16>, slots: Text<120>, confidence: u16 },
}

/// Checks a received message against the schema (MC-2.4): method, major version, unused bits, capability kind, and
/// for buffer calls every length and value of a private copy of the request (MC-2.11). `cap` is the slot passed to
/// `recv`; an unexpected capability is dropped (MC-2.12). The `Call` is what the reply functions need.
pub fn decode(request: &Received, cap: usize) -> core::result::Result<(Request, Call), Reject> {
    let words = request.data;
    wire::header(request, cap, MAJOR)?;
    match words[0] & 0xFF {
        1 => {
            let mut copy = [0u8; 266];
            let (call, length) = wire::take_buffer(request, cap, 243, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            let heard = <bool as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let understood = <bool as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let text = <Text<120> as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let intent = <Text<16> as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let slots = <Text<120> as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let confidence = <u16 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Next { heard, understood, text, intent, slots, confidence }, call))
        }
        _ => { wire::discard(request, cap); Err(Reject::Invalid) }
    }
}

pub fn reply_next(call: Call, value: &Order) -> Result<()> {
    wire::reply_buffer(call, |w| value.encode(w))
}