// Generated by scripts/mind_idl.py from idl/window.wit; do not edit.
//! Window broker (`windows`, issue 157): keeps the windows of programs so they outlive the window manager. A window's
//! surface (layout in `mind::window`) is memory of the broker, lent to the program that draws in it and to the manager
//! that shows it: neither can take it from the other or from the broker. A program may lend an endpoint to wake it;
//! the broker keeps the window's last place on the screen. One manager at a time (the manager badge, which the shell lends
//! for `REQUEST_WINDOW_MANAGER`) attaches, gets the windows, copies of their surfaces and wake endpoints, saves where
//! it puts them, and either detaches (windows and programs stay, hidden) or closes all (every program is asked to end).
//! A manager that ends is detached. A window ends with its program.
#![allow(clippy::all, unused_imports, unused_mut, unused_variables)]
use crate::abi::*;
use crate::ipc::{Endpoint, Received};
use crate::mem::Pages;
use crate::sys::{Error as SysError, Result};
use super::codec::{self, List, Reader, Text, Wire, Writer};
use super::wire::{self, Call, Reject};

pub const PACKAGE: &str = "mind:window";
pub const VERSION: (u8, u8, u8) = (1, 0, 0);
const MAJOR: usize = 1;

/// Why a request failed. `denied`: not the manager, or not the window's owner; `busy`: another manager is attached.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[repr(u8)]
pub enum Error { #[default] Invalid = 0, Limit = 1, NotFound = 2, Denied = 3, Busy = 4 }
impl Error {
    /// The case with wire code `code`; None for a code the interface does not define.
    pub fn from_code(code: usize) -> Option<Self> { match code { 0 => Some(Self::Invalid), 1 => Some(Self::Limit), 2 => Some(Self::NotFound), 3 => Some(Self::Denied), 4 => Some(Self::Busy), _ => None } }
}
impl Wire for Error {
    const MAX: usize = 1;
    fn encode(&self, w: &mut Writer) -> Option<()> { (*self as u8).encode(w) }
    fn decode(r: &mut Reader) -> Option<Self> { Self::from_code(u8::decode(r)? as usize) }
}

/// What a window's content is.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
#[repr(u8)]
pub enum Kind { #[default] Text = 0, Pixels = 1 }
impl Kind {
    /// The case with wire code `code`; None for a code the interface does not define.
    pub fn from_code(code: usize) -> Option<Self> { match code { 0 => Some(Self::Text), 1 => Some(Self::Pixels), _ => None } }
}
impl Wire for Kind {
    const MAX: usize = 1;
    fn encode(&self, w: &mut Writer) -> Option<()> { (*self as u8).encode(w) }
    fn decode(r: &mut Reader) -> Option<Self> { Self::from_code(u8::decode(r)? as usize) }
}

/// Where the manager put a window: position and size in cells, stacking order (higher: in front), minimized or
/// maximized.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Placement { pub x: u16, pub y: u16, pub columns: u16, pub rows: u16, pub z: u16, pub minimized: bool, pub maximized: bool }
impl Wire for Placement {
    const MAX: usize = <u16 as Wire>::MAX + <u16 as Wire>::MAX + <u16 as Wire>::MAX + <u16 as Wire>::MAX + <u16 as Wire>::MAX + <bool as Wire>::MAX + <bool as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.x.encode(w)?; self.y.encode(w)?; self.columns.encode(w)?; self.rows.encode(w)?; self.z.encode(w)?; self.minimized.encode(w)?; self.maximized.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { x: Wire::decode(r)?, y: Wire::decode(r)?, columns: Wire::decode(r)?, rows: Wire::decode(r)?, z: Wire::decode(r)?, minimized: Wire::decode(r)?, maximized: Wire::decode(r)? }) }
}

/// A window as the manager sees it: its id, the program, the content's kind and size (cells or pixels), the title
/// and the last placement (all 0 until a manager placed it).
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq)]
pub struct Info { pub id: u32, pub owner: u64, pub kind: Kind, pub width: u16, pub height: u16, pub title: Text<64>, pub place: Placement }
impl Wire for Info {
    const MAX: usize = <u32 as Wire>::MAX + <u64 as Wire>::MAX + <Kind as Wire>::MAX + <u16 as Wire>::MAX + <u16 as Wire>::MAX + <Text<64> as Wire>::MAX + <Placement as Wire>::MAX;
    fn encode(&self, w: &mut Writer) -> Option<()> { self.id.encode(w)?; self.owner.encode(w)?; self.kind.encode(w)?; self.width.encode(w)?; self.height.encode(w)?; self.title.encode(w)?; self.place.encode(w)?; Some(()) }
    fn decode(r: &mut Reader) -> Option<Self> { Some(Self { id: Wire::decode(r)?, owner: Wire::decode(r)?, kind: Wire::decode(r)?, width: Wire::decode(r)?, height: Wire::decode(r)?, title: Wire::decode(r)?, place: Wire::decode(r)? }) }
}

/// Program: a new window with a surface for `width` × `height` cells (text: up to 256 × 128) or pixels (up to
/// 1920 × 1200); returns its id. The surface comes from `surface`.
pub fn create(endpoint: Endpoint, kind: Kind, width: u16, height: u16) -> Result<core::result::Result<u32, Error>> {
    let words = [1 | MAJOR << 8 | ((kind) as usize) << 16 | ((width) as usize) << 24 | ((height) as usize) << 40, 0];
    let reply = wire::call(endpoint, words, None)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let _ = wire::check_reply(&reply, [0xffffffff0000, 0x0], false)?;
    Ok(Ok(wire::field(&reply, 0, 16, 32) as u32))
}

/// Program: an endpoint the manager sends a short message to when it queued input events.
pub fn wake(endpoint: Endpoint, window: u32, waker: usize) -> Result<core::result::Result<(), Error>> {
    let words = [2 | MAJOR << 8 | ((window) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, Some((waker, false)))?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    wire::check_reply(&reply, [0, 0], false)?;
    Ok(Ok(()))
}

/// Program: removes its window.
pub fn remove(endpoint: Endpoint, window: u32) -> Result<core::result::Result<(), Error>> {
    let words = [3 | MAJOR << 8 | ((window) as usize) << 16, 0];
    let reply = wire::call(endpoint, words, None)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    wire::check_reply(&reply, [0, 0], false)?;
    Ok(Ok(()))
}

/// Manager: attaches; returns how many windows there are.
pub fn attach(endpoint: Endpoint) -> Result<core::result::Result<u32, Error>> {
    let words = [4 | MAJOR << 8, 0];
    let reply = wire::call(endpoint, words, None)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let _ = wire::check_reply(&reply, [0xffffffff0000, 0x0], false)?;
    Ok(Ok(wire::field(&reply, 0, 16, 32) as u32))
}

/// Manager: detaches; the windows stay, hidden.
pub fn detach(endpoint: Endpoint) -> Result<core::result::Result<(), Error>> {
    let words = [5 | MAJOR << 8, 0];
    let reply = wire::call(endpoint, words, None)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    wire::check_reply(&reply, [0, 0], false)?;
    Ok(Ok(()))
}

/// Manager: asks every window's program to end (state close in its surface, a wake message); returns how many.
pub fn close_all(endpoint: Endpoint) -> Result<core::result::Result<u32, Error>> {
    let words = [6 | MAJOR << 8, 0];
    let reply = wire::call(endpoint, words, None)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let _ = wire::check_reply(&reply, [0xffffffff0000, 0x0], false)?;
    Ok(Ok(wire::field(&reply, 0, 16, 32) as u32))
}

/// Manager: the windows from the `start`-th on, oldest first.
pub fn list(endpoint: Endpoint, start: u32) -> Result<core::result::Result<List<Info, 16>, Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        start.encode(&mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 7 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 1522, false, false)?;
    let length = length.ok_or(SysError::Invalid)?;
    Ok(Ok({ let mut r = Reader::new(&buffer.as_slice()[..length]); <List<Info, 16> as Wire>::decode(&mut r).filter(|_| r.done()).ok_or(SysError::Invalid)? }))
}

/// Manager: counts every window created or removed; list again when it changes.
pub fn generation(endpoint: Endpoint) -> Result<u64> {
    let words = [8 | MAJOR << 8, 0];
    let reply = wire::call(endpoint, words, None)?;
    let _ = wire::check_reply(&reply, [0x0, 0xffffffffffffffff], false)?;
    Ok(wire::field(&reply, 1, 0, 64) as u64)
}

/// The program that owns the window, or the manager: a read-write lease of its surface (revoked when the window
/// ends, and the manager's also when it detaches).
pub fn surface(endpoint: Endpoint, window: u32, receive: usize) -> Result<core::result::Result<(), Error>> {
    let words = [9 | MAJOR << 8 | ((window) as usize) << 16, 0];
    let (reply, received) = wire::call_receiving(endpoint, words, None, receive)?;
    match wire::check_cap_reply(&reply, received, receive)? {
        None => Ok(Ok(())),
        Some(code) => Ok(Err(Error::from_code(wire::enum_code(code)?).ok_or(SysError::Invalid)?)),
    }
}

/// Manager: a copy of the window's wake endpoint.
pub fn waker(endpoint: Endpoint, window: u32, receive: usize) -> Result<core::result::Result<(), Error>> {
    let words = [10 | MAJOR << 8 | ((window) as usize) << 16, 0];
    let (reply, received) = wire::call_receiving(endpoint, words, None, receive)?;
    match wire::check_cap_reply(&reply, received, receive)? {
        None => Ok(Ok(())),
        Some(code) => Ok(Err(Error::from_code(wire::enum_code(code)?).ok_or(SysError::Invalid)?)),
    }
}

/// Manager: saves where a window is.
pub fn place(endpoint: Endpoint, window: u32, place: &Placement) -> Result<core::result::Result<(), Error>> {
    let mut buffer = Pages::new(4096).ok_or(SysError::NoMemory)?;
    let length = {
        let mut w = Writer::new(buffer.as_mut_slice());
        window.encode(&mut w).ok_or(SysError::Invalid)?;
        place.encode(&mut w).ok_or(SysError::Invalid)?;
        w.len()
    };
    let reply = wire::call_buffer(endpoint, 11 | MAJOR << 8, &buffer, length)?;
    if let Some(code) = wire::enum_error(&reply)? { return Ok(Err(Error::from_code(code).ok_or(SysError::Invalid)?)); }
    let length = wire::buffer_reply(&reply, 0, false, false)?;
    if length != Some(0) { return Err(SysError::Invalid); }
    Ok(Ok(()))
}

/// Manager: a program's client of the broker, to lend to programs it starts in windows.
pub fn client(endpoint: Endpoint, receive: usize) -> Result<core::result::Result<(), Error>> {
    let words = [12 | MAJOR << 8, 0];
    let (reply, received) = wire::call_receiving(endpoint, words, None, receive)?;
    match wire::check_cap_reply(&reply, received, receive)? {
        None => Ok(Ok(())),
        Some(code) => Ok(Err(Error::from_code(wire::enum_code(code)?).ok_or(SysError::Invalid)?)),
    }
}

/// A request to the `window` interface that passed the receiver's schema check.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Request {
    Create { kind: Kind, width: u16, height: u16 },
    Wake { window: u32, waker: usize },
    Remove { window: u32 },
    Attach,
    Detach,
    CloseAll,
    List { start: u32 },
    Generation,
    Surface { window: u32 },
    Waker { window: u32 },
    Place { window: u32, place: Placement },
    Client,
}

/// Checks a received message against the schema (MC-2.4): method, major version, unused bits, capability kind, and
/// for buffer calls every length and value of a private copy of the request (MC-2.11). `cap` is the slot passed to
/// `recv`; an unexpected capability is dropped (MC-2.12). The `Call` is what the reply functions need.
pub fn decode(request: &Received, cap: usize) -> core::result::Result<(Request, Call), Reject> {
    let words = request.data;
    wire::header(request, cap, MAJOR)?;
    match words[0] & 0xFF {
        1 => {
            wire::body(request, cap, [0xffffffffff0000, 0x0], CAP_KIND_NONE, false)?;
            let Some(kind) = Kind::from_code(wire::field(&words, 0, 16, 8)) else { wire::discard(request, cap); return Err(Reject::Invalid) };
            Ok((Request::Create { kind, width: wire::field(&words, 0, 24, 16) as u16, height: wire::field(&words, 0, 40, 16) as u16 }, Call::words(request, cap)))
        }
        2 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_ENDPOINT, true)?;
            Ok((Request::Wake { window: wire::field(&words, 0, 16, 32) as u32, waker: cap }, Call::words(request, cap)))
        }
        3 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::Remove { window: wire::field(&words, 0, 16, 32) as u32 }, Call::words(request, cap)))
        }
        4 => {
            wire::body(request, cap, [0x0, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::Attach, Call::words(request, cap)))
        }
        5 => {
            wire::body(request, cap, [0x0, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::Detach, Call::words(request, cap)))
        }
        6 => {
            wire::body(request, cap, [0x0, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::CloseAll, Call::words(request, cap)))
        }
        7 => {
            let mut copy = [0u8; 4];
            let (call, length) = wire::take_buffer(request, cap, 1522, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            let start = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::List { start }, call))
        }
        8 => {
            wire::body(request, cap, [0x0, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::Generation, Call::words(request, cap)))
        }
        9 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::Surface { window: wire::field(&words, 0, 16, 32) as u32 }, Call::words(request, cap)))
        }
        10 => {
            wire::body(request, cap, [0xffffffff0000, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::Waker { window: wire::field(&words, 0, 16, 32) as u32 }, Call::words(request, cap)))
        }
        11 => {
            let mut copy = [0u8; 16];
            let (call, length) = wire::take_buffer(request, cap, 0, &mut copy)?;
            let mut r = Reader::new(&copy[..length]);
            let window = <u32 as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            let place = <Placement as Wire>::decode(&mut r).ok_or(Reject::Invalid)?;
            if !r.done() { return Err(Reject::Invalid); }
            Ok((Request::Place { window, place }, call))
        }
        12 => {
            wire::body(request, cap, [0x0, 0x0], CAP_KIND_NONE, false)?;
            Ok((Request::Client, Call::words(request, cap)))
        }
        _ => { wire::discard(request, cap); Err(Reject::Invalid) }
    }
}

pub fn reply_create(call: Call, value: core::result::Result<u32, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [((value) as usize) << 16, 0])
}
pub fn reply_wake(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [0, 0])
}
pub fn reply_remove(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [0, 0])
}
pub fn reply_attach(call: Call, value: core::result::Result<u32, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [((value) as usize) << 16, 0])
}
pub fn reply_detach(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [0, 0])
}
pub fn reply_close_all(call: Call, value: core::result::Result<u32, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish(call, [((value) as usize) << 16, 0])
}
pub fn reply_list(call: Call, value: core::result::Result<&[Info], Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |w| codec::encode_slice::<Info, 16>(value, w))
}
pub fn reply_generation(call: Call, value: u64) -> Result<()> {
    wire::finish(call, [0, ((value) as usize) << 0])
}
/// `value` is the handle of the capability to send (copied).
pub fn reply_surface(call: Call, value: core::result::Result<usize, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish_cap(call, value, false)
}
/// `value` is the handle of the capability to send (copied).
pub fn reply_waker(call: Call, value: core::result::Result<usize, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish_cap(call, value, false)
}
pub fn reply_place(call: Call, value: core::result::Result<(), Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::reply_buffer(call, |_| Some(()))
}
/// `value` is the handle of the capability to send (copied).
pub fn reply_client(call: Call, value: core::result::Result<usize, Error>) -> Result<()> {
    let value = match value { Ok(value) => value, Err(error) => return wire::reply_code(call, error as usize) };
    wire::finish_cap(call, value, false)
}